force-app/main/default/objects/COMM_SubscriptionInvoice__c/COMM_SubscriptionInvoice__c.object-meta.xml
<CustomObject>
    <description>Represents an Invoice for a Subscription</description>
    <label>Subscription Invoice</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Subscription Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_IssuanceDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_IssuanceDate__c</fullName>
    <description>Date when invoice is issued</description>
    <label>Issuance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_SAPNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_SAPNumber__c</fullName>
    <description>Invoice Number used in SAP</description>
    <label>SAP Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_Status__c.field-meta.xml
<CustomField>
    <fullName>COMM_Status__c</fullName>
    <description>Status of the Invoice</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/COMM_REP_SubscriptionInvoice.cls
/**
 * @author Daniel Lascas
 * @description COMM_SubscriptionInvoice__c repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    28/03/2024       ECOMM-194: Original version
 **/
public inherited sharing class COMM_REP_SubscriptionInvoice extends FW_SobjectRep implements COMM_IREP_SubscriptionInvoice {
    /**
     * @description Retrieve the list of Subscription Invoice Records by a Set of Ids
     *
     * @param invoiceIds Set of Subscription Invoice Ids to query invoices
     * @return List of Subscription Invoice Records found
     **/
    public List<COMM_SubscriptionInvoice__c> getSubInvoiceByIds(Set<Id> invoiceIds) {
        return [
            SELECT Id, COMM_Status__c, COMM_SAPNumber__c, COMM_IssuanceDate__c
            FROM COMM_SubscriptionInvoice__c
            WHERE Id IN :invoiceIds
            WITH USER_MODE
        ];
    }
}