force-app/main/default/objects/COMM_ProductVariations__c/COMM_ProductVariations__c.object-meta.xml
<CustomObject>
    <description>Represents a Variation of the Product</description>
    <label>Product Variation</label>
    <nameField>
        <displayFormat>VA-{0000}</displayFormat>
        <label>Variation Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Variations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_ProductVariations__c/fields/COMM_MasterProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_MasterProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bundle Product that aggregates related Products</description>
    <label>Master Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Master Product must be Type=bundle</errorMessage>
        <filterItems>
            <field>Product2.COMM_ProductType__c</field>
            <operation>equals</operation>
            <value>bundle</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Variations</relationshipLabel>
    <relationshipName>ProductVariationsMaster</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_ProductVariations__c/fields/COMM_NumberOfHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_NumberOfHours__c</fullName>
    <description>Number of Hours the Related Product is reserved when bundle is bought</description>
    <label>Number of Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_ProductVariations__c/fields/COMM_Quantity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Quantity__c</fullName>
    <description>Related product quantity</description>
    <label>Quantity</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_ProductVariations__c/fields/COMM_RelatedProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_RelatedProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product included in the bundle</description>
    <label>Related Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Related Product must be Type=single</errorMessage>
        <filterItems>
            <field>Product2.COMM_ProductType__c</field>
            <operation>equals</operation>
            <value>single</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Variations (Related Product)</relationshipLabel>
    <relationshipName>ProductVariationsRelated</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Product for the Product Record</description>
    <label>Parent Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Airport needs to be the same in both Parent and Child Product</errorMessage>
        <filterItems>
            <field>Product2.COMM_Airport__c</field>
            <operation>equals</operation>
            <valueField>$Source.COMM_Airport__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ParentProductCode__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentProductCode__c</fullName>
    <description>Product Code of Parent Product</description>
    <formula>COMM_ParentProduct__r.ProductCode</formula>
    <label>Parent Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date for which the product is deemed valid</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_REP_ProductVariations.cls
/**
 * @author Daniel Lascas
 * @description COMM_ProductVariations__c repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    20/05/2024       ECOMM-386: Original version
 **/
public inherited sharing class COMM_REP_ProductVariations extends FW_SobjectRep implements COMM_IREP_ProductVariations {
    /**
     * @description Given a set of Product Ids. Retrieve Product Variations
     * for those products.
     *
     * @param productIds Set of Product Ids
     * @return Product Variation Records found
     */
    public List<COMM_ProductVariations__c> getProductVariationsByProductId(Set<Id> productIds) {
        return [
            SELECT
                Id,
                COMM_Quantity__c,
                COMM_NumberOfHours__c,
                COMM_MasterProduct__c,
                COMM_RelatedProduct__c,
                COMM_RelatedProduct__r.ProductCode,
                COMM_RelatedProduct__r.Name,
                COMM_RelatedProduct__r.Family,
            	COMM_RelatedProduct__r.COMM_Airport__c,
                COMM_RelatedProduct__r.COMM_ValidFrom__c,
                COMM_RelatedProduct__r.COMM_ValidTo__c,
                COMM_RelatedProduct__r.COMM_ParentProduct__c,
                COMM_RelatedProduct__r.COMM_ParentProductCode__c
            FROM COMM_ProductVariations__c
            WHERE COMM_MasterProduct__c IN :productIds
            WITH USER_MODE
        ];
    }
        
    /**
     * @description Retrieve a list of COMM_ProductVariations__c by a set of master product codes
     *
     * @param productCodes - Set of master product codes to query
     * @return {List<COMM_ProductVariations__c>}
     **/
    public List<COMM_ProductVariations__c> getProductVariationsByMasterProduct(Set<String> masterProductCodes) {
        return [
            SELECT Id, COMM_MasterProduct__r.ProductCode, COMM_RelatedProduct__r.ProductCode
            FROM COMM_ProductVariations__c
            WHERE COMM_MasterProduct__r.ProductCode IN :masterProductCodes
            WITH USER_MODE
        ];
    }
}