force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <inlineHelpText>This is used programmatically to execute the batch.</inlineHelpText>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Execute__c.field-meta.xml
<CustomField>
    <fullName>Execute__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to check whether to execute the job</description>
    <label>Execute</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Is_Scheduled_run__c.field-meta.xml
<CustomField>
    <fullName>Is_Scheduled_run__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Scheduled run?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Scheduled_Execution_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Execution_DateTime__c</fullName>
    <description>Time at which the user wants to manually schedule the job (if not now)</description>
    <label>Scheduled Execution DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FW_DO_JobExecution.cls
/**
    * @description   Job execution domain object class
    * @testClass     FW_DO_JobExecutionTest
    * Modification Log 
	* ------------------------------------------------------------------------------------  
	* Developer                       Date                Description  
    * ------------------------------------------------------------------------------------ 
*/
public inherited sharing class FW_DO_JobExecution implements FW_IDO_JobExecution {

    public final static String JOB_EXEC_STATUS_NEW = 'New';
    public final static String JOB_EXEC_STATUS_CANCELLED = 'Cancelled';
    public final static String JOB_EXEC_STATUS_STARTED = 'Started';
    public final static String JOB_EXEC_STATUS_SCHEDULED = 'Scheduled';
    public final static String JOB_EXEC_STATUS_FINISHED = 'Finished';
    public final static String JOB_EXEC_STATUS_FINISHED_ERRORS = 'Finished_with_Errors';
    public final static String JOB_EXEC_RECORD_TYPE_INITIAL = 'Initial';
    public final static String JOB_EXEC_RECORD_TYPE_DEFINED = 'Defined';

    /**
        * @description:    Method to clone a parameter and set JobExectutionId
    */
    public Parameters__c getClonedParameter(Parameters__c parameter, Id jobExecutionId){
        Parameters__c clonedParameter = parameter.clone(false, false);
        clonedParameter.Batch_Definition__c = null;
        clonedParameter.Job_Execution__c = jobExecutionId;
        return clonedParameter;
    }
    
    /**
        * @description:    Checks if execute field is checked
    */
    public Boolean isToExecute(Job_Execution__c jobExecution){
        return jobExecution.Execute__c;
    }

    /**
        * @description:    Checks if execute field is checked
    */
    public Boolean isScheduledRun(Job_Execution__c jobExecution){
        return jobExecution.Is_Scheduled_run__c;
    }

    /**
        * @description:    Checks if Job Execution job size is equals to the Batch Definition job size
    */
    public Boolean isJobSizeEqualsToBatchDefinitionJobSize(Job_Execution__c jobExecution, Batch_Definition__c batchDefinition) {
        return jobExecution.Job_Size__c == batchDefinition.Job_Size__c;
    }

    /**
        * @description:    Checks if the Job Execution is checked to run with default parameters
    */
    public Boolean isRunningwithDefaults(Job_Execution__c jobExecution) {
        return jobExecution.Run_with_Defaults__c;
    }
    
    /**
        * @description:    execute a batch job
    */
    public Id executeBatch(Job_Execution__c jobExecution, Batch_Definition__c batchDefinition) {
        Type customType = Type.forName(batchDefinition.Class_Name__c);

        FW_IAsync batchInterface = (FW_IAsync) customType.newInstance();

        batchInterface.setJobExecutionId(jobExecution.Id);

        return Database.executeBatch(
            (Database.Batchable<SObject>)batchInterface, 
            (Integer)jobExecution.Job_Size__c
        );
    }

    /**
        * @description:    Schedule a batch job
    */
    public Id scheduleBatch(Job_Execution__c jobExecution, Batch_Definition__c batchDefinition) {

        Type customType = Type.forName(batchDefinition.Class_Name__c);

        FW_IAsync batchInterface = (FW_IAsync) customType.newInstance();        
        batchInterface.setJobExecutionId(jobExecution.Id);
        
        return System.scheduleBatch(
                                    (Database.Batchable<SObject>)batchInterface,
                                    'Scheduled Job -' + String.valueOf(jobExecution.Scheduled_Execution_DateTime__c) + ' - ' + batchDefinition.Batch_Name__c,
                                    getDifferenceInMinutesFromNow(jobExecution.Scheduled_Execution_DateTime__c),
                                    (Integer)jobExecution.Job_Size__c
                                   );

    }

    /**
        * @description:    Returns the difference between current time and a given DateTime
    */
    public Integer getDifferenceInMinutesFromNow(DateTime dt1) {
        return (Integer)((dt1.getTime() - Datetime.now().getTime()) / 60000) + 1;
    }

    /**
        *  @description:    Returns the difference between current time and a given DateTime
    */
    public Job_Execution__c createJobExecutionsFromBD(Id batchDefinitionID){
    
        return new Job_Execution__c(
                    Batch_Definition__c = batchDefinitionID,
                    Is_Scheduled_run__c = true
                );
    }
    
    /**
        * @description:    abort a running job by specified ID
    */ 
    public void abortJob(String asyncId){
        if(test.isRunningTest()){
            System.abortJob(asyncId);
        }
    }
    
}