force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>To capture all sort of errors</description>
    <label>Error and Log</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors and Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Job Execution record, it is filled if the error comes from the Batch Framework</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipName>Error_and_Monitoring_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FW_REP_JobExecutionTest.cls
@isTest
public class FW_REP_JobExecutionTest {
    @isTest
    static void jobExecutionRepositoryTest(){
        User runningUser = FW_TestDataFactory.createUsers(1, true, 'System Administrator', null).get(0);
        system.runAs(runningUser){  
            Id batchDefinitionId = FW_TestDataFactory.createBatchDefinition(1, true).get(0).Id;
            List<Job_Execution__c> jobExecutionList = FW_TestDataFactory.createJobExecution(2, false, FW_DO_JobExecution.JOB_EXEC_RECORD_TYPE_INITIAL, batchDefinitionId);
            jobExecutionList.get(1).AsyncApexJobId__c = fflib_IDGenerator.generate(AsyncApexJob.sObjectType);

            test.startTest();
                FW_REP_JobExecution jobExecutionRepository = new FW_REP_JobExecution();
                jobExecutionRepository.insertSObjects(jobExecutionList);
                List<Job_Execution__c> jobExecutionFromIdSet = jobExecutionRepository.getJobExecwithBatchDefinitionsByIdSet(new Set<Id>{jobExecutionList.get(0).Id, jobExecutionList.get(1).Id});
                List<Job_Execution__c> jobExecutionFromAsyncJobId = jobExecutionRepository.getJobExecutionByAsyncApexJobIdSet(jobExecutionList.get(1).AsyncApexJobId__c);
                List<Job_Execution__c> jobExecutionFromAsyncJobIdSet = jobExecutionRepository.getJobExecutionByAsyncApexJobIdSet(new Set<Id>{null});
                
            test.stopTest();

            system.assertEquals(2, jobExecutionFromIdSet.size());
            system.assertEquals(1, jobExecutionFromAsyncJobId.size());
            system.assertEquals(1, jobExecutionFromAsyncJobIdSet.size());
        }
    }

    @isTest
    static void insertSObjectsTest(){
        User runningUser = FW_TestDataFactory.createUsers(1, true, 'System Administrator', null).get(0);
        system.runAs(runningUser){  
            Id batchDefinitionId = FW_TestDataFactory.createBatchDefinition(1, true).get(0).Id;
            List<Job_Execution__c> jobExecutionList = FW_TestDataFactory.createJobExecution(2, false, FW_DO_JobExecution.JOB_EXEC_RECORD_TYPE_INITIAL, batchDefinitionId);

            test.startTest();
                FW_REP_JobExecution jobExecutionRepository = new FW_REP_JobExecution();
                List<Database.SaveResult> saveResultsSuccessList = jobExecutionRepository.insertSObjects(jobExecutionList);

                for( Database.SaveResult res : saveResultsSuccessList ){
                    System.assertEquals(true, res.isSuccess());
                }

                jobExecutionList = FW_TestDataFactory.createJobExecution(2, false, FW_DO_JobExecution.JOB_EXEC_RECORD_TYPE_INITIAL, batchDefinitionId);
                jobExecutionList.get(1).Batch_Definition__c = null;
                saveResultsSuccessList = jobExecutionRepository.insertSObjects(jobExecutionList);

                for( Database.SaveResult res : saveResultsSuccessList ){
                    System.assertEquals(false, res.isSuccess());
                }
                
            test.stopTest();  

            // Integration testing to assess events were published:
            Test.getEventBus().deliver();     

            FW_IREP_ErrorLog errorRep = new FW_REP_ErrorLog();
            List<Error_Log__c> errorLogList = errorRep.getErrorLogListByJobExecutionIdSet( new Set<Id>{ jobExecutionList.get(0).Id, jobExecutionList.get(1).Id });
            System.assertEquals(jobExecutionList.size(), errorLogList.size());
        }
    }
}