force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FW_TW_JobExecution_CopyBDConfig.cls
/**
    @description    worker class to copy default configuration from Batch Definition to JobExecution when it is set to run with defaults
    @testClass      FW_THWB_JobExecution_CopyBDConfigTest
    * Modification Log 
	* ------------------------------------------------------------------------------------  
	* Developer                       Date                Description  
    * ------------------------------------------------------------------------------------
*/
public without sharing class FW_TW_JobExecution_CopyBDConfig {
    private FW_IREP_BatchDefinition bdRepository;
    
    public FW_TW_JobExecution_CopyBDConfig(){
        this.bdRepository = new FW_REP_BatchDefinition();
    }
    
    @TestVisible
    private FW_TW_JobExecution_CopyBDConfig(FW_IREP_BatchDefinition bdRepository){
        this.bdRepository = bdRepository;
    }

    public void execute(List<Job_Execution__c> jobExecList) {
        Set<Id> batchDefinitionIdSet = new Set<Id>();
        for(Job_Execution__c je : jobExecList){
            if(je.Run_with_Defaults__c){
                batchDefinitionIdSet.add(je.Batch_Definition__c);
            }
        }
        
        if(!batchDefinitionIdSet.isEmpty()){
            Map<Id,Batch_Definition__c> parametersMap = New Map<id, Batch_Definition__c>(bdRepository.getBatchDefinitionByIdSet(batchDefinitionIdSet));
            for(Job_Execution__c je : jobExecList){
                je.Job_Size__c = parametersMap.get(je.Batch_Definition__c).Job_Size__c;
            }
        }
    }
}