force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <inlineHelpText>This is used programmatically to execute the batch.</inlineHelpText>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>To capture all sort of errors</description>
    <label>Error and Log</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors and Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Job Execution record, it is filled if the error comes from the Batch Framework</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipName>Error_and_Monitoring_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FW_DisableErrorLogging__c/fields/All__c.field-meta.xml
<CustomField>
    <fullName>All__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to disable error log publishing for all the exceptions</description>
    <label>All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_DisableErrorLogging__c/fields/CalloutException__c.field-meta.xml
<CustomField>
    <fullName>CalloutException__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true not to log callout exceptions</description>
    <label>CalloutException</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_DisableErrorLogging__c/fields/DMLException__c.field-meta.xml
<CustomField>
    <fullName>DMLException__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set this to true to skip DML exception logs</description>
    <label>DMLException</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_DisableErrorLogging__c/fields/QueryException__c.field-meta.xml
<CustomField>
    <fullName>QueryException__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set this flag to true to skip query exceptions</description>
    <label>QueryException</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_TriggerHandlerSettings__c/fields/All__c.field-meta.xml
<CustomField>
    <fullName>All__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag for all trigger, if true all triggers will be skipped</description>
    <label>Skip All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FW_TestDataFactory.cls
/**
    * @description   Utility class to create records for tests
    * @testClass     N/A
    * Modification Log 
	* ------------------------------------------------------------------------------------  
	* Developer                       Date                Description  
    * ------------------------------------------------------------------------------------ 
*/
@isTest
public without sharing class FW_TestDataFactory{

    public static List<Batch_Definition__c> createBatchDefinition(Integer numberOfRecords, Boolean doInsert) {
        List<Batch_Definition__c> objList = new List<Batch_Definition__c>();
        
        for(Integer i = 0; i < numberOfRecords; i++) {
            objList.add(new Batch_Definition__c(
                Batch_Name__c = 'Test ' + i,
                Class_Name__c = 'Test ' + i,
                SObject_API_Name__c = 'Batch_Definition__c'
            ));
        }

        if(doInsert && !objList.isEmpty()) {
            insert objList;
        }
        return objList;
    }

    public static void createDisableErrorLogging() {
        insert new FW_DisableErrorLogging__c(
            All__c = true,
            CalloutException__c = true,
            DMLException__c = true,
            QueryException__c = true
        );
    }

    public static List<Error_Log__c> createErrorLog(Integer numberOfRecords, Boolean doInsert) {
        List<Error_Log__c> objList = new List<Error_Log__c>();
        
        for(Integer i = 0; i < numberOfRecords; i++){
            objList.add(new Error_Log__c());
        }

        if(doInsert && !objList.isEmpty()) {
            insert objList;
        }
        return objList;
    }

    public static List<Job_Execution__c> createJobExecution(Integer numberOfRecords, Boolean doInsert, String objRecordTypeName, Id batchDefinitionId) {
        Id rTypeId = getRecordTypeIdByDevName('Job_Execution__c', objRecordTypeName);
        
        List<Job_Execution__c> objList = new List<Job_Execution__c>();
        
        for(Integer i = 0; i < numberOfRecords; i++) {
            objList.add(new Job_Execution__c(
              Run_With_Defaults__c = true,
              RecordTypeId = rTypeId,
              Batch_Definition__c = batchDefinitionId
            ));
        }

        if(doInsert && !objList.isEmpty()) {
            insert objList;
        }
        return objList;
    }

    public static List<Parameters__c> createParameter(Integer numberOfRecords, Boolean doInsert) {
        List<Parameters__c> objList = new List<Parameters__c>();
        
        for(Integer i = 0; i < numberOfRecords; i++) {
            objList.add(new Parameters__c());
        }

        if(doInsert && !objList.isEmpty()) {
            insert objList;
        }
        return objList;
    }

     public static List<User> createUsers(Integer numberOfRecords, Boolean doInsert, String userProfileName, Id contactId) {
        Id userProfileId = [SELECT Id FROM Profile WHERE Name = :userProfileName LIMIT 1].Id;
        List<User> objList = new List<User>();
        
        for(Integer i = 0; i < numberOfRecords; i++) {
            objList.add(new User(
                LastName            = 'Test Last Name ' + i,
                Alias               = string.valueof(Math.abs(Crypto.getRandomLong())).substring(0, 6),
                Username            = string.valueof(Math.abs(Crypto.getRandomLong())).substring(0, 6) + i + '@test.com',
                CommunityNickname   = string.valueof(Math.abs(Crypto.getRandomLong())).substring(0, 6) + i,
                ProfileId           = userProfileId,
                Email               = 'testemail' + i + '@test.com',
                TimeZoneSidKey      = 'Europe/Paris',
                LocaleSidKey        = 'fr_BE', 
                EmailEncodingKey    = 'ISO-8859-1',
                LanguageLocaleKey   = 'en_US',
                ContactId           = contactId
            ));
        }

        if(doInsert && !objList.isEmpty()) {
            insert objList;
        }

        return objList;
    }

    public static FW_TriggerHandlerSettings__c createTriggerHandlerSettingInactive(Boolean doAll, Boolean doInsert) {

        FW_TriggerHandlerSettings__c triggerHandlerSettings = new FW_TriggerHandlerSettings__c();
        SObjectType accountType = Schema.getGlobalDescribe().get('FW_TriggerHandlerSettings__c');
        Map<String,Schema.SObjectField> mfields = accountType.getDescribe().fields.getMap();
        
        for(Schema.SObjectField sfield : mfields.Values()) {
            schema.describefieldresult dfield = sfield.getDescribe();
            string namefield = dfield.getname();
            if(namefield.endsWith('__c')) {
                triggerHandlerSettings.put(namefield, false);
            }        
        }
        triggerHandlerSettings.put('All__c', doAll);

        if(doInsert) {
            insert triggerHandlerSettings;
        }
        return triggerHandlerSettings;
    }

    public static List<CleanErrorLogBatchSettings__c> createCleanErrorLogBatchSettings(Integer numberOfRecords, Boolean doInsert) {
        List<CleanErrorLogBatchSettings__c> objList = new List<CleanErrorLogBatchSettings__c>();
        
        for(Integer i = 0; i < numberOfRecords; i++) {
            objList.add(new CleanErrorLogBatchSettings__c(
              Name = 'Default',
              NumberOfDays__c = 2
            ));
        }

        if(doInsert && !objList.isEmpty()) {
            insert objList;
        }
        return objList;
    }

    private static Id getRecordTypeIdByDevName(String sObjType, String devName){

        Id recTypeId = null;

        try {
            final Map<String, Schema.SObjectType> sObjectTypeMap = Schema.getGlobalDescribe();
            if (sObjectTypeMap.containsKey(sObjType)) {
                final Map<String, Schema.RecordTypeInfo> recordTypeInfoMap = sObjectTypeMap.get(sObjType).getDescribe().getRecordTypeInfosByDeveloperName();
                if (recordTypeInfoMap.containsKey(devName)) {
                    recTypeId = recordTypeInfoMap.get(devName).getRecordTypeId();
                }
            }
        } catch (Exception e) {
            System.debug( e.getLineNumber() + ' ' + e.getMessage());
        }

        return recTypeId;
    }
}