force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <inlineHelpText>This is used programmatically to execute the batch.</inlineHelpText>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Finished_with_Errors</fullName>
                <label>Finished with Errors</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FW_Async_GenericBatchSchedulerTest.cls
/**
 * @author         Nuno Costa
 * @description    FW_Async_GenericBatchScheduler test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * nuno Costa    	01/09/2023      100            US 00000000 - Original version
 **/
@isTest
private class FW_Async_GenericBatchSchedulerTest {
	static fflib_ApexMocks mocks = new fflib_ApexMocks();

	@isTest
	private static void Async_GenericBatchSchedulerExecuteOkTest() {
		FW_IREP_JobExecution jobExecutionRep = (FW_REP_JobExecution) mocks.mock(FW_REP_JobExecution.class);
		FW_IREP_BatchDefinition batchDefRep = (FW_REP_BatchDefinition) mocks.mock(FW_REP_BatchDefinition.class);
		FW_IDO_JobExecution jobExecutionDO = (FW_DO_JobExecution) mocks.mock(FW_DO_JobExecution.class);

		//Create Batch_Definition
		List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>{
		new Batch_Definition__c(
			Id = fflib_IDGenerator.generate(Batch_Definition__c.sObjectType),
			Batch_Name__c = 'CleanJobExecutions',
			Class_Name__c = 'FW_Async_JobExecutionClean',
			Job_Size__c = 200,
			SObject_API_Name__c = 'Job_Execution__c'
		)
		};

		//Create JobExecution
		List<Job_Execution__c> jobExecutionList = new List<Job_Execution__c>{
			new Job_Execution__c(
				Id = fflib_IDGenerator.generate(Job_Execution__c.sObjectType),
				Batch_Definition__c = batchDefinitionList[0].id,
				Run_With_Defaults__c = true,
				Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_NEW
			)
		};

		mocks.startStubbing();
		mocks.when(batchDefRep.getBatchDefinitionByNameSet((Set<String>) fflib_match.anyObject())).thenReturn(batchDefinitionList);
		mocks.stopStubbing();

		FW_Async_GenericBatchScheduler scheduleJobExec = new FW_Async_GenericBatchScheduler();
		scheduleJobExec = new FW_Async_GenericBatchScheduler(batchDefRep, jobExecutionRep, jobExecutionDO);
		scheduleJobExec.batchDefinitionName = batchDefinitionList[0].Batch_Name__c;
		scheduleJobExec.execute(null);

		((FW_IREP_BatchDefinition) mocks.verify(batchDefRep, 1)).getBatchDefinitionByNameSet((Set<String>) fflib_match.anyObject());
	}

	@isTest
	private static void Async_GenericBatchSchedulerExecuteNOkTest() {
		FW_IREP_JobExecution jobExecutionRep = (FW_REP_JobExecution) mocks.mock(FW_REP_JobExecution.class);
		FW_IREP_BatchDefinition batchDefRep = (FW_REP_BatchDefinition) mocks.mock(FW_REP_BatchDefinition.class);
		FW_IDO_JobExecution jobExecutionDO = (FW_DO_JobExecution) mocks.mock(FW_DO_JobExecution.class);

		//Create Batch_Definition
		List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>();

		mocks.startStubbing();
		mocks.when(batchDefRep.getBatchDefinitionByNameSet((Set<String>) fflib_match.anyObject())).thenReturn(batchDefinitionList);
		mocks.stopStubbing();

		test.startTest();
		FW_Async_GenericBatchScheduler scheduleJobExec = new FW_Async_GenericBatchScheduler(batchDefRep, jobExecutionRep, jobExecutionDO);
		scheduleJobExec.execute(null);
		Test.stopTest();

		((FW_IREP_BatchDefinition) mocks.verify(batchDefRep, 1)).getBatchDefinitionByNameSet((Set<String>) fflib_match.anyObject());
	}
}