force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FW_REP_ParametersTest.cls
@isTest
public class FW_REP_ParametersTest {
    @isTest
    static void paremeterRepositoryTest(){
        User runningUser = FW_TestDataFactory.createUsers(1, true, 'System Administrator', null).get(0);
        system.runAs(runningUser){  
            List<Batch_Definition__c> batchDefinitionList = FW_TestDataFactory.createBatchDefinition(1, true);
            List<Job_Execution__c> jobExecutionList = FW_TestDataFactory.createJobExecution(1, true, FW_DO_JobExecution.JOB_EXEC_RECORD_TYPE_INITIAL, batchDefinitionList.get(0).Id);
            List<Parameters__c> parameterList = FW_TestDataFactory.createParameter(2, false);
            parameterList.get(0).Job_Execution__c = jobExecutionList.get(0).Id;
            parameterList.get(1).Batch_Definition__c = batchDefinitionList.get(0).Id;
            
            test.startTest();
                FW_REP_Parameters parameterRepository = new FW_REP_Parameters();
                parameterRepository.insertSObjects(parameterList);
                List<Parameters__c> parameterListFromJobExecution = parameterRepository.getParametersByParentId(new Set<Id>{jobExecutionList.get(0).Id});
                List<Parameters__c> parameterListFromBatchDefinition = parameterRepository.getParametersByBatchDefinitionId(new Set<Id>{batchDefinitionList.get(0).Id});
            test.stopTest();
            
            system.assertEquals(1, parameterListFromJobExecution.size());
            system.assertEquals(2, parameterListFromBatchDefinition.size());
        }
    } 
}