force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <inlineHelpText>This is used programmatically to execute the batch.</inlineHelpText>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/recordTypes/COMM_ContactUs.recordType-meta.xml
<RecordType>
    <fullName>COMM_ContactUs</fullName>
    <active>true</active>
    <businessProcess>Contact Us</businessProcess>
    <description>Case to submit a a request for information</description>
    <label>Contact Us</label>
</RecordType>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Finished_with_Errors</fullName>
                <label>Finished with Errors</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Defines the value of the parameter, can be a set of Ids, a status value, a constant etc</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/COMM_Async_CleanupCaseRecordsTest.cls
/**
 * @author Carlos Fusco
 * @description COMM_Async_CleanupCaseRecords test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer             Date            Coverage(%)         Description
 * ------------------------------------------------------------------------------------
 * Carlos Fusco        26/04/2024           100             Original version
 **/
@isTest
private class COMM_Async_CleanupCaseRecordsTest {
    private final static fflib_ApexMocks MOCKS = new fflib_ApexMocks();
    private final static FW_IREP_JobExecution JOB_EXECUTION_REP = (FW_REP_JobExecution) MOCKS.mock(FW_REP_JobExecution.class);
    private final static FW_ISObjectRep SOBJECT_REP = (FW_SObjectRep) MOCKS.mock(FW_SObjectRep.class);
    private final static FW_IREP_Parameters PARAMETERS_REP = (FW_REP_Parameters) MOCKS.mock(FW_REP_Parameters.class);

    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
    @isTest
    private static void deleteCaseRecordsBatchExecuteTest() {
        List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>{
            new Batch_Definition__c(
                Id = fflib_IDGenerator.generate(Batch_Definition__c.sObjectType),
                Batch_Name__c = 'AsyncCleanupCompletedCaseContactUsRecords',
                Class_Name__c = 'COMM_Async_CleanupCaseRecords',
                Job_Size__c = 200,
                SObject_API_Name__c = 'Case'
            )
        };

        List<SObject> caseList = new List<SObject>{ new Case() };

        List<Job_Execution__c> jobExecutionList = new List<Job_Execution__c>{
            new Job_Execution__c(
                Id = fflib_IDGenerator.generate(Job_Execution__c.sObjectType),
                Batch_Definition__c = batchDefinitionList[0].id,
                Run_With_Defaults__c = true,
                Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_NEW
            )
        };

        List<Parameters__c> parametersList = new List<Parameters__c>{
            new Parameters__c(Id = fflib_IDGenerator.generate(Parameters__c.sObjectType), Name = FW_AsyncHandler.DEFAULT_PARAMETER),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = COMM_Async_CleanupCaseRecords.PARAMETER_DATEFIELD,
                Value__c = 'CreatedDate'
            ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = COMM_Async_CleanupCaseRecords.PARAMETER_OPERATOR,
                Value__c = '<='
            ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = COMM_Async_CleanupCaseRecords.PARAMETER_MONTHS_AGO,
                Value__c = '12'
            ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = COMM_Async_CleanupCaseRecords.PARAMETER_RECORD_TYPE,
                Value__c = 'COMM_ContactUs'
            ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = COMM_Async_CleanupCaseRecords.PARAMETER_STATUS,
                Value__c = 'Process Concluded'
            ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = COMM_Async_CleanupCaseRecords.PARAMETER_ORIGIN,
                Value__c = 'Web'
            )
        };

        MOCKS.startStubbing();
        MOCKS.when(SOBJECT_REP.deleteSObjects((List<SObject>) fflib_Match.anyList())).thenReturn(new List<Database.DeleteResult>());
        MOCKS.when(JOB_EXECUTION_REP.getJobExecWithBatchDefinitionsByIdSet((Set<Id>) fflib_match.anyObject())).thenReturn(jobExecutionList);
        MOCKS.when(JOB_EXECUTION_REP.getJobExecutionByAsyncApexJobIdSet((Id) fflib_match.anyObject())).thenReturn(jobExecutionList);
        MOCKS.when(PARAMETERS_REP.getParametersByParentId((Set<Id>) fflib_match.anyObject())).thenReturn(parametersList);
        MOCKS.stopStubbing();

        Boolean errorOccured = false;
        try {
            COMM_Async_CleanupCaseRecords newBatchRun = new COMM_Async_CleanupCaseRecords();
            newBatchRun = new COMM_Async_CleanupCaseRecords(SOBJECT_REP, JOB_EXECUTION_REP, PARAMETERS_REP);

            Database.executeBatch(newBatchRun);
            newBatchRun.setAsyncApexJobId(null);
            newBatchRun.execute(null, caseList);
        } catch (Exception e) {
            errorOccured = true;
        }

        ((FW_IREP_JobExecution) mocks.verify(JOB_EXECUTION_REP, 1)).getJobExecWithBatchDefinitionsByIdSet((Set<Id>) fflib_match.anyObject());
        ((FW_ISObjectRep) mocks.verify(SOBJECT_REP, 1)).deleteSObjects(caseList);
        Assert.isFalse(errorOccured, 'expected no errors to occur');
    }
}