force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FW_TW_BatchDefinition_DefaultParamTest.cls
@isTest
private class FW_TW_BatchDefinition_DefaultParamTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();
    
    @isTest
    private static void jobExecutionDefaultParamTest(){
        FW_IREP_Parameters parametersRepository = (FW_REP_Parameters)mocks.mock(FW_REP_Parameters.class);
        
        List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>();
        batchDefinitionList.add(
            new Batch_Definition__c(
                Id = fflib_IDGenerator.generate(Batch_Definition__c.sObjectType)
            )  
        );

        List<Parameters__c> parameterList = new List<Parameters__c>();
        parameterList.add(
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Batch_Definition__c = batchDefinitionList.get(0).Id
            ) 
        );

        mocks.startStubbing();
            mocks.when(parametersRepository.insertSObjects(parameterList)).thenReturn(new List<Database.SaveResult>());
        mocks.stopStubbing();
       
        FW_TW_BatchDefinition_DefaultParam jobExecutionWorker = new FW_TW_BatchDefinition_DefaultParam();
        jobExecutionWorker = new FW_TW_BatchDefinition_DefaultParam(parametersRepository);
        
        jobExecutionWorker.execute(batchDefinitionList);
        
        ((FW_IREP_Parameters)mocks.verify(parametersRepository, 1)).insertSObjects((List<Parameters__c>)fflib_match.anyList());
    }
}