force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Finish__c.field-meta.xml
<CustomField>
    <fullName>Batch_Finish__c</fullName>
    <description>date/time that the batch finished</description>
    <label>Batch Finish</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Start__c.field-meta.xml
<CustomField>
    <fullName>Batch_Start__c</fullName>
    <description>date/time that the batch started</description>
    <label>Batch Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Finished_with_Errors</fullName>
                <label>Finished with Errors</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Defines the value of the parameter, can be a set of Ids, a status value, a constant etc</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/FW_AsyncHandler.cls
/**
 * @description   Handler class for batch framework
 * @testClass     FW_AsyncHandlerTest
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer                       Date                Description
 * ------------------------------------------------------------------------------------
 */
public virtual without sharing class FW_AsyncHandler implements Database.RaisesPlatformEvents, FW_IAsync {
    public final static String DEFAULT_PARAMETER = 'IdList';

    private Job_Execution__c jobExecution;
    private Id asyncApexJobId;
    private Id jobExecutionId;
    private Map<String, Parameters__c> parametersMap;
    protected FW_IREP_JobExecution jobExecutionRep;
    protected FW_IREP_Parameters parameterRep;
    protected FW_IREP_AsyncApexJob asyncApexJobRep;

    /**
     * @description Class Constructor to initialize REP classes
     */
    public FW_AsyncHandler() {
        jobExecutionRep = new FW_REP_JobExecution();
        parameterRep = new FW_REP_Parameters();
        asyncApexJobRep = new FW_REP_AsyncApexJob();
    }

    @testVisible
    private FW_AsyncHandler(FW_IREP_JobExecution jobExecutionRep, FW_IREP_Parameters parameterRep, FW_IREP_AsyncApexJob asyncApexJobRep) {
        this.jobExecutionRep = jobExecutionRep;
        this.parameterRep = parameterRep;
        this.asyncApexJobRep = asyncApexJobRep;
    }

    /**
     * @description Method to set the Id of the Job Execution Record associated with the executed Batch
     * @param jobExecutionId Id of the Job Execution Record
     */
    public void setJobExecutionId(Id jobExecutionId) {
        this.jobExecutionId = jobExecutionId;
    }

    /**
     * @description Get the job Id and the parameters and start the batch
     * @param asyncApexJobId Id of the Async Apex Job that represents the batch
     */
    public void setAsyncApexJobId(Id asyncApexJobId) {
        this.asyncApexJobId = asyncApexJobId;
        Set<Id> parentIdSet = new Set<Id>();
        list<Job_Execution__c> jobExecutionList = jobExecutionRep.getJobExecWithBatchDefinitionsByIdSet(new Set<id>{ this.jobExecutionId });
        this.jobExecution = jobExecutionList.get(0);

        if (this.jobExecution.Run_With_Defaults__c) {
            parentIdSet.add(this.jobExecution.Batch_Definition__c);
        } else {
            parentIdSet.add(this.jobExecution.id);
        }

        parametersMap = new Map<String, Parameters__c>();
        if (!parentIdSet.isEmpty()) {
            for (Parameters__c parameter : parameterRep.getParametersByParentId(parentIdSet)) {
                parametersMap.put(parameter.name, parameter);
            }
        }
        startBatch();
    }

    /**
     * @description Get the parameter value
     * @param parameterName Name of the Batch Parameter to retrieve
     * @return Value of the Batch Parameter
     */
    public String getParameterValue(String parameterName) {
        if (parametersMap.containsKey(parameterName)) {
            return parametersMap.get(parameterName).Value__c;
        }
        throw new FW_TriggerException(Label.Batch_Framework_Missing_Parameters_Exception);
    }

    /**
     * @description Method to initialize batch
     */
    public void startBatch() {
        jobExecution.Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_STARTED;
        jobExecution.Batch_Start__c = System.now();
        jobExecution.AsyncApexJobId__c = AsyncApexJobId;
        jobExecutionRep.updateSObjects(new List<Job_Execution__c>{ jobExecution });
    }

    /**
     * @description Method to execute post batch finish logic
     * @param asyncApexJobId Id of the Async Apex Job that finished
     */
    public void finishBatch(Id asyncApexJobId) {
        jobExecution = jobExecutionRep.getJobExecutionByAsyncApexJobIdSet(asyncApexJobId).get(0);
        if (jobExecution.Batch_Finish__c == null) {
            AsyncApexJob job = asyncApexJobRep.getAsyncApexJobListByIdSet(new Set<Id>{ asyncApexJobId }).get(0);
            if (String.isEmpty(job.ExtendedStatus)) {
                jobExecution.Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_FINISHED;
            } else {
                jobExecution.Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_FINISHED_ERRORS;
            }
            jobExecution.Batch_Finish__c = System.now();

            jobExecutionRep.updateSObjects(new List<Job_Execution__c>{ jobExecution });
        }
    }

    /**
     * @description Method to query the system
     * @param query Query Builder instance with the query to be executed
     * @return QueryLocator object with the executed query
     */
    public Database.QueryLocator executeQuery(FW_QueryBuilder query) {
        if (!String.isEmpty(getParameterValue(DEFAULT_PARAMETER))) {
            query.whereIn('Id', (list<Object>) getParameterValue(DEFAULT_PARAMETER).split(','));
        }

        String countQuery = query.getCountQuery();
        Integer numberOfRecords = Database.countQuery(countQuery);

        if (numberOfRecords != null) {
            jobExecution.Queried_Records__c = numberOfRecords;
            jobExecutionRep.updateSObjects(new List<Job_Execution__c>{ jobExecution });
        }

        return Database.getQueryLocator(query.getQuery());
    }
}