force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <inlineHelpText>This is used programmatically to execute the batch.</inlineHelpText>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_MigrationCreateExternalUser__c.field-meta.xml
<CustomField>
    <fullName>COMM_MigrationCreateExternalUser__c</fullName>
    <description>To be used on External User migration</description>
    <label>Migration Create External User</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PROCESSED</fullName>
            </value>
            <value>
                <fullName>TO PROCESS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Finished_with_Errors</fullName>
                <label>Finished with Errors</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/COMM_LoginType__c.field-meta.xml
<CustomField>
    <fullName>COMM_LoginType__c</fullName>
    <description>Used to identify the type of Login the User uses when logging in from the Community Site</description>
    <label>Login Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Azure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/COMM_Async_UserCreationTest.cls
/**
 * @author         Miguel Freire
 * @description    COMM_Async_UserCreation test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Miguel Freire    24/01/2024      100         Original version
 **/
@isTest
private class COMM_Async_UserCreationTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();
    private final static FW_IREP_JobExecution jobExecutionRep = (FW_REP_JobExecution) mocks.mock(FW_REP_JobExecution.class);
    private final static FW_IREP_Parameters parameterRep = (FW_REP_Parameters) mocks.mock(FW_REP_Parameters.class);
    private final static FW_IAsync asynHandler = (FW_AsyncHandler) mocks.mock(FW_AsyncHandler.class);
    private final static COMM_REP_Contact CONTACT_REP = (COMM_REP_Contact) MOCKS.mock(COMM_REP_Contact.class);
    private final static COMM_REP_User USER_REP = (COMM_REP_User) MOCKS.mock(COMM_REP_User.class);
    private final static COMM_DO_User USER_DO = (COMM_DO_User) MOCKS.mock(COMM_DO_User.class);

    @isTest
    private static void COMM_Async_UserCreationTest() {
        // Initialize framework
        //Create Batch_Definition
        List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>{
            new Batch_Definition__c(
                Id = fflib_IDGenerator.generate(Batch_Definition__c.sObjectType),
                Batch_Name__c = 'COMM_Async_UserCreation',
                Class_Name__c = 'COMM_Async_UserCreation',
                Job_Size__c = 200,
                SObject_API_Name__c = 'Contact'
            )
        };

        //Create Parameters
        List<Parameters__c> parametersList = new List<Parameters__c>{
            new Parameters__c(Id = fflib_IDGenerator.generate(Parameters__c.sObjectType), Name = FW_AsyncHandler.DEFAULT_PARAMETER)
        };

        //Create JobExecution
        List<Job_Execution__c> jobExecutionList = new List<Job_Execution__c>{
            new Job_Execution__c(
                Id = fflib_IDGenerator.generate(Job_Execution__c.sObjectType),
                Batch_Definition__c = batchDefinitionList.get(0).id,
                Run_With_Defaults__c = true,
                Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_NEW
            )
        };

        List<Job_Execution__c> jobExecutionList2 = new List<Job_Execution__c>{
            new Job_Execution__c(
                Id = fflib_IDGenerator.generate(Job_Execution__c.sObjectType),
                Batch_Definition__c = batchDefinitionList.get(0).id,
                Run_With_Defaults__c = true,
                Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_SCHEDULED
            )
        };

        mocks.startStubbing();
        mocks.when(jobExecutionRep.getJobExecWithBatchDefinitionsByIdSet((Set<Id>) fflib_match.anyObject())).thenReturn(jobExecutionList);
        mocks.when(jobExecutionRep.getJobExecutionByAsyncApexJobIdSet((Id) fflib_match.anyObject())).thenReturn(jobExecutionList);
        mocks.when(parameterRep.getParametersByParentId((Set<Id>) fflib_match.anyObject())).thenReturn(parametersList);
        mocks.when(
                USER_DO.instantiateUser(
                    (String) fflib_match.anyObject(),
                    (String) fflib_match.anyObject(),
                    (String) fflib_match.anyObject(),
                    (String) fflib_match.anyObject()
                )
            )
            .thenReturn(new User());
        mocks.stopStubbing();

        COMM_Async_UserCreation newBatchRun = new COMM_Async_UserCreation();
        newBatchRun = new COMM_Async_UserCreation(CONTACT_REP, USER_REP, USER_DO, jobExecutionRep, parameterRep);

        Database.executeBatch(newBatchRun);
        newBatchRun.setAsyncApexJobId(null);

        ((FW_IREP_JobExecution) mocks.verify(jobExecutionRep, 1)).getJobExecWithBatchDefinitionsByIdSet((Set<Id>) fflib_match.anyObject());
        ((FW_IREP_Parameters) mocks.verify(parameterRep, 1)).getParametersByParentId((Set<Id>) fflib_match.anyObject());
    }
    @isTest
    private static void COMM_Async_UserCreationExecuteTest() {
        //Scenario: The Batch tries to Create a User for each Contact that has de field COMM_MigrationCreateExternalUser = true
        //Expected: Creates Users for correct Contacts

        //Mock Person Contact.
        Contact mockedContact = (Contact) fflib_ApexMocksUtils.setReadOnlyFields(
            new Contact(),
            Contact.class,
            new Map<SObjectField, Object>{
                Contact.Id => fflib_IDGenerator.generate(Contact.SObjectType),
                Contact.Email => 'test@test.com',
                Contact.LastName => 'User',
                Contact.FirstName => 'Portal',
                Contact.COMM_MigrationCreateExternalUser__c => 'TO PROCESS'
            }
        );

        //Mock expected User Record
        User userRecord = (User) COMM_TestDataFactory.insertRecords(
            1,
            false,
            'User',
            new Map<String, Object>{
                'Id' => fflib_IDGenerator.generate(User.SObjectType),
                'Username' => 'testuser@ana.pt.test',
                'Email' => mockedContact.Email,
                'LastName' => mockedContact.LastName,
                'FirstName' => mockedContact.FirstName,
                'COMM_LoginType__c' => COMM_DO_User.NORMAL_LOGIN_IDENTIFIER,
                'CommunityNickname' => 'portaluser',
                'Alias' => 'portalUs',
                'LanguageLocaleKey' => UserInfo.getLanguage(),
                'LocaleSidKey' => UserInfo.getLocale(),
                'EmailEncodingKey' => COMM_DO_User.EMAIL_ENCODINGKEY_PICKLIST_UTF8,
                'TimeZoneSidKey' => COMM_DO_User.TIME_ZONE_PICKLIST_PTLS,
                'ProfileId' => fflib_IDGenerator.generate(Profile.SObjectType),
                'ContactId' => mockedContact.Id
            }
        )[0];

        //Mock Queries
        MOCKS.startStubbing();
        MOCKS.when(
                USER_DO.instantiateUser(
                    (String) fflib_match.anyObject(),
                    (String) fflib_match.anyObject(),
                    (String) fflib_match.anyObject(),
                    (String) fflib_match.anyObject()
                )
            )
            .thenReturn(userRecord);
        MOCKS.stopStubbing();

        //Start Test
        Test.startTest();
        Boolean errorOccured = false;
        try {
            COMM_Async_UserCreation newBatchRun = new COMM_Async_UserCreation();
            newBatchRun = new COMM_Async_UserCreation(CONTACT_REP, USER_REP, USER_DO, jobExecutionRep, parameterRep);
            newBatchRun.execute(null, new List<Contact>{ mockedContact });
        } catch (Exception e) {
            errorOccured = true;
        }
        Test.stopTest();
        Assert.isFalse(errorOccured, 'Users created successfully');
    }
}