force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Finished_with_Errors</fullName>
                <label>Finished with Errors</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FW_TW_JobExecution_ManageBatchAfter.cls
/**  
	* @description  Worker class to manage Job executions validations
	* @testClass    FW_TW_JobExecution_ManageBatchAfterTest
	* Modification Log 
	* ------------------------------------------------------------------------------------  
	* Developer                       Date                Description  
    * ------------------------------------------------------------------------------------  
**/
public with sharing class FW_TW_JobExecution_ManageBatchAfter {

    private FW_IREP_BatchDefinition batchDefinitionRepository;
    private FW_IDO_JobExecution jobExecutionDO;
    private FW_IREP_JobExecution jobExecutionRepository;

    public FW_TW_JobExecution_ManageBatchAfter() {
        this.batchDefinitionRepository = new FW_REP_BatchDefinition();
        this.jobExecutionDO = new FW_DO_JobExecution();
        this.jobExecutionRepository = new FW_REP_JobExecution();
    }
    
    @TestVisible
    private FW_TW_JobExecution_ManageBatchAfter(FW_IDO_JobExecution jobExecutionDO, FW_IREP_BatchDefinition batchDefinitionRepository, FW_IREP_JobExecution jobExecutionRepository) {
        this.batchDefinitionRepository = batchDefinitionRepository;
        this.jobExecutionDO = jobExecutionDO;
        this.jobExecutionRepository = jobExecutionRepository;
    }
    
    public void execute(List<Job_Execution__c> jobExecutionList) {
        
        Set<Id> batchDefinitionIdSet = getBatchDefinitionIdSet(jobExecutionList);
        Map<Id, Batch_Definition__c> batchDefinitionMap = new Map<Id, Batch_Definition__c>(batchDefinitionRepository.getBatchDefinitionByIdSet(batchDefinitionIdSet));

        List<Job_Execution__c> jobExecutionsToUpdateList = new List<Job_Execution__c>();
        for(Job_Execution__c jobExecution: jobExecutionList) {

            if(jobExecutionDO.isScheduledRun(jobExecution)){
                jobExecutionsToUpdateList.add(
                    new Job_Execution__c(
                        Id = jobExecution.Id,
                        RecordTypeId = Schema.SObjectType.Job_Execution__c.getRecordTypeInfosByDeveloperName().get(FW_DO_JobExecution.JOB_EXEC_RECORD_TYPE_DEFINED).getRecordTypeId(),
                        AsyncApexJobId__c = jobExecutionDO.executeBatch(jobExecution, batchDefinitionMap.get(jobExecution.Batch_Definition__c)),
                        Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_SCHEDULED
                    )
                );
                
            }
        }
        jobExecutionRepository.updateSObjects(jobExecutionsToUpdateList);
    }

    /**
        * @description:         Returns a set of Batch Definition Id for a given list of Job Executions
    */
    private Set<Id> getBatchDefinitionIdSet(List<Job_Execution__c> jobExecutions) {
        Set<Id> batchDefinitionIdSet = new Set<Id>();

        for(Job_Execution__c jobExecution: jobExecutions) {
            batchDefinitionIdSet.add(jobExecution.Batch_Definition__c);
        }
        return batchDefinitionIdSet;
    }
}