force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FW_TW_JobExecution_CloneParameters.cls
/**
    @description    worker class to copy default parameter to the job execution record
    @testClass      FW_TW_JobExecution_CloneParametersTest
    * Modification Log 
	* ------------------------------------------------------------------------------------  
	* Developer                       Date                Description  
    * ------------------------------------------------------------------------------------        
*/

public without sharing class FW_TW_JobExecution_CloneParameters {

    private FW_IREP_Parameters parametersRepository;
    private FW_IDO_JobExecution jobExecutionDomain;
    
    public FW_TW_JobExecution_CloneParameters(){
        this.parametersRepository = new FW_REP_Parameters();
        this.jobExecutionDomain = new FW_DO_JobExecution();
    }
    
    @TestVisible
    private FW_TW_JobExecution_CloneParameters(FW_IREP_Parameters parametersRepository, FW_IDO_JobExecution jobExecutionDomain){
        this.parametersRepository = parametersRepository;
        this.jobExecutionDomain = jobExecutionDomain;
    }

    public void execute(List<Job_Execution__c> jobExecutionList) {
        
        Map<Id, List<Job_Execution__c>> jobExecutionIdByBatchDefinitionIdMap = new Map<Id, List<Job_Execution__c>>();
        for(Job_Execution__c je : jobExecutionList){
            if(!jobExecutionDomain.isRunningwithDefaults(je) && !isChildJob(je)){
                if(jobExecutionIdByBatchDefinitionIdMap.get(je.Batch_Definition__c) == null){
                    jobExecutionIdByBatchDefinitionIdMap.put(je.Batch_Definition__c, new List<Job_Execution__c>{je});
                }else{
                    jobExecutionIdByBatchDefinitionIdMap.get(je.Batch_Definition__c).add(je);
                }
            } 
        }
        
        if(!jobExecutionIdByBatchDefinitionIdMap.keyset().isEmpty()){
            List<Parameters__c> parameters = parametersRepository.getParametersByBatchDefinitionId(jobExecutionIdByBatchDefinitionIdMap.keyset());
            
            List<Parameters__c> newParameters = new List<Parameters__c>();
            for(Parameters__c parameter : parameters){
                for(Job_Execution__c jobExecution : jobExecutionIdByBatchDefinitionIdMap.get(parameter.Batch_Definition__c)){
                    if(jobExecution.Job_Execution__c == null || jobExecution.Job_Execution__c == ''){
                        newParameters.add(jobExecutionDomain.getClonedParameter(parameter, jobExecution.Id));
                    }
                }
            }
            parametersRepository.insertSObjects(newParameters);  
        }
        
    }

    /**
        * @description:         Validates if Job Execution is null
    */
    private boolean isChildJob(Job_Execution__c je){
        return je.Job_Execution__c != null;
    }
}