force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of what the batch does</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the attribute, should have the options that the parameter can have.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/FW_TW_BatchDefinition_DefaultParam.cls
/**
    * @description   Worker class to create default parameters on batch definitions
    * @testClass     FW_TW_BatchDefinition_DefaultParamTest
    * Modification Log 
	* ------------------------------------------------------------------------------------  
	* Developer                       Date                Description  
    * ------------------------------------------------------------------------------------  
**/
public without sharing class FW_TW_BatchDefinition_DefaultParam  {
    
    private FW_IREP_Parameters parameterRepository;
    
    public FW_TW_BatchDefinition_DefaultParam(){
        this.parameterRepository = new FW_REP_Parameters();
    }
    
    @TestVisible
    private FW_TW_BatchDefinition_DefaultParam(FW_IREP_Parameters parameterRepository){
        this.parameterRepository = parameterRepository;
    }

    public void execute(list<Batch_Definition__c> newBDList) {
        List<Parameters__c> defaultParametersList = new List<Parameters__c>();

        for(Batch_Definition__c batchDefinition: newBDList) {
            defaultParametersList.add(
                new Parameters__c(
                    Name=FW_AsyncHandler.DEFAULT_PARAMETER, 
                    Description__c=Label.Job_Execution_Default_Parameter_Comment,
                    Batch_Definition__c=batchDefinition.Id
                )
            );
        }

        if(!defaultParametersList.isEmpty()){
            parameterRepository.insertSObjects(defaultParametersList);
        }
    }
}