force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <inlineHelpText>This is used programmatically to execute the batch.</inlineHelpText>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/BatchSchedulerClass__c.field-meta.xml
<CustomField>
    <fullName>BatchSchedulerClass__c</fullName>
    <description>The name of the class that&apos;s used to schedule the job</description>
    <inlineHelpText>The name of the class that&apos;s used to schedule the job</inlineHelpText>
    <label>Batch Scheduler Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/CronExpression__c.field-meta.xml
<CustomField>
    <fullName>CronExpression__c</fullName>
    <description>Cron Expression used to run the batch with a custom schedule</description>
    <label>Cron Expression</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FW_SL_ScheduleBatch.cls
/**
 * @author           Nuno Costa
 * @description      Class that allows to schedule a batch from a flow
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Description
 * -----------------------------------------------------------------------------------
 * Nuno Costa      	01/09/2023      US 00000000 - Original version
 **/
public with sharing class FW_SL_ScheduleBatch {

	@InvocableMethod(
		label='Schedule Batch'
		description='Schedule Batch'
		category='Custom Actions'
	)
	public static List<String> scheduleBatch(List<Batch_Definition__c> batchDefinition){

        List<String> jobIdList = new List<String>();
		for(Batch_Definition__c batchDefinitionRecord: batchDefinition){

			if(batchDefinitionRecord.BatchSchedulerClass__c == FW_Async_GenericBatchScheduler.class.getName()){
				FW_Async_GenericBatchScheduler genericScheduler = new FW_Async_GenericBatchScheduler();
				genericScheduler.batchDefinitionName = batchDefinitionRecord.Batch_Name__c;

				String jobID = !Test.isRunningTest() ? System.schedule(batchDefinitionRecord.Name, batchDefinitionRecord.CronExpression__c, genericScheduler) : 'Test Id';
				jobIdList.add(jobID);
			} else {
				Type classType = Type.forName(batchDefinitionRecord.BatchSchedulerClass__c);
				Schedulable classInstance = (Schedulable) classType.newInstance();
				//Due to the nature of this class, it's difficult to test the scheduling, since job ids are only returned after the test runs. 
				//Therefore, if it's a test we return a mock Id.CronExpression__c
				String jobID = !Test.isRunningTest() ? System.schedule(batchDefinitionRecord.Name, batchDefinitionRecord.CronExpression__c, classInstance) : 'Test Id';
				jobIdList.add(jobID);
			}
			
		}

        return jobIdList;
    }
}