force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of what the batch does</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>To capture all sort of errors</description>
    <label>Error and Log</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors and Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Job Execution record, it is filled if the error comes from the Batch Framework</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipName>Error_and_Monitoring_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Job_Scope__c.field-meta.xml
<CustomField>
    <fullName>Job_Scope__c</fullName>
    <description>The Record IDs that are in scope if the event was fired from the execute() method of a batch job. If the batch job uses custom iterators instead of sObjects, JobScope is the toString() representation of the iterable objects. Maximum length is 40000 characters.</description>
    <label>Job Scope</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the attribute, should have the options that the parameter can have.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Defines the value of the parameter, can be a set of Ids, a status value, a constant etc</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/FW_LCC_JobExecutionRetry.cls
/**
    * @description   Lightning component controller for Job Execution component
    * @testClass     FW_LCC_JobExecutionRetryTest
    * Modification Log 
	* ------------------------------------------------------------------------------------  
	* Developer                       Date                Description  
    * ------------------------------------------------------------------------------------ 
*/
public without sharing class FW_LCC_JobExecutionRetry {
    private static FW_REP_ErrorLog errorLogRepository = new FW_REP_ErrorLog();
    private static FW_REP_JobExecution jobExecutionRepository = new FW_REP_JobExecution();
    private static FW_REP_Parameters parameterRepository = new FW_REP_Parameters();
    private static FW_DO_JobExecution jobExecutionDomain = new FW_DO_JobExecution();
    
    /**
        *  @description:    Method to retrieve errors related to a job execution
    */
    @AuraEnabled
    public static List<Error_Log__c> getErrorList(Id jobExecutionId){
        return errorLogRepository.getErrorLogListByJobExecutionIdSet(new Set<Id>{jobExecutionId});
    }
    
    /**
        *  @description:    Create job Execution from an error log
    */
    @AuraEnabled
    public static void createJobExecutions(List<Id> errorListId){

        List<Error_Log__c> errorList = errorLogRepository.getErrorLogListByIdSet(new Set<Id>(errorListId));
        
        Id initialJobRTId = Schema.SObjectType.Job_Execution__c.getRecordTypeInfosByDeveloperName().get(FW_DO_JobExecution.JOB_EXEC_RECORD_TYPE_INITIAL).getRecordTypeId();
        Map<Id, Job_Execution__c> jobExecutionByErrorIdMap = new Map<Id, Job_Execution__c>();
        for(Error_Log__c error : errorList){
            Integer jobSize = 200;
            if(!String.isEmpty(error.Job_Scope__c)){
                jobSize = error.Job_Scope__c.split(',').size();
            }
            
            Job_Execution__c newJob = new Job_Execution__c(Job_Execution__c = error.Job_Execution__c,
                                                                   Batch_Definition__c = error.Job_Execution__r.Batch_Definition__c,
                                                                   RecordTypeId = initialJobRTId,
                                                                   Run_with_Defaults__c = false,
                                                                   Job_Size__c = jobSize
                                                                   ); 
            jobExecutionByErrorIdMap.put(error.id, newJob);    
        }
        
        //jobExecutionRepository.insertSObjects(jobExecutionByErrorIdMap.values());
        insert jobExecutionByErrorIdMap.values();
        List<Parameters__c> parentParameterList;
        if(errorList.get(0).Job_Execution__r.Run_with_Defaults__c){
            parentParameterList = parameterRepository.getParametersByParentId(new Set<Id>{errorList.get(0).Job_Execution__r.Batch_Definition__c}); 
        }else{
            parentParameterList = parameterRepository.getParametersByParentId(new Set<Id>{errorList.get(0).Job_Execution__c});
        }
        
        List<Parameters__c> parameterList = new List<Parameters__c>();
        for(Error_Log__c error : errorList){
            parameterList.add(new Parameters__c(Description__c = Label.Job_Execution_Default_Parameter_Comment,
                                                    Job_Execution__c = jobExecutionByErrorIdMap.get(error.Id).Id,
                                                    Value__c = error.Job_Scope__c,
                                                    Name = FW_AsyncHandler.DEFAULT_PARAMETER));
            
            for(Parameters__c parameter : parentParameterList){
                if(parameter.Name != FW_AsyncHandler.DEFAULT_PARAMETER){
                    parameterList.add(jobExecutionDomain.getClonedParameter(parameter, jobExecutionByErrorIdMap.get(error.Id).Id));
                }
            }
                                                    
        }
        parameterRepository.insertSObjects(parameterList);
        errorLogRepository.updateSObjects(errorList);
    }
}