force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FW_IDO_JobExecution.cls
/**
    * @description   Interface for the Job Execution Domain Object Class
**/
public interface FW_IDO_JobExecution {

    Boolean isRunningwithDefaults(Job_Execution__c jobExecution);
    Boolean isJobSizeEqualsToBatchDefinitionJobSize(Job_Execution__c jobExecution, Batch_Definition__c batchDefinition);
    Id executeBatch(Job_Execution__c jobExecution, Batch_Definition__c batchDefinition);
    Integer getDifferenceInMinutesFromNow(DateTime dt1);
    Parameters__c getClonedParameter(Parameters__c parameter, Id jobExecutionId);
    Boolean isToExecute(Job_Execution__c jobExecution);
    Boolean isScheduledRun(Job_Execution__c jobExecution);
    Id scheduleBatch(Job_Execution__c jobExecution, Batch_Definition__c batchDefinition);
    Job_Execution__c createJobExecutionsFromBD(Id batchDefinitionID);
    void abortJob(String asyncId);
}