force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <inlineHelpText>This is used programmatically to execute the batch.</inlineHelpText>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/BatchSchedulerClass__c.field-meta.xml
<CustomField>
    <fullName>BatchSchedulerClass__c</fullName>
    <description>The name of the class that&apos;s used to schedule the job</description>
    <inlineHelpText>The name of the class that&apos;s used to schedule the job</inlineHelpText>
    <label>Batch Scheduler Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/CronExpression__c.field-meta.xml
<CustomField>
    <fullName>CronExpression__c</fullName>
    <description>Cron Expression used to run the batch with a custom schedule</description>
    <label>Cron Expression</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FW_SL_ScheduleBatchTest.cls
/**
 * @author           Nuno Costa
 * @description      FW_SL_ScheduleBatch test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Nuno Costa      	01/09/2023      100            US 00000000 - Original version
 **/
@isTest
private class FW_SL_ScheduleBatchTest {
	@isTest
	static void scheduleBatchTest() {
		//scenario: This test is mostly for coverage. We do not want to schedule batches from tests 
		//and Job IDs are only returned after the test runs
		Batch_Definition__c batchDefinition = new Batch_Definition__c();
		batchDefinition.Batch_Name__c = 'CleanJobExecutions';
		batchDefinition.Class_Name__c = 'FW_Async_JobExecutionClean'; //Class that implements "Schedulable" framework
		batchDefinition.CronExpression__c = '0 0 12 ? * * *';
		batchDefinition.BatchSchedulerClass__c = 'FW_Async_JobExecutionCleanSchedule';

		Boolean error = false;
		String errorMessage = '';
		List<String> resultList = new List<String>();
		Test.startTest();
		try{
			resultList = FW_SL_ScheduleBatch.scheduleBatch(new List<Batch_Definition__c> {batchDefinition});
		} catch(exception ex) {
			error = true;
			errorMessage = ex.getMessage();
		}
		Test.stopTest();

		Assert.isFalse(error, 'An error was found: ' + errorMessage);
		Assert.isTrue(!resultList.isEmpty(), 'No id was returned');
	}

	@isTest
	static void scheduleGenericBatchTest() {
		//scenario: This test is mostly for coverage. We do not want to schedule batches from tests 
		//and Job IDs are only returned after the test runs
		Batch_Definition__c batchDefinition = new Batch_Definition__c();
		batchDefinition.Batch_Name__c = 'CleanJobExecutions';
		batchDefinition.Class_Name__c = 'FW_Async_JobExecutionClean'; //Class that implements "Schedulable" framework
		batchDefinition.CronExpression__c = '0 0 12 ? * * *';
		batchDefinition.BatchSchedulerClass__c = 'FW_Async_GenericBatchScheduler';

		Boolean error = false;
		String errorMessage = '';
		List<String> resultList = new List<String>();
		Test.startTest();
		try{
			resultList = FW_SL_ScheduleBatch.scheduleBatch(new List<Batch_Definition__c> {batchDefinition});
		} catch(exception ex) {
			error = true;
			errorMessage = ex.getMessage();
		}
		Test.stopTest();

		Assert.isFalse(error, 'An error was found: ' + errorMessage);
		Assert.isTrue(!resultList.isEmpty(), 'No id was returned');
	}
}