force-app/main/default/objects/Case/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <label>Airport</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_AirportTextList__c.field-meta.xml
<CustomField>
    <fullName>COMM_AirportTextList__c</fullName>
    <description>Field used on Sharing Rules. Due multi-picklist limitation.</description>
    <label>Airport Text List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_TW_Case_AirportUpdate.cls
/**
 * @author Daniel Lascas
 * @description Trigger worker that verifies if the multi-picklist COMM_Airport__c
 * was changed. If it was copy value to COMM_AirportTextList__c to update sharing.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    11/07/2024		ECOMM-1602: CR-33
 **/
public with sharing class COMM_TW_Case_AirportUpdate {
    /**
     * @description Execute Trigger Worker Logic.
     *
     * @param newCaseList List with the Case Records in after context.
     * @param oldCaseMap Map with the Case Records in before context.
     */
    public void execute(List<Case> newCaseList, Map<Id, Case> oldCaseMap) {
        for (Case newCase : newCaseList) {
            //Verify Airport Field Changed
            if (COMM_GEN_Utility.isChangedField(newCase, oldCaseMap, Case.COMM_Airport__c)) {
                newCase.COMM_AirportTextList__c = newCase.COMM_Airport__c;
            }
        }
    }
}