force-app/main/default/objects/Case/fields/COMM_Card__c.field-meta.xml
<CustomField>
    <fullName>COMM_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_FirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstName__c</fullName>
    <label>Case First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_InitialSubscriptionMonth__c.field-meta.xml
<CustomField>
    <fullName>COMM_InitialSubscriptionMonth__c</fullName>
    <label>Initial Subscription Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Language__c.field-meta.xml
<CustomField>
    <fullName>COMM_Language__c</fullName>
    <description>Field used to define the language used when communicating with the client</description>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pt_PT</fullName>
                <label>Portuguese (European)</label>
            </value>
            <value>
                <fullName>en_US</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Spanish</label>
            </value>
            <value>
                <fullName>en</fullName>
                <isActive>false</isActive>
                <label>en</label>
            </value>
            <value>
                <fullName>en_EN</fullName>
                <isActive>false</isActive>
                <label>en_EN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_LastName__c.field-meta.xml
<CustomField>
    <fullName>COMM_LastName__c</fullName>
    <label>Case Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <label>License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_NewCardRequest__c.field-meta.xml
<CustomField>
    <fullName>COMM_NewCardRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Card Request?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Order__c.field-meta.xml
<CustomField>
    <fullName>COMM_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Order record related on Case.</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Order Product record related on Case.</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <label>Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_PhoneNumber__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Subscription__c.field-meta.xml
<CustomField>
    <fullName>COMM_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>COMM_Subscription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SubscriptionPrice__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubscriptionPrice__c</fullName>
    <description>Field with the Price of a Subscription related on Case.</description>
    <label>Subscription Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>This is the unique number that identifies a taxable person (business) or non-taxable legal entity that is registered for VAT.</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/COMM_ChangeOwnership.recordType-meta.xml
<RecordType>
    <fullName>COMM_ChangeOwnership</fullName>
    <active>true</active>
    <businessProcess>Change Ownership</businessProcess>
    <description>Case for a request to change the ownership of a subscription</description>
    <label>Change Ownership</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/COMM_IndividualStaffRequest.recordType-meta.xml
<RecordType>
    <fullName>COMM_IndividualStaffRequest</fullName>
    <active>true</active>
    <businessProcess>Individual Staff Request</businessProcess>
    <description>Case to request individual staff attribute</description>
    <label>Individual Staff Request</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/COMM_ManualRenewal.recordType-meta.xml
<RecordType>
    <fullName>COMM_ManualRenewal</fullName>
    <active>true</active>
    <businessProcess>Manual renewal</businessProcess>
    <description>Manual Renewal Record Type</description>
    <label>Manual Renewal</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/COMM_NewCardDueToDamageLoss.recordType-meta.xml
<RecordType>
    <fullName>COMM_NewCardDueToDamageLoss</fullName>
    <active>true</active>
    <businessProcess>New Card due To Damage%2FLoss</businessProcess>
    <description>Case to request a new card for a subscription</description>
    <label>New Card due To Damage/Loss</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/COMM_NewPublicSubscription.recordType-meta.xml
<RecordType>
    <fullName>COMM_NewPublicSubscription</fullName>
    <active>true</active>
    <businessProcess>New Public Subscription</businessProcess>
    <description>Record Type for New Public Subscriptions.</description>
    <label>New Public Subscription</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/COMM_NewSubscription.recordType-meta.xml
<RecordType>
    <fullName>COMM_NewSubscription</fullName>
    <active>true</active>
    <businessProcess>New Subscription</businessProcess>
    <description>Case to renew a subscription manually</description>
    <label>New Subscription</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/COMM_RecurringPublicSubscription.recordType-meta.xml
<RecordType>
    <fullName>COMM_RecurringPublicSubscription</fullName>
    <active>true</active>
    <businessProcess>Recurring Public Subscription</businessProcess>
    <description>Record Type for Recurring Public Subscriptions.</description>
    <label>Recurring Public Subscription</label>
</RecordType>

force-app/main/default/objects/COMM_Subscription__c/COMM_Subscription__c.object-meta.xml
<CustomObject>
    <description>Object to represent a Subscription associated with a Client</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SBS-{0000}</displayFormat>
        <label>Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Account__c.field-meta.xml
<CustomField>
    <fullName>COMM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account associated with the Subscription Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Card__c.field-meta.xml
<CustomField>
    <fullName>COMM_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Card to be included with the Subscription</description>
    <label>Card</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Associated Product can only be a Card</errorMessage>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Card</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions (Card)</relationshipLabel>
    <relationshipName>CardSubscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Contact__c.field-meta.xml
<CustomField>
    <fullName>COMM_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact associated with the Subscription Record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Email__c.field-meta.xml
<CustomField>
    <fullName>COMM_Email__c</fullName>
    <description>Email of the client associated with the Subscription</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EndDate__c</fullName>
    <description>Date when the Subscription is scheduled to end</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_FirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstName__c</fullName>
    <description>First Name of the Client associated with the Subscription</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_InitialSubscriptionMonth__c.field-meta.xml
<CustomField>
    <fullName>COMM_InitialSubscriptionMonth__c</fullName>
    <description>Month where the Subscription will initially start</description>
    <label>Initial Subscription Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_LastName__c.field-meta.xml
<CustomField>
    <fullName>COMM_LastName__c</fullName>
    <description>Last Name of the Client associated with the Subscription</description>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <description>License Plate of the Vehicle associated with the Subscription</description>
    <label>License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Order__c.field-meta.xml
<CustomField>
    <fullName>COMM_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order associated with the Subscription</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order Product associated with the Subscription</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <description>Defines the periodicity of the subscription</description>
    <label>Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_PhoneNumber__c</fullName>
    <description>Phone Number of the Client associated with the Subscription</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Price__c.field-meta.xml
<CustomField>
    <fullName>COMM_Price__c</fullName>
    <description>Price of all products: Subscription or Subscription + Card</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product the Subscription is associated with</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Subscription can only be associated with a Subscription Product</errorMessage>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>COMM_Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_StartDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date when the Subscription starts</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>VAT Number of the Client associated with the Subscription</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/COMM_Language__c.field-meta.xml
<CustomField>
    <fullName>COMM_Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_LanguageCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <description>License plate to communicate with CPMS</description>
    <label>Reservation License Plate</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <description>Defines the periodicity of the subscription</description>
    <label>Subscription Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/COMM_DO_Case.cls
/**
 * @author           Daniel Lascas
 * @description      Case SObject Domain object class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    18/03/2024       ECOMM-368: Original version
 * Daniel Reto      17/06/2024       New Status and RT variable
 **/
public inherited sharing class COMM_DO_Case implements COMM_IDO_Case {
    //Record Type Developer Names
    public final static string INDIVIDUAL_STAFF_REQUEST_RT = 'COMM_IndividualStaffRequest';
    public final static string SUBSCRIPTION_REQUEST_RT = 'COMM_NewSubscription';
    public final static string CHANGE_OWNERSHIP_RT = 'COMM_ChangeOwnership';
    public final static string NEW_CARD_RT = 'COMM_NewCardDueToDamageLoss';
    public final static string NEW_PUBLIC_SUBSCRIPTION_REQUEST_RT = 'COMM_NewPublicSubscription';
    public final static string RECURRING_PUBLIC_SUBSCRIPTION_REQUEST_RT = 'COMM_RecurringPublicSubscription';
    public final static string MANUAL_RENEWAL_RT = 'COMM_ManualRenewal';
    //Case Status Picklist Values
    public final static string WAITING_APPROVAL_STATUS = 'Waiting Approval';
    public final static string IN_APPROVAL_STATUS = 'In Approval';
    public final static string PROCESS_CONCLUDED_STATUS = 'Process Concluded';
    public final static string WAITING_CONCLUSION = 'Waiting Conclusion';
    public final static string ARCHIVED_STATUS = 'Archived';
    public final static string EXPIRED_STATUS = 'Expired';
    public final static string WAITING_CONCLUSION_STATUS = 'Waiting Conclusion';
    //Case Type Picklist Values
    public final static string INDIVIDUAL_STAFF_TYPE = 'Individual Staff Request';
    public final static string NEW_PUBLIC_SUBSCRIPTION_TYPE = 'New Public Subscription';
    public final static string RECURRING_PUBLIC_SUBSCRIPTION_TYPE = 'Recurring Public Subscription';

    //Case Origin Picklist Values
    public final static string WEB_ORIGIN = 'Web';

    /**
     * @description Define Case records to be created base on Subscription record details.
     * @param subscription Subscription records by airport definition.
     * @param cardByAirportMap Card product record by airport definition.
     * @param orderSummaryByIdMap Order Summary record by identifier.
     * @param oItemSummaryBySubscriptionNbrMap Order Item Summary record by subscription number.
     * @param isRecurring Boolean to flag if Case is related on recurring Subscription.
     */
    @SuppressWarnings('PMD.ExcessiveParameterList')
    public static Case setCaseToCreate(
        COMM_Subscription__c subscription,
        Map<String, OrderItemSummary> cardByAirportMap,
        Map<Id, OrderSummary> orderSummaryByIdMap,
        Map<String, OrderItemSummary> oItemSummaryBySubscriptionNbrMap,
        Boolean isRecurring,
        Group sabaQueue
    ) {
        Case caseToCreate = new Case();
        caseToCreate.Type = setCaseType(isRecurring);
        caseToCreate.COMM_Subscription__c = subscription.Id;
        caseToCreate.COMM_Order__c = setCaseOrder(subscription, oItemSummaryBySubscriptionNbrMap, isRecurring);
        caseToCreate.COMM_OrderProduct__c = setCaseOrderProduct(subscription, oItemSummaryBySubscriptionNbrMap, isRecurring);
        caseToCreate.RecordTypeId = setCaseRecordType(isRecurring);
        caseToCreate.AccountId = subscription.COMM_Account__c;
        caseToCreate.ContactId = subscription.COMM_Contact__c;
        caseToCreate.Status = WAITING_CONCLUSION;
        caseToCreate.COMM_SubscriptionPrice__c = subscription.COMM_Price__c;
        caseToCreate.ProductId = subscription.COMM_Product__c;
        caseToCreate.COMM_InitialSubscriptionMonth__c = setCaseInitialSubscriptionMonth(subscription, isRecurring);
        caseToCreate.COMM_StartDate__c = setCaseStartDate(subscription, oItemSummaryBySubscriptionNbrMap, isRecurring);
        caseToCreate.COMM_EndDate__c = setCaseEndDate(subscription, oItemSummaryBySubscriptionNbrMap, isRecurring);
        caseToCreate.COMM_LicensePlate__c = subscription.COMM_LicensePlate__c;
        caseToCreate.COMM_Periodicity__c = subscription.COMM_Periodicity__c;
        caseToCreate.COMM_FirstName__c = subscription.COMM_FirstName__c;
        caseToCreate.COMM_LastName__c = subscription.COMM_LastName__c;
        caseToCreate.COMM_VATNumber__c = subscription.COMM_VATNumber__c;
        caseToCreate.COMM_PhoneNumber__c = subscription.COMM_PhoneNumber__c;
        caseToCreate.SuppliedEmail = subscription.COMM_Email__c;
        caseToCreate.COMM_Address__Street__s = subscription.COMM_Address__Street__s;
        caseToCreate.COMM_Address__City__s = subscription.COMM_Address__City__s;
        caseToCreate.COMM_Address__CountryCode__s = subscription.COMM_Address__CountryCode__s;
        caseToCreate.COMM_Address__PostalCode__s = subscription.COMM_Address__PostalCode__s;
        caseToCreate.COMM_Card__c = setCaseCard(subscription, isRecurring);
        caseToCreate.COMM_NewCardRequest__c = setCaseNewCardRequest(isRecurring);
        caseToCreate.COMM_Language__c = setCaseLanguage(subscription, orderSummaryByIdMap, oItemSummaryBySubscriptionNbrMap, isRecurring);
        caseToCreate.COMM_OrderSummary__c = isRecurring == false ? subscription.COMM_OrderSummary__c : oItemSummaryBySubscriptionNbrMap.get(subscription.Id)?.OrderSummaryId;
        caseToCreate.OwnerId = sabaQueue.Id;

        if (!isRecurring) {
            for (OrderItemSummary orderItemSummary : cardByAirportMap.values()) {
                if (orderItemSummary.Product2.Id == subscription.COMM_Card__c) {
                    caseToCreate.COMM_CardPrice__c = orderItemSummary.TotalPrice;
                }
            }
        } else {
            caseToCreate.COMM_SubscriptionNumber__c = subscription.COMM_SubscriptionNumber__c;
        }

        return caseToCreate;
    }

    /**
     * @description Define Case Type of Case to create.
     * @param isRecurring to flag if Case is related on recurring Subscription.
     * @return String with Case Type value.
     */
    private static String setCaseType(Boolean isRecurring) {
        return isRecurring == false ? COMM_DO_Case.NEW_PUBLIC_SUBSCRIPTION_TYPE : COMM_DO_Case.RECURRING_PUBLIC_SUBSCRIPTION_TYPE;
    }

    /**
     * @description Define related Order on Case to create.
     * @param subscription Subscription record to process.
     * @param oItemSummaryBySubscriptionNbrMap Order Item Summary by existing Subscription record Number to process.
     * @param isRecurring to flag if Case is related on recurring Subscription.
     * @return String with Order identifier
     */
    private static String setCaseOrder(
        COMM_Subscription__c subscription,
        Map<String, OrderItemSummary> oItemSummaryBySubscriptionNbrMap,
        Boolean isRecurring
    ) {
        return isRecurring == false
            ? subscription.COMM_Order__c
            : oItemSummaryBySubscriptionNbrMap.get(subscription.Id).OriginalOrderItem.OrderId;
    }

    /**
     * @description Define related Order Product on Case to create.
     * @param subscription Subscription record to process.
     * @param oItemSummaryBySubscriptionNbrMap Order Item Summary by existing Subscription record Number to process.
     * @param isRecurring to flag if Case is related on recurring Subscription.
     * @return String with Order Product identifier
     */
    private static String setCaseOrderProduct(
        COMM_Subscription__c subscription,
        Map<String, OrderItemSummary> oItemSummaryBySubscriptionNbrMap,
        Boolean isRecurring
    ) {
        return isRecurring == false
            ? subscription.COMM_OrderProduct__c
            : oItemSummaryBySubscriptionNbrMap.get(subscription.Id).OriginalOrderItemId;
    }

    /**
     * @description Define Record Type of Case to create.
     * @param isRecurring to flag if Case is related on recurring Subscription.
     * @return String with Case Record Type identifier value.
     */
    private static String setCaseRecordType(Boolean isRecurring) {
        return isRecurring == false
            ? Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(COMM_DO_Case.NEW_PUBLIC_SUBSCRIPTION_REQUEST_RT).RecordTypeId
            : Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(COMM_DO_Case.RECURRING_PUBLIC_SUBSCRIPTION_REQUEST_RT).RecordTypeId;
    }

    /**
     * @description Define Case Initial Subscription Month.
     * @param subscription Subscription record to process.
     * @param isRecurring to flag if Case is related on recurring Subscription.
     * @return String with Initial Month value.
     */
    private static String setCaseInitialSubscriptionMonth(COMM_Subscription__c subscription, Boolean isRecurring) {
        return isRecurring == false ? subscription.COMM_InitialSubscriptionMonth__c : datetime.now().format('MMMM');
    }

    /**
     * @description Define Case Start Date.
     * @param subscription Subscription record to process.
     * @param oItemSummaryBySubscriptionNbrMap Order Item Summary by existing Subscription record Number to process.
     * @param isRecurring to flag if Case is related on recurring Subscription.
     * @return Date with Case Start Date.
     */
    private static Date setCaseStartDate(
        COMM_Subscription__c subscription,
        Map<String, OrderItemSummary> oItemSummaryBySubscriptionNbrMap,
        Boolean isRecurring
    ) {
        return isRecurring == false
            ? subscription.COMM_StartDate__c
            : oItemSummaryBySubscriptionNbrMap.get(subscription.Id).OriginalOrderItem.COMM_ReservationStart__c?.date();
    }

    /**
     * @description Define Case End Date.
     * @param subscription Subscription record to process.
     * @param oItemSummaryBySubscriptionNbrMap Order Item Summary by existing Subscription record Number to process.
     * @param isRecurring to flag if Case is related on recurring Subscription.
     * @return Date with Case End Date.
     */
    private static Date setCaseEndDate(
        COMM_Subscription__c subscription,
        Map<String, OrderItemSummary> oItemSummaryBySubscriptionNbrMap,
        Boolean isRecurring
    ) {
        return isRecurring == false
            ? subscription.COMM_EndDate__c
            : oItemSummaryBySubscriptionNbrMap.get(subscription.Id).OriginalOrderItem.COMM_ReservationEnd__c?.date();
    }

    /**
     * @description Define Case Card.
     * @param subscription Subscription record to process.
     * @param isRecurring to flag if Case is related on recurring Subscription.
     * @return String with Case Card identifier.
     */
    private static String setCaseCard(COMM_Subscription__c subscription, Boolean isRecurring) {
        return isRecurring == false ? subscription.COMM_Card__c : null;
    }

    /**
     * @description Define if Case has new Card request.
     * @param isRecurring to flag if Case is related on recurring Subscription.
     * @return Boolean to flag if Case has New Card.
     */
    private static Boolean setCaseNewCardRequest(Boolean isRecurring) {
        return isRecurring == false ? true : false;
    }

    /**
     * @description Define Case Language.
     * @param subscription Subscription record to process.
     * @param orderSummaryByIdMap Order Summary by identifier to process.
     * @param oItemSummaryBySubscriptionNbrMap Order Item Summary by existing Subscription record Number to process.
     * @param isRecurring to flag if Case is related on recurring Subscription.
     * @return String with Case language value.
     */
    @SuppressWarnings('PMD.ExcessiveParameterList')
    private static String setCaseLanguage(
        COMM_Subscription__c subscription,
        Map<Id, OrderSummary> orderSummaryByIdMap,
        Map<String, OrderItemSummary> oItemSummaryBySubscriptionNbrMap,
        Boolean isRecurring
    ) {
        return isRecurring == false
            ? orderSummaryByIdMap.get(subscription.COMM_OrderSummary__c).COMM_Language__c
            : orderSummaryByIdMap.get(oItemSummaryBySubscriptionNbrMap.get(subscription.Id).OrderSummaryId).COMM_Language__c;
    }
}