force-app/main/default/objects/Case/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <label>Airport</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_FirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstName__c</fullName>
    <label>Case First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_JobRole__c.field-meta.xml
<CustomField>
    <fullName>COMM_JobRole__c</fullName>
    <label>Job Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_LastName__c.field-meta.xml
<CustomField>
    <fullName>COMM_LastName__c</fullName>
    <label>Case Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <label>License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_PhoneNumber__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SecondaryLicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryLicensePlate__c</fullName>
    <label>Secondary License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SecondaryVehicleBrand__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryVehicleBrand__c</fullName>
    <label>Secondary Vehicle Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SecondaryVehicleModel__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryVehicleModel__c</fullName>
    <label>Secondary Vehicle Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>This is the unique number that identifies a taxable person (business) or non-taxable legal entity that is registered for VAT.</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_VehicleBrand__c.field-meta.xml
<CustomField>
    <fullName>COMM_VehicleBrand__c</fullName>
    <label>Vehicle Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_VehicleModel__c.field-meta.xml
<CustomField>
    <fullName>COMM_VehicleModel__c</fullName>
    <label>Vehicle Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_SL_WS_GetFormDetails.cls
/**
 * @author Daniel Reto
 * @description Class to support the Web Service to get Case details for Subscription form.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      21/10/2024       Original version
 **/
public inherited sharing class COMM_SL_WS_GetFormDetails {
    private static final String INVALID_CASEID_PARAMETER_ERROR = 'The Case Id received doesn\'t exist!';
    /**
     * @description Check if any Order record exists for the request order number.
     * @param String caseIdValue - Case Id to search
     * @return COMM_WS_FormDetailsOutput output with Case Details data
     */
    public COMM_WS_FormDetailsOutput checkFormDetails(String caseIdValue) {
        COMM_WS_FormDetailsOutput outputRequest = new COMM_WS_FormDetailsOutput();

        COMM_REP_Case caseRep = new COMM_REP_Case();
        List<Case> caseList = caseRep.getCasesByCaseIds(new Set<Id>{ caseIdValue });

        if (caseList != null && caseList.size() > 0) {
            outputRequest.personalFirstName = caseList.get(0).COMM_FirstName__c;
            outputRequest.personalLastName = caseList.get(0).COMM_LastName__c;
            outputRequest.personalVAT = caseList.get(0).COMM_VATNumber__c;
            outputRequest.personalAddress = caseList.get(0).COMM_Address__Street__s;
            outputRequest.personalCity = caseList.get(0).COMM_Address__City__s;
            outputRequest.personalCountry = caseList.get(0).COMM_Address__CountryCode__s;
            outputRequest.personalZipCode = caseList.get(0).COMM_Address__PostalCode__s;
            outputRequest.personalPhoneCode = caseList.get(0).COMM_PhoneNumber__c?.substringBefore(' ');
            outputRequest.personalPhoneNumber = caseList.get(0).COMM_PhoneNumber__c?.substringAfter(' ');
            outputRequest.personalEmail = caseList.get(0).SuppliedEmail;
            outputRequest.jobRole = caseList.get(0).COMM_JobRole__c;
            outputRequest.vehicleBrand = caseList.get(0).COMM_VehicleBrand__c;
            outputRequest.vehicleModel = caseList.get(0).COMM_VehicleModel__c;
            outputRequest.vehicleLicense = caseList.get(0).COMM_LicensePlate__c;
            outputRequest.secondVehicleBrand = caseList.get(0).COMM_SecondaryVehicleBrand__c;
            outputRequest.secondVehicleModel = caseList.get(0).COMM_SecondaryVehicleModel__c;
            outputRequest.secondVehicleLicense = caseList.get(0).COMM_SecondaryLicensePlate__c;
            outputRequest.recordTypeName = caseList.get(0).RecordType.Name;
            outputRequest.recordTypeDeveloperName = caseList.get(0).RecordType.DeveloperName;
            outputRequest.airport = caseList.get(0).COMM_Airport__c;
            outputRequest.status = caseList.get(0).Status;
        } else {
            throw new COMM_SL_WS_GetFormDetailsException(INVALID_CASEID_PARAMETER_ERROR);
        }

        return outputRequest;
    }

    /**
     * @description Salesforce adapter exception
     */
    public class COMM_SL_WS_GetFormDetailsException extends Exception {
    }
}