force-app/main/default/objects/Case/fields/COMM_Active__c.field-meta.xml
<CustomField>
    <fullName>COMM_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Subscription__c.field-meta.xml
<CustomField>
    <fullName>COMM_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>COMM_Subscription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/COMM_Capacity__c.object-meta.xml
<CustomObject>
    <description>The available capacity for a given Product</description>
    <label>Capacity</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Active__c.field-meta.xml
<CustomField>
    <fullName>COMM_Active__c</fullName>
    <description>Determine if Record is Active</description>
    <formula>COMM_ValidTo__c &gt; NOW()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Capacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Capacity__c</fullName>
    <description>It is the daily capacity set by hour, that is constant throughout the operating hours.

This capacity configuration is not applicable to subscriptions.

For the subscriptions, the capacity is calculated by multiplying the total number of parking spaces by the multiplier. This capacity is constant, therefore is not defined by hour.</description>
    <inlineHelpText>To put the product as suspended, changed capacity to 0.</inlineHelpText>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the capacity for specific period of times will be applied</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>For Subscription, product must also be subscription.
For Capacity, product must also be a non-subscription</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Capacity</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>notEqual</operation>
            <value>Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Capacities</relationshipLabel>
    <relationshipName>Capacities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the capacity is valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/COMM_Subscription__c.object-meta.xml
<CustomObject>
    <description>Object to represent a Subscription associated with a Client</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SBS-{0000}</displayFormat>
        <label>Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Active__c.field-meta.xml
<CustomField>
    <fullName>COMM_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if the Subscription is currently Active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_ActiveSubscriptionRequest__c.field-meta.xml
<CustomField>
    <fullName>COMM_ActiveSubscriptionRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to display the open Subscription Request</description>
    <label>Active Subscription Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>ActiveSubscriptionRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EndDate__c</fullName>
    <description>Date when the Subscription is scheduled to end</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_OCIEndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_OCIEndDate__c</fullName>
    <description>Field which will store the Product valid date to identify the possibility to extend the Subscription End Date based on the Periodicity.</description>
    <label>OCI End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product the Subscription is associated with</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Subscription can only be associated with a Subscription Product</errorMessage>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>COMM_Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Status__c.field-meta.xml
<CustomField>
    <fullName>COMM_Status__c</fullName>
    <description>Current Status of the Subscription</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Approval</fullName>
                <default>true</default>
                <label>In Approval</label>
            </value>
            <value>
                <fullName>Waiting Conclusion</fullName>
            </value>
            <value>
                <fullName>Process Concluded</fullName>
            </value>
            <value>
                <fullName>Request Denied</fullName>
            </value>
            <value>
                <fullName>Archieved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Pending Form</fullName>
                <isActive>false</isActive>
                <label>Pending Form</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>To capture all sort of errors</description>
    <label>Error and Log</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors and Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex_Class</fullName>
                <label>Apex Class</label>
            </value>
            <value>
                <fullName>Apex_Trigger</fullName>
                <label>Apex Trigger</label>
            </value>
            <value>
                <fullName>Process_Builder</fullName>
                <label>Process Builder</label>
            </value>
            <value>
                <fullName>HTTP_Callout</fullName>
                <label>HTTP Callout</label>
            </value>
            <value>
                <fullName>HTTP_Inbound</fullName>
                <label>HTTP Inbound</label>
            </value>
            <value>
                <fullName>Platform_Event</fullName>
                <label>Platform Event</label>
            </value>
            <value>
                <fullName>Apex_Batch</fullName>
                <label>Apex Batch</label>
            </value>
            <value>
                <fullName>Log</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Job Execution record, it is filled if the error comes from the Batch Framework</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipName>Error_and_Monitoring_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Job_Scope__c.field-meta.xml
<CustomField>
    <fullName>Job_Scope__c</fullName>
    <description>The Record IDs that are in scope if the event was fired from the execute() method of a batch job. If the batch job uses custom iterators instead of sObjects, JobScope is the toString() representation of the iterable objects. Maximum length is 40000 characters.</description>
    <label>Job Scope</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/StackTraceString__c.field-meta.xml
<CustomField>
    <fullName>StackTraceString__c</fullName>
    <description>Exception stacktracestring</description>
    <label>StackTraceString</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Product for the Product Record</description>
    <label>Parent Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Airport needs to be the same in both Parent and Child Product</errorMessage>
        <filterItems>
            <field>Product2.COMM_Airport__c</field>
            <operation>equals</operation>
            <valueField>$Source.COMM_Airport__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_Async_SubscFreeStockOnEndDate.cls
/**
 * @author Daniel Reto
 * @description Batch class to free Stock in OCI after the End Date
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      13/05/2024      ECOMM-1126: Original version
 * Daniel Reto      17/06/2024      set new Parameters to be possible to reuse this batch
 **/
public with sharing class COMM_Async_SubscFreeStockOnEndDate extends FW_AsyncHandler implements Database.Batchable<SObject>, Database.Stateful {
    //batch framework parameters (used by the framework to pass values to the batch dynamically)
    @TestVisible
    private final static String PARAMETER_DAYS_BEFORE_END_DATE_OCI = 'Days To Add Before End Date - Free Stock';
    @TestVisible
    private final static String PARAMETER_DAYS_BEFORE_END_DATE_SUBSCRIPTION_UPDATE = 'Days To Add Before End Date - Update Subscription';
    @TestVisible
    private final static String PARAMETER_RECORD_TYPE_FILTER = 'Record Type';

    private COMM_IREP_Capacity capacityRep;
    private COMM_IREP_Subscription subscriptionRep;

    public static final List<SObjectField> PRODUCT_FIELDS = new List<SObjectField>{ Product2.COMM_ParentProduct__c, Product2.ProductCode, Product2.IsActive };
    public static final List<SObjectField> RECORDTYPE_FIELDS = new List<SObjectField>{ RecordType.DeveloperName };
    public static final List<SObjectField> CASE_FIELDS = new List<SObjectField>{ Case.Id, Case.Status };

    private Integer daysBeforeEndDateOCI;
    private Integer daysBeforeEndDateSubscriptionUpdate;

    /**
     * @description Class Constructor to initialize REP class
     */
    public COMM_Async_SubscFreeStockOnEndDate() {
        this.capacityRep = new COMM_REP_Capacity();
        this.subscriptionRep = new COMM_REP_Subscription();
    }

    @testVisible
    private COMM_Async_SubscFreeStockOnEndDate(
        COMM_IREP_Capacity capacityRep,
        COMM_IREP_Subscription subscriptionRep,
        FW_IREP_JobExecution jobExecutionRep,
        FW_IREP_Parameters parameterRep
    ) {
        this.capacityRep = capacityRep;
        this.subscriptionRep = subscriptionRep;
        this.jobExecutionRep = jobExecutionRep;
        this.parameterRep = parameterRep;
    }

    /**
     * @description Batch Start Method. According to the Batch Parameters, initiates query to obtain all records
     * of a specified SObject, whose specified Date Field has a date set a specific number of months ago.
     *
     * @param bc Context Information of the executed batch
     * @return Database.QueryLocator with the built query
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        setAsyncApexJobId(bc.getJobId());

        SObjectType sobjType = Schema.getGlobalDescribe().get('COMM_Subscription__c');
        daysBeforeEndDateOCI = Integer.valueOf(getParameterValue(PARAMETER_DAYS_BEFORE_END_DATE_OCI));
        daysBeforeEndDateSubscriptionUpdate = Integer.valueOf(getParameterValue(PARAMETER_DAYS_BEFORE_END_DATE_SUBSCRIPTION_UPDATE));
        String recordTypeFilter = getParameterValue(PARAMETER_RECORD_TYPE_FILTER);
        FW_QueryBuilder parentQuery = new FW_QueryBuilder(Case.SObjectType)
            .selectFields(CASE_FIELDS)
            .selectParentFields(Case.RecordTypeId, new List<SObjectField>{ RecordType.DeveloperName });

        FW_QueryBuilder query = new FW_QueryBuilder(sobjType)
            .selectFields(COMM_REP_Subscription.SUBSCRIPTION_FIELDS)
            .selectParentFields(COMM_Subscription__c.COMM_Product__c, PRODUCT_FIELDS)
            .selectParentFields(COMM_Subscription__c.RecordTypeId, RECORDTYPE_FIELDS)
            .selectFields(COMM_Subscription__c.COMM_ActiveSubscriptionRequest__c, parentQuery)
            .setWhere(
                '( COMM_Status__c = \'' +
                    COMM_DO_Subscription.STATUS_PROCESS_CONCLUDED +
                    '\' OR COMM_Status__c = \'' +
                    COMM_DO_Subscription.STATUS_ARCHIEVED +
                    '\' ) AND (COMM_EndDate__c < ' +
                    String.valueOf(System.now().addDays(daysBeforeEndDateSubscriptionUpdate).dateGMT()).left(10) +
                    ' OR COMM_EndDate__c < ' +
                    String.valueOf(System.now().addDays(daysBeforeEndDateOCI).dateGMT()).left(10) +
                    ') AND RecordType.DeveloperName = \'' +
                    recordTypeFilter +
                    '\' AND COMM_OCIEndDate__c != null'
            )
            .whereEquals('COMM_Active__c', true);

        return executeQuery(query);
    }

    /**
     * @description Batch Execute Method. Deletes the records obtained in the start method's query.
     *
     * @param bc Context Information of the executed batch
     * @param productsList List of Capacity records (distinct ProductCodes) that were obtained on the start method's query
     */
    @SuppressWarnings('PMD.CognitiveComplexity')
    public void execute(Database.BatchableContext bc, List<COMM_Subscription__c> subscriptionsList) {
        if (Test.isRunningTest()) {
            if (subscriptionsList[0].RecordType.DeveloperName == COMM_DO_Subscription.RECORDTYPE_PARTNER) {
                daysBeforeEndDateOCI = 0;
                daysBeforeEndDateSubscriptionUpdate = 0;
            } else if (subscriptionsList[0].RecordType.DeveloperName == COMM_DO_Subscription.RECORDTYPE_DIRECT_SALES) {
                daysBeforeEndDateOCI = 15;
                daysBeforeEndDateSubscriptionUpdate = 0;
            }
        }
        Set<String> parentProductIdSet = new Set<String>();
        Map<String, List<COMM_Subscription__c>> subscriptionListByProductCodeMap = new Map<String, List<COMM_Subscription__c>>();
        List<COMM_Capacity__c> capacitiesList = new List<COMM_Capacity__c>();
        Map<String, Date> validToByParentProductIdMap = new Map<String, Date>();
        // Boolean variable to identify if a update must happen to updated the related Subscription Records
        Boolean requiresSubscriptionUpdate = false;

        // create a list of Subscriptions by Parent Product Code, to be possible to send the correct capacity being released to OCI + update subscription records to be deactivated (Status and Active fields)
        for (COMM_Subscription__c subscriptionRecord : subscriptionsList) {
            // if subscription record type is Partner, the record will be updated + OCI stock will be free (only for Subscriptions with Status "Process Concluded")
            if (subscriptionRecord.RecordType.DeveloperName == COMM_DO_Subscription.RECORDTYPE_PARTNER) {
                if (subscriptionRecord.COMM_Status__c == COMM_DO_Subscription.STATUS_ARCHIEVED) {
                    subscriptionRecord.COMM_Active__c = false;
                    subscriptionRecord.COMM_OCIEndDate__c = subscriptionRecord.COMM_EndDate__c;
                    requiresSubscriptionUpdate = true;
                } else if (subscriptionRecord.COMM_Status__c == COMM_DO_Subscription.STATUS_PROCESS_CONCLUDED) {
                    if(subscriptionRecord.COMM_Product__r.isActive){
                        if (subscriptionListByProductCodeMap.containsKey(subscriptionRecord.COMM_Product__r.ProductCode)) {
                            subscriptionListByProductCodeMap.get(subscriptionRecord.COMM_Product__r.ProductCode).add(subscriptionRecord);
                        } else {
                            subscriptionListByProductCodeMap.put(
                                subscriptionRecord.COMM_Product__r.ProductCode,
                                new List<COMM_Subscription__c>{ subscriptionRecord }
                            );
                        }
                        parentProductIdSet.add(subscriptionRecord.COMM_Product__r.COMM_ParentProduct__c);
                    }
                    subscriptionRecord.COMM_Active__c = false;
                    subscriptionRecord.COMM_Status__c = COMM_DO_Subscription.STATUS_ARCHIEVED;
                    subscriptionRecord.COMM_OCIEndDate__c = subscriptionRecord.COMM_EndDate__c;
                    requiresSubscriptionUpdate = true;
                }
            }
            // if subscription record type is Direct Sales, the record will be updated (if the End Date is overdue) + OCI stock will be free (only if today date is End Date - daysBeforeEndDateOCI AND any case record is open to renew the subscription)
            if (subscriptionRecord.RecordType.DeveloperName == COMM_DO_Subscription.RECORDTYPE_DIRECT_SALES) {
                // only if there is no pending open case the subscription can be terminated and stock released
                if (
                    subscriptionRecord.COMM_ActiveSubscriptionRequest__c == null ||
                    subscriptionRecord.COMM_ActiveSubscriptionRequest__r.RecordType.DeveloperName !=
                    COMM_DO_Case.RECURRING_PUBLIC_SUBSCRIPTION_REQUEST_RT ||
                    (subscriptionRecord.COMM_ActiveSubscriptionRequest__r.RecordType.DeveloperName ==
                    COMM_DO_Case.RECURRING_PUBLIC_SUBSCRIPTION_REQUEST_RT &&
                    subscriptionRecord.COMM_ActiveSubscriptionRequest__r.Status != COMM_DO_Case.WAITING_CONCLUSION_STATUS)
                ) {
                    if (subscriptionRecord.COMM_EndDate__c < System.now().addDays(daysBeforeEndDateSubscriptionUpdate).dateGMT()) {
                        subscriptionRecord.COMM_Status__c = COMM_DO_Subscription.STATUS_ARCHIEVED;
                        subscriptionRecord.COMM_Active__c = false;
                        requiresSubscriptionUpdate = true;
                    }
                    if (
                        subscriptionRecord.COMM_OCIEndDate__c > subscriptionRecord.COMM_EndDate__c &&
                        subscriptionRecord.COMM_EndDate__c < System.now().addDays(daysBeforeEndDateOCI).dateGMT()
                    ) {
                        if(subscriptionRecord.COMM_Product__r.isActive){
                            if (subscriptionListByProductCodeMap.containsKey(subscriptionRecord.COMM_Product__r.ProductCode)) {
                                subscriptionListByProductCodeMap.get(subscriptionRecord.COMM_Product__r.ProductCode).add(subscriptionRecord);
                            } else {
                                subscriptionListByProductCodeMap.put(
                                    subscriptionRecord.COMM_Product__r.ProductCode,
                                    new List<COMM_Subscription__c>{ subscriptionRecord }
                                );
                            }
                            parentProductIdSet.add(subscriptionRecord.COMM_Product__r.COMM_ParentProduct__c);
                        }
                        subscriptionRecord.COMM_OCIEndDate__c = subscriptionRecord.COMM_EndDate__c;
                        requiresSubscriptionUpdate = true;
                    }
                }
            }
        }

        List<Error_Log__c> errorListToWrite = new List<Error_Log__c>();

        // if at least one Parent Product Code is found we must release the capacity on OCI
        if (!parentProductIdSet.isEmpty()) {
            // get capacity related records
            capacitiesList = capacityRep.getCapacityByProductIds(parentProductIdSet);

            // map Valid to date on each Capacity for each Parent Product, to be able to identify the End date of each Parent Product
            for (COMM_Capacity__c capacityRecord : capacitiesList) {
                validToByParentProductIdMap.put(capacityRecord.COMM_Product__c, capacityRecord.COMM_ValidTo__c.date());
            }

            // set input request to send for OCI
            COMM_WS_ReservationInput input = new COMM_WS_ReservationInput();
            input.expirationSeconds = 0;
            input.product = new List<COMM_WS_ReservationInput.Product>();

            // generate COMM_WS_ReservationInput wrapper for each Subscription being deactivated
            for (String productCode : subscriptionListByProductCodeMap.keySet()) {
                for (COMM_Subscription__c subscriptionRecord : subscriptionListByProductCodeMap.get(productCode)) {
                    COMM_WS_ReservationInput.Product product = new COMM_WS_ReservationInput.Product();
                    product.productId = productCode;
                    product.startDate = COMM_GEN_Utility.generateDateTimeDataType(subscriptionRecord.COMM_EndDate__c.addDays(1));
                    product.endDate = COMM_GEN_Utility.generateDateTimeDataType(
                        validToByParentProductIdMap.get(subscriptionRecord.COMM_Product__r.COMM_ParentProduct__c)
                    );
                    input.product.add(product);
                }
            }

            // OCI capacity release
            if(!input.product.isEmpty()){
                try{
            COMM_SL_WS_OCIReservations ociReservation = new COMM_SL_WS_OCIReservations();
            ociReservation.release(input);
                }
                catch (Exception e){                    
                    Error_Log__c error = new Error_Log__c();
                    error.Job_Execution__c = bc.getJobId();
                    error.Error_Message__c = e.getMessage();
                    error.StackTraceString__c = e.getStackTraceString();
                    error.Category__c = 'Apex_Batch';
                    error.Exception_Type_Name__c = e.getTypeName();
                    error.Job_Scope__c = (new Map<Id,COMM_Subscription__c>(subscriptionsList)).keySet().toString();
                }
            }
        }

        //Subscription update
        if (requiresSubscriptionUpdate) {
            subscriptionRep.updateSObjects(subscriptionsList);
        }

        //insert errors
        if(!errorListToWrite.isEmpty()){
            FW_REP_ErrorLog errorRepository = new FW_REP_ErrorLog();
            errorRepository.insertSObjects(errorListToWrite);
        }
    }

    /**
     * @description Batch Finish Method. Initiates the Framework batch finished process.
     *
     * @param bc Context Information of the executed batch
     */
    public void finish(Database.BatchableContext bc) {
        finishBatch(bc.getJobId());
    }
}