force-app/main/default/objects/Case/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <label>Airport</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Card__c.field-meta.xml
<CustomField>
    <fullName>COMM_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Subscription__c.field-meta.xml
<CustomField>
    <fullName>COMM_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>COMM_Subscription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SubscriptionNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubscriptionNumber__c</fullName>
    <label>Subscription Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/COMM_Capacity__c.object-meta.xml
<CustomObject>
    <description>The available capacity for a given Product</description>
    <label>Capacity</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Capacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Capacity__c</fullName>
    <description>It is the daily capacity set by hour, that is constant throughout the operating hours.

This capacity configuration is not applicable to subscriptions.

For the subscriptions, the capacity is calculated by multiplying the total number of parking spaces by the multiplier. This capacity is constant, therefore is not defined by hour.</description>
    <inlineHelpText>To put the product as suspended, changed capacity to 0.</inlineHelpText>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the capacity for specific period of times will be applied</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>For Subscription, product must also be subscription.
For Capacity, product must also be a non-subscription</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Capacity</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>notEqual</operation>
            <value>Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Capacities</relationshipLabel>
    <relationshipName>Capacities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the capacity is valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/COMM_Subscription__c.object-meta.xml
<CustomObject>
    <description>Object to represent a Subscription associated with a Client</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SBS-{0000}</displayFormat>
        <label>Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_ActiveSubscriptionRequest__c.field-meta.xml
<CustomField>
    <fullName>COMM_ActiveSubscriptionRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to display the open Subscription Request</description>
    <label>Active Subscription Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>ActiveSubscriptionRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport the Subscription is associated with</description>
    <formula>CASE(COMM_Product__r.COMM_Airport__c,
&quot;OPO&quot;, &quot;Porto&quot;,
&quot;LIS&quot;,&quot;Lisbon&quot;,
&quot;FAO&quot;,&quot;Faro&quot;,
&quot;FNC&quot;,&quot;Madeira&quot;,
&quot;PDL&quot;,&quot;Ponta Delgada&quot;,
&quot;&quot;)</formula>
    <label>Airport</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Card__c.field-meta.xml
<CustomField>
    <fullName>COMM_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Card to be included with the Subscription</description>
    <label>Card</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Associated Product can only be a Card</errorMessage>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Card</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions (Card)</relationshipLabel>
    <relationshipName>CardSubscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EndDate__c</fullName>
    <description>Date when the Subscription is scheduled to end</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_OCIEndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_OCIEndDate__c</fullName>
    <description>Field which will store the Product valid date to identify the possibility to extend the Subscription End Date based on the Periodicity.</description>
    <label>OCI End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product the Subscription is associated with</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Subscription can only be associated with a Subscription Product</errorMessage>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>COMM_Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_SubscriptionNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubscriptionNumber__c</fullName>
    <description>Number of the Subscription, to be filled by SABA</description>
    <label>Subscription Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/COMM_SubscriptionNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubscriptionNumber__c</fullName>
    <description>Number of the Subscription</description>
    <label>Subscription Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Product for the Product Record</description>
    <label>Parent Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Airport needs to be the same in both Parent and Child Product</errorMessage>
        <filterItems>
            <field>Product2.COMM_Airport__c</field>
            <operation>equals</operation>
            <valueField>$Source.COMM_Airport__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_SL_PublicSubscriptionCreation.cls
/**
 * @author Carlos Fusco
 * @description Service for Public Subscription Creation on Invoice paid.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer          Date             Description
 * -----------------------------------------------------------------------------------
 * Carlos Fusco     10/06/2024       Original version
 **/
public with sharing class COMM_SL_PublicSubscriptionCreation {
    private static final Map<String, String> AIRPORT_DEFINITION = COMM_GEN_Utility.getPicklistMap(Schema.Product2.COMM_Airport__c, false);
    private static final List<String> PRODUCT_FAMILIES = new List<String>{ COMM_DO_Product2.CATEGORY_CARD, COMM_DO_Product2.CATEGORY_SUBSCRIPTION };
    private static final String ENTITY_ITEM_TYPE = 'Order Product';
    private static COMM_IREP_Group groupRep = new COMM_REP_Group();
    private static COMM_IREP_Subscription subsriptionRep = new COMM_REP_Subscription();
    private static COMM_IREP_Invoice invoiceRep = new COMM_REP_Invoice();
    private static COMM_IREP_InvoiceLine invoiceLineRep = new COMM_REP_InvoiceLine();
    private static COMM_IREP_OrderItemSummary orderItemSummaryRep = new COMM_REP_OrderItemSummary();
    private static COMM_IREP_Capacity capacityRep = new COMM_REP_Capacity();
    private static Boolean isRecurring = false;

    /**
     * @description invocable method to handle Public Subscription and related Case creation for paid processed invoices.
     * @param invoiceIdsList List of invoice identifiers to process.
     */
    @InvocableMethod(label='Create Public Subscription' description='Create Public Subscription and related Case on Invoice paid.')
    public static void createPublicSubscription(List<Id> invoiceIdsList) {
        Map<String, OrderItemSummary> oItemSummaryBySubscriptionNbrMap = new Map<String, OrderItemSummary>();
        Map<String, OrderItemSummary> cardByAirportMap = new Map<String, OrderItemSummary>();
        Map<Id, OrderSummary> orderSummaryByIdMap = new Map<Id, OrderSummary>();
        Map<String, List<COMM_Subscription__c>> subscriptionsByAirportMap = new Map<String, List<COMM_Subscription__c>>();
        Map<Id, OrderItemSummary> orderItemSummaryByIdMap = new Map<Id, OrderItemSummary>(getOrderItemSummary(invoiceIdsList));
        Map<String, Set<String>> productSetByParentProductIdMap = new Map<String, Set<String>>();

        if (orderItemSummaryByIdMap.isEmpty()) {
            return;
        }

        for (OrderItemSummary orderItemSummary : orderItemSummaryByIdMap.values()) {
            if (orderItemSummary.Product2.Family == COMM_DO_Product2.CATEGORY_SUBSCRIPTION) {
                if (String.isBlank(orderItemSummary.COMM_SubscriptionNumber__c)) {
                    COMM_Subscription__c subscriptionToCreate = COMM_DO_Subscription.setSubscriptionToCreate(orderItemSummary);
                    if (!subscriptionsByAirportMap.containsKey(AIRPORT_DEFINITION.get(orderItemSummary.Product2.COMM_Airport__c))) {
                        subscriptionsByAirportMap.put(
                            AIRPORT_DEFINITION.get(orderItemSummary.Product2.COMM_Airport__c),
                            new List<COMM_Subscription__c>()
                        );
                    }
                    subscriptionsByAirportMap.get(AIRPORT_DEFINITION.get(orderItemSummary.Product2.COMM_Airport__c)).add(subscriptionToCreate);
                    if(!productSetByParentProductIdMap.containsKey(orderItemSummary.Product2.COMM_ParentProduct__c)){
                        productSetByParentProductIdMap.put(orderItemSummary.Product2.COMM_ParentProduct__c, new Set<String>());
                    }
                    productSetByParentProductIdMap.get(orderItemSummary.Product2.COMM_ParentProduct__c).add(orderItemSummary.Product2Id);
                } else {
                    isRecurring = true;
                    oItemSummaryBySubscriptionNbrMap.put(orderItemSummary.COMM_SubscriptionNumber__c, orderItemSummary);
                }
                orderSummaryByIdMap.put(orderItemSummary.OrderSummaryId, orderItemSummary.OrderSummary);
            } else if (orderItemSummary.Product2.Family == COMM_DO_Product2.CATEGORY_CARD) {
                cardByAirportMap.put(AIRPORT_DEFINITION.get(orderItemSummary.Product2.COMM_Airport__c), orderItemSummary);
            }
        }

        handleSubscriptionAndCaseCreationUpdate(subscriptionsByAirportMap, cardByAirportMap, oItemSummaryBySubscriptionNbrMap, orderSummaryByIdMap, productSetByParentProductIdMap);
    }

    /**
     * @description Get list of Order Item Summary related on a paid Invoice.
     * @param invoiceIdsList List of invoice identifiers to process.
     * @return List of Order Item Summary to process.
     */
    private static List<OrderItemSummary> getOrderItemSummary(List<Id> invoiceIdsList) {
        Map<Id, Invoice> invoiceByIdMap = new Map<Id, Invoice>();
        List<InvoiceLine> invoiceLineList = new List<InvoiceLine>();
        Set<String> orderItemSummaryIdSet = new Set<String>();
        List<OrderItemSummary> orderItemSummaryList = new List<OrderItemSummary>();

        if (invoiceIdsList.isEmpty() || invoiceIdsList == null) {
            return new List<OrderItemSummary>();
        }

        invoiceByIdMap = new Map<Id, Invoice>(invoiceRep.getByIds(invoiceIdsList));

        if (invoiceByIdMap.isEmpty()) {
            return new List<OrderItemSummary>();
        }

        invoiceLineList = invoiceLineRep.getInvoiceLinesByFamilyAndType(invoiceIdsList, PRODUCT_FAMILIES, ENTITY_ITEM_TYPE);

        if (invoiceLineList.isEmpty()) {
            return new List<OrderItemSummary>();
        }

        for (InvoiceLine invoiceLine : invoiceLineList) {
            orderItemSummaryIdSet.add(invoiceLine.ReferenceEntityItemId);
        }

        if (orderItemSummaryIdSet == null) {
            return new List<OrderItemSummary>();
        }

        orderItemSummaryList = orderItemSummaryRep.getOrderItemSummariesById(new List<String>(orderItemSummaryIdSet));

        return orderItemSummaryList;
    }

    /**
     * @description Define List of Subscription records to be created.
     * @param subscriptionsByAirportMap Subscription records by airport definition.
     * @param cardByAirportMap Card product record by airport definition.
     * @return List of Subscription records to be created.
     */
    private static List<COMM_Subscription__c> setSubscriptionsToCreate(
        Map<String, List<COMM_Subscription__c>> subscriptionsByAirportMap,
        Map<String, OrderItemSummary> cardByAirportMap
    ) {
        List<COMM_Subscription__c> subscriptionsToCreateList = new List<COMM_Subscription__c>();

        for (String subscriptionAirport : subscriptionsByAirportMap.keySet()) {
            List<COMM_Subscription__c> subscriptionList = new List<COMM_Subscription__c>();
            if (cardByAirportMap.containsKey(subscriptionAirport)) {
                subscriptionList = subscriptionsByAirportMap.get(subscriptionAirport);
                for (COMM_Subscription__c subscription : subscriptionList) {
                    subscription.COMM_Card__c = cardByAirportMap.get(subscriptionAirport).Product2.Id;
                    subscriptionsToCreateList.add(subscription);
                }
            } else {
                subscriptionsToCreateList.addAll(subscriptionsByAirportMap.get(subscriptionAirport));
            }
        }

        return subscriptionsToCreateList;
    }

    /**
     * @description Define List of Case records to be created.
     * @param subscriptionsToCreateList Subscription records to be created.
     * @param subscriptionsByAirportMap Subscription records by airport definition.
     * @param cardByAirportMap Card product record by airport definition.
     * @param orderSummaryByIdMap Order Summary record by identifier.
     */
    @SuppressWarnings('PMD.ExcessiveParameterList')
    private static List<Case> setCasesToCreate(
        List<COMM_Subscription__c> subscriptionsToCreateList,
        Map<String, OrderItemSummary> cardByAirportMap,
        Map<Id, OrderSummary> orderSummaryByIdMap,
        Map<String, OrderItemSummary> oItemSummaryBySubscriptionNbrMap
    ) {
        List<Case> casesToCreateList = new List<Case>();
        Group sabaQueue = groupRep.getQueueIdByDeveloperName(COMM_DO_Group.QUEUE_NAME_SUBSCRIPTION_SABA, true).get(0);

        for (COMM_Subscription__c subscription : subscriptionsToCreateList) {
            Case caseToCreate = COMM_DO_Case.setCaseToCreate(
                subscription,
                cardByAirportMap,
                orderSummaryByIdMap,
                oItemSummaryBySubscriptionNbrMap,
                isRecurring,
                sabaQueue
            );
            casesToCreateList.add(caseToCreate);
        }

        return casesToCreateList;
    }

    /**
     * @description Handle Subscription and related Case records creation and updates.
     * @param subscriptionsByAirportMap Subscription records by airport definition.
     * @param cardByAirportMap Card product record by airport definition.
     * @param oItemSummaryBySubscriptionNbrMap Order Item Summary record by subscription number.
     * @param orderSummaryByIdMap Order Summary record by identifier.
     */
    @SuppressWarnings('PMD.ExcessiveParameterList')
    private static void handleSubscriptionAndCaseCreationUpdate(
        Map<String, List<COMM_Subscription__c>> subscriptionsByAirportMap,
        Map<String, OrderItemSummary> cardByAirportMap,
        Map<String, OrderItemSummary> oItemSummaryBySubscriptionNbrMap,
        Map<Id, OrderSummary> orderSummaryByIdMap,
        Map<String, Set<String>> productSetByParentProductIdMap
    ) {
        FW_ISObjectRep sObjectRep = new FW_SObjectRep();
        Set<Id> createdCaseIdsSet = new Set<Id>();

        List<COMM_Subscription__c> subscriptionsToCreateList = setSubscriptionsToCreate(subscriptionsByAirportMap, cardByAirportMap);

        setSubscriptionOCIEndateRequest(subscriptionsToCreateList, productSetByParentProductIdMap);

        try {
            sObjectRep.insertSObjects(subscriptionsToCreateList);
        } catch (Exception e) {
            COMM_GEN_Utility.logError(
                e,
                'Public Subscription creation handleSubscriptionAndCaseCreationUpdate error',
                'COMM_SL_PublicSubscriptionCreation'
            );
        }

        List<Case> casesToCreate = setCasesToCreate(
            subscriptionsToCreateList,
            cardByAirportMap,
            orderSummaryByIdMap,
            new Map<String, OrderItemSummary>()
        );

        List<COMM_Subscription__c> existingSubscriptionList = subsriptionRep.getSubscriptionsById(oItemSummaryBySubscriptionNbrMap.keySet());

        if (!existingSubscriptionList.isEmpty()) {
            casesToCreate.addAll(setCasesToCreate(existingSubscriptionList, cardByAirportMap, orderSummaryByIdMap, oItemSummaryBySubscriptionNbrMap));
        }

        try {
            sObjectRep.insertSObjects(casesToCreate);
        } catch (Exception e) {
            COMM_GEN_Utility.logError(
                e,
                'Public Subscription Case creation handleSubscriptionAndCaseCreationUpdate error',
                'COMM_SL_PublicSubscriptionCreation'
            );
        }

        for (Case currentCase : casesToCreate) {
            createdCaseIdsSet.add(currentCase.Id);
        }

        Map<Id, COMM_Subscription__c> subscriptionByIdMap = new Map<Id, COMM_Subscription__c>(subscriptionsToCreateList);

        if (!existingSubscriptionList.isEmpty()) {
            Map<Id, COMM_Subscription__c> existingSubscriptionByIdMap = new Map<Id, COMM_Subscription__c>(existingSubscriptionList);
            subscriptionByIdMap.putAll(existingSubscriptionByIdMap);
        }

        List<COMM_Subscription__c> subscriptionsToUpdateList = setSubscriptionActiveRequest(casesToCreate, subscriptionByIdMap);
        try {
            sObjectRep.updateSObjects(subscriptionsToUpdateList);
        } catch (Exception e) {
            COMM_GEN_Utility.logError(
                e,
                'Public Subscription update handleSubscriptionAndCaseCreationUpdate error',
                'COMM_SL_PublicSubscriptionCreation'
            );
        }
    }

    /**
     * @description Update Subscription with last active Public Subscription request represented by a Case.
     * @param casesToCreateList List of Case records.
     * @param subscriptionByIdMap Subscription records to update.
     */
    private static List<COMM_Subscription__c> setSubscriptionActiveRequest(
        List<Case> casesToCreateList,
        Map<Id, COMM_Subscription__c> subscriptionByIdMap
    ) {
        List<COMM_Subscription__c> subscriptionsToUpdateList = new List<COMM_Subscription__c>();

        for (Case currentCase : casesToCreateList) {
            if (subscriptionByIdMap.containsKey(currentCase.COMM_Subscription__c)) {
                subscriptionByIdMap.get(currentCase.COMM_Subscription__c).COMM_ActiveSubscriptionRequest__c = currentCase.Id;
                if (
                    currentCase.RecordTypeId ==
                    Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
                        .get(COMM_DO_Case.RECURRING_PUBLIC_SUBSCRIPTION_REQUEST_RT)
                        .RecordTypeId
                ) {
                    subscriptionByIdMap.get(currentCase.COMM_Subscription__c).COMM_EndDate__c = currentCase.COMM_EndDate__c;
                }
                subscriptionsToUpdateList.add(subscriptionByIdMap.get(currentCase.COMM_Subscription__c));
            }
        }

        return subscriptionsToUpdateList;
    }

    /**
     * @description Update Subscription OCI End Date and generate stock for the remaining Capacity Valid To Date.
     * @param subscriptionsToCreateList List of Subscription records.
     * @param productSetByParentProductIdMap Map of Child ProductId by Parent Product Id.
     */
    private static void setSubscriptionOCIEndateRequest(
        List<COMM_Subscription__c> subscriptionsToCreateList,
        Map<String, Set<String>> productSetByParentProductIdMap
    ) {
        Map<String, String> parentProductCodeByProductId = new Map<String, String>();
        List<COMM_Capacity__c> capacityList = capacityRep.getCapacityByProductIds(productSetByParentProductIdMap.keySet());
        for(COMM_Subscription__c subscriptionRecord : subscriptionsToCreateList){
            for(COMM_Capacity__c capacityRecord : capacityList){
                if(productSetByParentProductIdMap.get(capacityRecord.COMM_Product__c).contains(subscriptionRecord.COMM_Product__c)){
                    subscriptionRecord.COMM_OCIEndDate__c = capacityRecord.COMM_ValidTo__c.date();
                    parentProductCodeByProductId.put(subscriptionRecord.COMM_Product__c, capacityRecord.COMM_Product__r.ProductCode);
                }
            }
        }
        if(!parentProductCodeByProductId.isEmpty()){
            COMM_WS_ReservationInput input = new COMM_WS_ReservationInput();
            input.expirationSeconds = 0;
            input.product = new List<COMM_WS_ReservationInput.Product>();
            for (COMM_Subscription__c subscriptionRecord : subscriptionsToCreateList) {
                COMM_WS_ReservationInput.Product product = new COMM_WS_ReservationInput.Product();
                product.productId = parentProductCodeByProductId.get(subscriptionRecord.COMM_Product__c);
                product.startDate = COMM_GEN_Utility.generateDateTimeDataType(subscriptionRecord.COMM_EndDate__c).addDays(1);
                product.endDate = COMM_GEN_Utility.generateDateTimeDataType(subscriptionRecord.COMM_OCIEndDate__c);
                input.product.add(product);
            }
            COMM_SL_WS_OCIReservations ociReservation = new COMM_SL_WS_OCIReservations();
            ociReservation.reserve(input, false);
        }
    }
}