force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>To capture all sort of errors</description>
    <label>Error and Log</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors and Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Actor_Name__c.field-meta.xml
<CustomField>
    <fullName>Actor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the actor, this lookup will be populated if the actor Id is a user</description>
    <label>Actor Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Errors_and_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex_Class</fullName>
                <label>Apex Class</label>
            </value>
            <value>
                <fullName>Apex_Trigger</fullName>
                <label>Apex Trigger</label>
            </value>
            <value>
                <fullName>Process_Builder</fullName>
                <label>Process Builder</label>
            </value>
            <value>
                <fullName>HTTP_Callout</fullName>
                <label>HTTP Callout</label>
            </value>
            <value>
                <fullName>HTTP_Inbound</fullName>
                <label>HTTP Inbound</label>
            </value>
            <value>
                <fullName>Platform_Event</fullName>
                <label>Platform Event</label>
            </value>
            <value>
                <fullName>Apex_Batch</fullName>
                <label>Apex Batch</label>
            </value>
            <value>
                <fullName>Log</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Job Execution record, it is filled if the error comes from the Batch Framework</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipName>Error_and_Monitoring_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Job_Scope__c.field-meta.xml
<CustomField>
    <fullName>Job_Scope__c</fullName>
    <description>The Record IDs that are in scope if the event was fired from the execute() method of a batch job. If the batch job uses custom iterators instead of sObjects, JobScope is the toString() representation of the iterable objects. Maximum length is 40000 characters.</description>
    <label>Job Scope</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/StackTraceString__c.field-meta.xml
<CustomField>
    <fullName>StackTraceString__c</fullName>
    <description>Exception stacktracestring</description>
    <label>StackTraceString</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Notification__e/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>To capture error message</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Notification__e/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>Request body for the external/internal callouts</description>
    <label>Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Notification__e/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <description>Response body for the external/internal callouts</description>
    <label>Response Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Notification__e/fields/StackTraceString__c.field-meta.xml
<CustomField>
    <fullName>StackTraceString__c</fullName>
    <description>Error StackTraceString</description>
    <label>StackTraceString</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/FW_SL_ErrorHandling.cls
/**
    * @description   Error Handling Class
    * @testClass     FW_SL_ErrorHandlingTest
    * Modification Log 
	* ------------------------------------------------------------------------------------  
	* Developer                       Date                Description  
    * ------------------------------------------------------------------------------------ 
*/
public class FW_SL_ErrorHandling implements FW_ISL_ErrorHandling {

    @TestVisible
    private List<Error_Log__c> errorListToWrite;
    private FW_IREP_ErrorLog errorRepository;

    //Default Constructor to be used
    public FW_SL_ErrorHandling(){
        errorListToWrite = new List<Error_Log__c>();
        errorRepository = new FW_REP_ErrorLog();
    }

    @TestVisible
    private FW_SL_ErrorHandling(FW_IREP_ErrorLog errorRepository){
        errorListToWrite = new List<Error_Log__c>();
        this.errorRepository = errorRepository;
    }

    /**
        * @description:    Create a log record for a job execution error
    */

    public void writeLog(System_Notification__e event) {
        
        //Create new error record 
        Error_Log__c error = new Error_Log__c();
        error.Actor_Id__c = event.Actor_Id__c;
        error.Record_Id__c = event.Record_Id__c;
        error.Category__c = event.Category__c;
        error.Error_Message__c = event.Error_Message__c;
        error.Exception_Cause__c = event.Exception_Cause__c;
        error.Exception_Line_Number__c = event.Exception_Line_Number__c;
        error.Exception_Type_Name__c = event.Exception_Type_Name__c;
        error.Origin__c = event.Origin__c;
        error.Request_Body__c = event.Request_Body__c;
        error.Response_Body__c = event.Response_Body__c;
        error.StackTraceString__c = event.StackTraceString__c;
        try{
            ID userId = Id.valueOf(event.Actor_Id__c);
            if(userId.getSobjectType() == Schema.User.SObjectType){
                error.Actor_Name__c = userId;
            }
        } catch (Exception e){
            System.debug('Not a Valid ID =' + e);
        }
        errorListToWrite.add(error);
    }

    /**
        * @description:    Create a log record for a job execution error
    */
    public void writeLog(BatchApexErrorEvent event, Id jobId) {
        
        Error_Log__c error = new Error_Log__c();
        error.Job_Execution__c = jobId;
        error.Error_Message__c = event.Message;
        error.StackTraceString__c = event.StackTrace;
        error.Category__c = 'Apex_Batch';
        error.Exception_Type_Name__c = event.ExceptionType;
        error.Job_Scope__c = event.JobScope;
        
        errorListToWrite.add(error);
    }

    /**
        * @description:    Insert a a list of log records
    */
    public void saveLogs() {
        errorRepository.insertSObjects(errorListToWrite);
    }
    
}