force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>To capture all sort of errors</description>
    <label>Error and Log</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors and Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Job Execution record, it is filled if the error comes from the Batch Framework</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipName>Error_and_Monitoring_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FW_REP_ErrorLogTest.cls
@isTest
public class FW_REP_ErrorLogTest {
    @isTest
    static void errorLogRepositoryTest(){
        User runningUser = FW_TestDataFactory.createUsers(1, true, 'System Administrator', null).get(0);
        system.runAs(runningUser){    
            Id batchDefinitionId = FW_TestDataFactory.createBatchDefinition(1, true).get(0).Id;
            List<Job_Execution__c> jobExecutionList = FW_TestDataFactory.createJobExecution(1, true, FW_DO_JobExecution.JOB_EXEC_RECORD_TYPE_INITIAL, batchDefinitionId);
            List<Error_Log__c> errorLogList = FW_TestDataFactory.createErrorLog(1, false);
            errorLogList.get(0).Job_Execution__c = jobExecutionList.get(0).Id;
            insert errorLogList;
            
            test.startTest();
                FW_REP_ErrorLog errorLogRepository = new FW_REP_ErrorLog();
                List<Error_Log__c> errorLogFromJobExecution = errorLogRepository.getErrorLogListByJobExecutionIdSet(new Set<Id>{errorLogList.get(0).Job_Execution__c});
                List<Error_Log__c> errorLogFromId = errorLogRepository.getErrorLogListByIdSet(new Set<id>{errorLogList.get(0).Id});
            test.stopTest();
            
            system.assertEquals(1, errorLogFromJobExecution.size());
            system.assertEquals(1, errorLogFromId.size());
        }
    }
}