force-app/main/default/objects/COMM_ResellerAssortment__c/COMM_ResellerAssortment__c.object-meta.xml
<CustomObject>
    <description>Representes a Reseller Assortment</description>
    <label>Reseller Assortment</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Reseller Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reseller Assortments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_ResellerAssortment__c/fields/COMM_Account__c.field-meta.xml
<CustomField>
    <fullName>COMM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account associated with the assortment</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Assortments</relationshipLabel>
    <relationshipName>ResellerAssortments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_ResellerAssortment__c/fields/COMM_AvailableDailyQuantity__c.field-meta.xml
<CustomField>
    <fullName>COMM_AvailableDailyQuantity__c</fullName>
    <description>The quantity the reseller has available to sell of the Product for the current day</description>
    <formula>COMM_DailyLimit__c -  COMM_CurrentDailyQuantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Daily Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_ResellerAssortment__c/fields/COMM_CurrentDailyQuantity__c.field-meta.xml
<CustomField>
    <fullName>COMM_CurrentDailyQuantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The quantity the reseller has sold of the Product for the current day</description>
    <label>Current Daily Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_ResellerAssortment__c/fields/COMM_DailyLimit__c.field-meta.xml
<CustomField>
    <fullName>COMM_DailyLimit__c</fullName>
    <description>Maximum daily sales limit</description>
    <label>Daily Limit</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_ResellerAssortment__c/fields/COMM_PriceBook__c.field-meta.xml
<CustomField>
    <fullName>COMM_PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reseller price catalog</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Reseller Assortments</relationshipLabel>
    <relationshipName>ResellerAssortments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_ResellerAssortment__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product to be sold by reseller</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Reseller Assortments</relationshipLabel>
    <relationshipName>ResellerAssortments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/COMM_REP_ResellerAssortment.cls
/**
 * @author Diogo Gonçalves
 * @description ResellerAssortment repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Diogo Gonçalves    22/05/2024       Original version
 **/
public inherited sharing class COMM_REP_ResellerAssortment extends FW_SobjectRep implements COMM_IREP_ResellerAssortment {
    /**
     * @description Retrieve a list of ResellerAssortment by product code and reseller account Id
     *              For update of the Daily Count field
     *
     * @param productCodes Set of productCodes to query
     * @param resellerAccountId Id of the reseller account
     * @return List of ResellerAssortment Records found
     **/
    public List<COMM_ResellerAssortment__c> getForStockReserve(Set<String> productCodes, Id resellerAccountId) {
        return [
            SELECT Id, COMM_Product__r.ProductCode, COMM_DailyLimit__c, COMM_CurrentDailyQuantity__c, COMM_AvailableDailyQuantity__c, COMM_PriceBook__c
            FROM COMM_ResellerAssortment__c
            WHERE COMM_Product__r.ProductCode IN :productCodes AND COMM_Account__c = :resellerAccountId
            WITH SECURITY_ENFORCED
            FOR UPDATE
        ];
    }
}