force-app/main/default/objects/Pricebook2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date and hour for which the price is valid</description>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the price is valid date for which the product is deemed valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of Price Book used (Public or Reseller)</description>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_First15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_First15MinuteUnit__c</fullName>
    <description>The price applied during the first 15 minutes</description>
    <label>First 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FirstPeriodDailyMaximum__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstPeriodDailyMaximum__c</fullName>
    <description>The First Period Daily Maximum value aplied to the days defined between that period</description>
    <label>First Period Daily Maximum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FirstPeriodEndDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstPeriodEndDay__c</fullName>
    <description>The day the first Period&apos;s price stops being applied</description>
    <label>First Period End Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FirstPeriodStartDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstPeriodStartDay__c</fullName>
    <description>The day the first Period&apos;s price starts to be applied</description>
    <label>First Period Start Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FourthPeriodDailyMaximum__c.field-meta.xml
<CustomField>
    <fullName>COMM_FourthPeriodDailyMaximum__c</fullName>
    <description>The Fourth Period Daily Maximum value applied to the days defined between that period</description>
    <label>Fourth Period Daily Maximum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FourthPeriodEndDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_FourthPeriodEndDay__c</fullName>
    <description>The day the fourth Period&apos;s price stops being applied</description>
    <label>Fourth Period End Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FourthPeriodStartDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_FourthPeriodStartDay__c</fullName>
    <description>The day the fourth Period&apos;s price starts to be applied</description>
    <label>Fourth Period Start Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Remaining15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Remaining15MinuteUnit__c</fullName>
    <description>The price applied during the remaining 15 minutes</description>
    <label>Remaining 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Second15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Second15MinuteUnit__c</fullName>
    <description>The price applied during the second 15 minutes</description>
    <label>Second 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_SecondPeriodDailyMaximum__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondPeriodDailyMaximum__c</fullName>
    <description>The Second Period Daily Maximum value applied to the days defined between that period</description>
    <label>Second Period Daily Maximum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_SecondPeriodEndDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondPeriodEndDay__c</fullName>
    <description>The day the second Period&apos;s price stops being applied</description>
    <label>Second Period End Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_SecondPeriodStartDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondPeriodStartDay__c</fullName>
    <description>The day the second Period&apos;s price starts to be applied</description>
    <label>Second Period Start Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Third15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Third15MinuteUnit__c</fullName>
    <description>The price applied during the third 15 minutes</description>
    <label>Third 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_ThirdPeriodDailyMaximum__c.field-meta.xml
<CustomField>
    <fullName>COMM_ThirdPeriodDailyMaximum__c</fullName>
    <description>The Third Period Daily Maximum value applied to the days defined between that period</description>
    <label>Third Period Daily Maximum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_ThirdPeriodEndDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_ThirdPeriodEndDay__c</fullName>
    <description>The day the third Period&apos;s price stops being applied</description>
    <label>Third Period End Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_ThirdPeriodStartDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_ThirdPeriodStartDay__c</fullName>
    <description>The day the third Period&apos;s price starts to be applied</description>
    <label>Third Period Start Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <description>Defines the periodicity of the subscription</description>
    <label>Subscription Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubCategory__c</fullName>
    <description>Used to define the sub-category of the product.</description>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Park</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Fast Lane</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Exempt Official Entity</fullName>
            </value>
            <value>
                <fullName>ANA + Entities</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>RAC / Shuttle NL</fullName>
            </value>
            <value>
                <fullName>Staff Company</fullName>
            </value>
            <value>
                <fullName>Staff Individual</fullName>
            </value>
            <value>
                <fullName>Fast Track Plus</fullName>
            </value>
            <value>
                <fullName>Lounge Adult</fullName>
            </value>
            <value>
                <fullName>Lounge Child</fullName>
            </value>
            <value>
                <fullName>Lounge Adult with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Child with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Non Schengen</fullName>
            </value>
            <value>
                <fullName>Terminal</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non -Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Adult Non -Schengen</label>
            </value>
            <value>
                <fullName>Lounge Child Non - Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Child Non - Schengen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Tax__c.field-meta.xml
<CustomField>
    <fullName>COMM_Tax__c</fullName>
    <description>Defines the tax used for the product based on location</description>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>COMM_Airport__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continent</fullName>
            </value>
            <value>
                <fullName>Madeira</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date for which the product is deemed valid</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_REP_PricebookEntry.cls
/**
 * @author Ricardo Dias
 * @description Pricebook Entry repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date                Description
 * -----------------------------------------------------------------------------------
 * Ricardo Dias     23/02/2024          Original version
 * Ricardo Dias     08/04/2024          Update getPBEByProductCodeList where clause
 * Daniel Lascas    10/04/2024          ECOMM-194: Added getCardPBEByIds method
 * Daniel Reto      01/05/2024          ECOMM-997: Added getPBEByProductCodeDataBaseQueryList method
 * Daniel Reto      29/05/2024          PDM warning messages fix
 **/
public inherited sharing class COMM_REP_PricebookEntry extends FW_SobjectRep implements COMM_IREP_PricebookEntry {
    public static final String publicType = COMM_GEN_Utility.TYPE_PUBLIC;

    /**
     * @description Retrieve a list of Valid(Valid From <= NOW AND Valid To >= NOW) Active Pricebook Entries by a set of Product Codes
     *
     * @param productCodesSet Set of Product Codes to query
     * @return List of Pricebook Entry Records found
     **/
    public List<PricebookEntry> getPBEByProductCodeList(Set<String> productCodesSet) {
        return [
            SELECT
                Id,
                ProductCode,
                Pricebook2.Id,
                Pricebook2.IsStandard,
                Pricebook2.Name,
                UnitPrice,
                Product2Id,
                Pricebook2.COMM_ValidFrom__c,
                Pricebook2.COMM_ValidTo__c,
                Product2.COMM_Tax__c,
                Product2.Family,
                Product2.Name,
                Product2.COMM_Periodicity__c,
                Product2.ProductCode,
                Product2.COMM_SubCategory__c,
                Product2.COMM_Airport__c,
                Pricebook2Id,
                COMM_First15MinuteUnit__c,
                COMM_Second15MinuteUnit__c,
                COMM_Third15MinuteUnit__c,
                COMM_Remaining15MinuteUnit__c,
                COMM_FirstPeriodStartDay__c,
                COMM_FirstPeriodEndDay__c,
                COMM_FirstPeriodDailyMaximum__c,
                COMM_SecondPeriodStartDay__c,
                COMM_SecondPeriodEndDay__c,
                COMM_SecondPeriodDailyMaximum__c,
                COMM_ThirdPeriodStartDay__c,
                COMM_ThirdPeriodEndDay__c,
                COMM_ThirdPeriodDailyMaximum__c,
                COMM_FourthPeriodStartDay__c,
                COMM_FourthPeriodEndDay__c,
                COMM_FourthPeriodDailyMaximum__c
            FROM PricebookEntry
            WHERE
                ProductCode IN :productCodesSet
                AND IsActive = TRUE
                AND Pricebook2.Type__c INCLUDES (:COMM_GEN_Utility.TYPE_PUBLIC)
                AND Pricebook2.IsActive = TRUE
                AND Pricebook2.COMM_ValidFrom__c <= :system.now()
                AND Pricebook2.COMM_ValidTo__c >= :system.now()
            WITH USER_MODE
            ORDER BY Pricebook2.IsStandard ASC, Pricebook2.COMM_ValidFrom__c DESC
        ];
    }

    /**
     * @description Retrieve a list of Valid(Valid From <= NOW AND Valid To >= NOW) Active Pricebook Entries by a set of Product Codes and Pricebooks
     *
     * @param productCodesSet Set of Product Codes to query
     * @param pricebookIdSet Set of Pricebook Ids to query
     * @return List of Pricebook Entry Records found
     **/
    public List<PricebookEntry> getPBEByProductCodeList(Set<String> productCodesSet, Set<Id> pricebookIdSet) {
        return [
            SELECT
                Id,
                ProductCode,
                Pricebook2.Id,
                Pricebook2.IsStandard,
                Pricebook2.Name,
                UnitPrice,
                Product2Id,
                Pricebook2.COMM_ValidFrom__c,
                Pricebook2.COMM_ValidTo__c,
                Product2.COMM_Tax__c,
                Product2.Family,
                Product2.Name,
                Product2.COMM_Periodicity__c,
                Product2.ProductCode,
                Product2.COMM_SubCategory__c,
                Product2.COMM_Airport__c,
                Pricebook2Id,
                COMM_First15MinuteUnit__c,
                COMM_Second15MinuteUnit__c,
                COMM_Third15MinuteUnit__c,
                COMM_Remaining15MinuteUnit__c,
                COMM_FirstPeriodStartDay__c,
                COMM_FirstPeriodEndDay__c,
                COMM_FirstPeriodDailyMaximum__c,
                COMM_SecondPeriodStartDay__c,
                COMM_SecondPeriodEndDay__c,
                COMM_SecondPeriodDailyMaximum__c,
                COMM_ThirdPeriodStartDay__c,
                COMM_ThirdPeriodEndDay__c,
                COMM_ThirdPeriodDailyMaximum__c,
                COMM_FourthPeriodStartDay__c,
                COMM_FourthPeriodEndDay__c,
                COMM_FourthPeriodDailyMaximum__c
            FROM PricebookEntry
            WHERE
                ProductCode IN :productCodesSet
                AND IsActive = TRUE
                AND Pricebook2Id IN: pricebookIdSet
                AND Pricebook2.Type__c INCLUDES (:COMM_GEN_Utility.TYPE_RESELLER)
                AND Pricebook2.IsActive = TRUE
                AND Pricebook2.COMM_ValidFrom__c <= :system.now()
                AND Pricebook2.COMM_ValidTo__c >= :system.now()
            WITH USER_MODE
            ORDER BY Pricebook2.IsStandard ASC, Pricebook2.COMM_ValidFrom__c DESC
        ];
    }

    /**
     * @description Retrieve a list of Active Pricebook Entries for Card Products by a set of Ids
     *
     * @param cardProductIds Set of Card Product Ids to query
     * @return List of Pricebook Entry Records found for Card Products
     **/
    public List<PricebookEntry> getCardPBEByIds(Set<Id> cardProductIds) {
        return [
            SELECT Id, UnitPrice, Product2Id
            FROM PricebookEntry
            WHERE
                Product2Id IN :cardProductIds
                AND Product2.Family = :COMM_DO_Product2.CATEGORY_CARD
                AND IsActive = TRUE
                AND Pricebook2.IsActive = TRUE
                AND Pricebook2.IsStandard = TRUE
            WITH USER_MODE
        ];
    }

    /**
     * @description Retrieve a list of Valid(Valid From <= NOW AND Valid To >= NOW) Active Pricebook Entries by a set of Product Codes
     * using Database.query()
     *
     * @param productCodesSet Set of Product Codes to query
     * @return List of Pricebook Entry Records found
     **/
    public List<PricebookEntry> getPBEByProductCodeDataBaseQueryList(Set<String> productCodesSet) {
        String query =
            'SELECT ' +
            'Id, ' +
            'COMM_FirstPeriodStartDay__c, ' +
            'COMM_FirstPeriodEndDay__c, ' +
            'COMM_FirstPeriodDailyMaximum__c, ' +
            'COMM_SecondPeriodStartDay__c, ' +
            'COMM_SecondPeriodEndDay__c, ' +
            'COMM_SecondPeriodDailyMaximum__c, ' +
            'COMM_ThirdPeriodStartDay__c, ' +
            'COMM_ThirdPeriodEndDay__c, ' +
            'COMM_ThirdPeriodDailyMaximum__c, ' +
            'COMM_FourthPeriodStartDay__c, ' +
            'COMM_FourthPeriodEndDay__c, ' +
            'COMM_FourthPeriodDailyMaximum__c, ' +
            'COMM_First15MinuteUnit__c, ' +
            'COMM_Second15MinuteUnit__c, ' +
            'COMM_Third15MinuteUnit__c, ' +
            'COMM_Remaining15MinuteUnit__c, ' +
            'Pricebook2.Id, ' +
            'Pricebook2.IsStandard, ' +
            'Pricebook2.Name, ' +
            'Product2Id, ' +
            'Product2.COMM_Periodicity__c, ' +
            'toLabel(Product2.COMM_Periodicity__c) productPeriodicityLabel, ' +
            'Product2.Family, ' +
            'Product2.Name, ' +
            'ProductCode, ' +
            'UnitPrice ' +
            'FROM ' +
            'PricebookEntry ' +
            'WHERE ' +
            'ProductCode IN :productCodesSet ' +
            'AND IsActive = TRUE ' +
            'AND Pricebook2.Type__c = :publicType ' +
            'AND Pricebook2.IsActive = TRUE ' +
            'AND Pricebook2.COMM_ValidFrom__c <= ' +
            system.now().format('yyyy-MM-dd\'T\'HH:mm:ssXXX') +
            ' AND Pricebook2.COMM_ValidTo__c >= ' +
            system.now().format('yyyy-MM-dd\'T\'HH:mm:ssXXX') +
            ' WITH USER_MODE ' +
            'ORDER BY Pricebook2.IsStandard ASC, Pricebook2.COMM_ValidFrom__c DESC';

        return (List<PricebookEntry>) Database.query(String.escapeSingleQuotes(query));
    }

    /**
     * @description Retrieve a list of Pricebook Entries by a set of Product Ids and Pricebook Ids
     *
     * @param productIds Set of Product Ids to query
     * @param pricebookIds Set of Pricebook Ids to query
     * @return List of Pricebook Entry Records found
     **/
    public List<PricebookEntry> getPBEByProductAndPricebookIds(Set<Id> productIds, Set<Id> pricebookIds) {
        return [
            SELECT
                Id,
                UnitPrice,
                Product2Id,
                Product2.Family,
                ProductCode,
                Pricebook2Id,
                Pricebook2.IsStandard,
                COMM_First15MinuteUnit__c,
                COMM_Second15MinuteUnit__c,
                COMM_Third15MinuteUnit__c,
                COMM_Remaining15MinuteUnit__c,
                COMM_FirstPeriodStartDay__c,
                COMM_FirstPeriodEndDay__c,
                COMM_FirstPeriodDailyMaximum__c,
                COMM_SecondPeriodStartDay__c,
                COMM_SecondPeriodEndDay__c,
                COMM_SecondPeriodDailyMaximum__c,
                COMM_ThirdPeriodStartDay__c,
                COMM_ThirdPeriodEndDay__c,
                COMM_ThirdPeriodDailyMaximum__c,
                COMM_FourthPeriodStartDay__c,
                COMM_FourthPeriodEndDay__c,
                COMM_FourthPeriodDailyMaximum__c
            FROM PricebookEntry
            WHERE Product2Id IN :productIds AND Pricebook2Id IN :pricebookIds
            WITH USER_MODE
        ];
    }
}