force-app/main/default/objects/COMM_CustomerUpdateRequest__e/COMM_CustomerUpdateRequest__e.object-meta.xml
<CustomObject>
    <description>Platform Event used to send Customer Updates Callouts to Commerce</description>
    <label>Customer Update Request</label>
    <pluralLabel>Customer Update Requests</pluralLabel>
</CustomObject>

force-app/main/default/objects/COMM_CustomerUpdateRequest__e/fields/COMM_ContactId__c.field-meta.xml
<CustomField>
    <fullName>COMM_ContactId__c</fullName>
    <description>Id of the Contact whose data is to be sent to Commerce</description>
    <label>Contact Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_IntegrationRequestBody__c.field-meta.xml
<CustomField>
    <fullName>COMM_IntegrationRequestBody__c</fullName>
    <description>To set Customer Data integration body request detail in JSON format, for integration in Salesforce Commerce.</description>
    <label>Integration Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_SetForCommerceIntegration__c.field-meta.xml
<CustomField>
    <fullName>COMM_SetForCommerceIntegration__c</fullName>
    <description>Formula to indicate if Account is an Affiliate. Used to check if Commerce integration is used.</description>
    <formula>Account.COMM_IsAffiliate__c</formula>
    <label>Set for Commerce Integration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/COMM_TW_Contact_CustomerSyncWithCommerce.cls
/**
 * @author Daniel Lascas
 * @description Trigger worker that verifies if one of the fields that is synched
 * with Commerce was changed. If it was then build an update request body and calls
 * Queueable Class to send update callout.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    08/07/2024		ECOMM-1637: Original version
 **/
public class COMM_TW_Contact_CustomerSyncWithCommerce {
    private COMM_IDO_CustomerSyncMapping mappingSync;

    /**
     * @description Class Constructor to initialize Mapping
     */
    public COMM_TW_Contact_CustomerSyncWithCommerce() {
        this.mappingSync = new COMM_DO_CustomerSyncMapping();
    }

    @TestVisible
    private COMM_TW_Contact_CustomerSyncWithCommerce(COMM_IDO_CustomerSyncMapping mappingSync) {
        this.mappingSync = mappingSync;
    }

    /**
     * @description Execute Trigger Worker Logic.
     *
     * @param newContactList List with the Contact Records in after context.
     * @param oldContactMap Map with the Contact Records in before context.
     */
    public void execute(List<Contact> newContactList, Map<Id, Contact> oldContactMap) {
        Set<String> fieldSet = mappingSync.getCoreFieldList(String.valueOf(Contact.sObjectType), false);
        List<COMM_CustomerUpdateRequest__e> customerUpdateRequestList = new List<COMM_CustomerUpdateRequest__e>();
        for (Contact newContact : newContactList) {
            if (newContact.COMM_SetForCommerceIntegration__c) {
                //Verify for each updated Contact if field used in Sync was changed
                for (String fieldName : fieldSet) {
                    //If Synched Field changed update JSON map and jump to next record.
                    if (COMM_GEN_Utility.isChangedField(newContact, oldContactMap.get(newContact.Id), fieldName)) {
                        Map<String, Object> jsonMap = new Map<String, Object>();
                        mappingSync.mapJsonFromSObject(newContact, jsonMap, false);
                        newContact.COMM_IntegrationRequestBody__c = JSON.serialize(jsonMap);
                        //Generate Event to send Update Call to Commerce
                        COMM_CustomerUpdateRequest__e event = new COMM_CustomerUpdateRequest__e();
                        event.COMM_ContactId__c = newContact.Id;
                        customerUpdateRequestList.add(event);
                        break;
                    }
                }
            }
        }
        if (!customerUpdateRequestList.isEmpty()) {
            EventBus.publish(customerUpdateRequestList);
        }
    }
}