force-app/main/default/objects/COMM_Subscription__c/COMM_Subscription__c.object-meta.xml
<CustomObject>
    <description>Object to represent a Subscription associated with a Client</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SBS-{0000}</displayFormat>
        <label>Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport the Subscription is associated with</description>
    <formula>CASE(COMM_Product__r.COMM_Airport__c,
&quot;OPO&quot;, &quot;Porto&quot;,
&quot;LIS&quot;,&quot;Lisbon&quot;,
&quot;FAO&quot;,&quot;Faro&quot;,
&quot;FNC&quot;,&quot;Madeira&quot;,
&quot;PDL&quot;,&quot;Ponta Delgada&quot;,
&quot;&quot;)</formula>
    <label>Airport</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_AirportValue__c.field-meta.xml
<CustomField>
    <fullName>COMM_AirportValue__c</fullName>
    <description>Field used on Sharing Rules. Due multi-picklist limitation.</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product the Subscription is associated with</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Subscription can only be associated with a Subscription Product</errorMessage>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>COMM_Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/COMM_TW_Product_AirportUpdate.cls
/**
 * @author Daniel Lascas
 * @description Trigger worker that verifies if the picklist COMM_Airport__c
 * was changed. If it was update airport field in all related subscriptions
 * in order to update sharing.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    11/07/2024		ECOMM-1602: CR-33
 **/
public with sharing class COMM_TW_Product_AirportUpdate {
    private COMM_IREP_Subscription subscriptionRep;

    /**
     * @description Class constructor to initialize REP
     */
    public COMM_TW_Product_AirportUpdate() {
        this.subscriptionRep = new COMM_REP_Subscription();
    }

    @TestVisible
    private COMM_TW_Product_AirportUpdate(COMM_IREP_Subscription subscriptionRep) {
        this.subscriptionRep = subscriptionRep;
    }

    /**
     * @description Execute Trigger Worker Logic.
     *
     * @param newProductList List with the Product2 Records in after context.
     * @param oldProductMap Map with the Product2 Records in before context.
     */
    public void execute(List<Product2> newProductList, Map<Id, Product2> oldProductMap) {
        Map<Id, String> airportUpdateValueMap = new Map<Id, String>();

        for (Product2 newProduct : newProductList) {
            //Verify Airport Field Changed
            if (
                COMM_GEN_Utility.isChangedField(newProduct, oldProductMap, Product2.COMM_Airport__c) &&
                COMM_DO_Product2.CATEGORY_SUBSCRIPTION.equals(newProduct.Family)
            ) {
                airportUpdateValueMap.put(newProduct.Id, newProduct.COMM_Airport__c);
            }
        }

        if (!airportUpdateValueMap.isEmpty()) {
            List<COMM_Subscription__c> subsUpdateList = new List<COMM_Subscription__c>();
            //Verify Related Subscriptions and set them to update airport field
            for (COMM_Subscription__c subRecord : subscriptionRep.getSubscriptionsByProductIds(airportUpdateValueMap.keySet())) {
                subRecord.COMM_AirportValue__c = airportUpdateValueMap.get(subRecord.COMM_Product__c);
                subsUpdateList.add(subRecord);
            }
            if (!subsUpdateList.isEmpty()) {
                subscriptionRep.updateSObjects(subsUpdateList);
            }
        }
    }
}