force-app/main/default/objects/COMM_Subscription__c/COMM_Subscription__c.object-meta.xml
<CustomObject>
    <description>Object to represent a Subscription associated with a Client</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SBS-{0000}</displayFormat>
        <label>Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport the Subscription is associated with</description>
    <formula>CASE(COMM_Product__r.COMM_Airport__c,
&quot;OPO&quot;, &quot;Porto&quot;,
&quot;LIS&quot;,&quot;Lisbon&quot;,
&quot;FAO&quot;,&quot;Faro&quot;,
&quot;FNC&quot;,&quot;Madeira&quot;,
&quot;PDL&quot;,&quot;Ponta Delgada&quot;,
&quot;&quot;)</formula>
    <label>Airport</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_AirportValue__c.field-meta.xml
<CustomField>
    <fullName>COMM_AirportValue__c</fullName>
    <description>Field used on Sharing Rules. Due multi-picklist limitation.</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product the Subscription is associated with</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Subscription can only be associated with a Subscription Product</errorMessage>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>COMM_Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/COMM_TW_Product_AirportUpdateTest.cls
/**
 * @author           Daniel Lascas
 * @description      COMM_TW_Product_AirportUpdate test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    11/07/2024      100            ECOMM-1602: Original version
 **/
@isTest
private class COMM_TW_Product_AirportUpdateTest {
    private final static fflib_ApexMocks MOCKS = new fflib_ApexMocks();
    private final static COMM_IREP_Subscription SUBSCRIPTION_REP = (COMM_REP_Subscription) MOCKS.mock(COMM_REP_Subscription.class);

    @isTest
    static void updateAirportFieldTest() {
        //Scenario:	Product's Airport field was Updated.
        //Expected: Related Subscription's Aiport Field was set for update.

        //Generate mocked Product
        Product2 oldProduct = (Product2) COMM_TestDataFactory.insertRecords(
            1,
            false,
            'Product2',
            new Map<String, Object>{
                'Id' => fflib_IdGenerator.generate(Product2.sObjectType),
                'Family' => COMM_DO_Product2.CATEGORY_SUBSCRIPTION,
                'COMM_Airport__c' => 'LIS'
            }
        )[0];

        //Mocked Update where Airport is changed
        Product2 newProduct = oldProduct.clone(true);
        newProduct.COMM_Airport__c = 'OPO';

        //Generate mocked Subscription
        List<COMM_Subscription__c> subscriptionList = (List<COMM_Subscription__c>) COMM_TestDataFactory.insertRecords(
            1,
            false,
            'COMM_Subscription__c',
            new Map<String, Object>{
                'Id' => fflib_IdGenerator.generate(COMM_Subscription__c.sObjectType),
                'COMM_Product__c' => oldProduct.Id,
                'COMM_AirportValue__c' => oldProduct.COMM_Airport__c
            }
        );

        Map<Id, Product2> oldProductMap = new Map<Id, Product2>{ oldProduct.Id => oldProduct };
        List<Product2> newProductList = new List<Product2>{ newProduct };

        //Mock REP Calls
        MOCKS.startStubbing();
        MOCKS.when(SUBSCRIPTION_REP.getSubscriptionsByProductIds((Set<Id>) fflib_Match.anyObject())).thenReturn(subscriptionList);
        MOCKS.when(SUBSCRIPTION_REP.updateSObjects((List<COMM_Subscription__c>) fflib_Match.anyList())).thenReturn(new List<Database.SaveResult>());
        MOCKS.stopStubbing();

        Test.startTest();
        COMM_TW_Product_AirportUpdate worker = new COMM_TW_Product_AirportUpdate();
        worker = new COMM_TW_Product_AirportUpdate(SUBSCRIPTION_REP);
        worker.execute(newProductList, oldProductMap);
        Test.stopTest();

        ((COMM_IREP_Subscription) mocks.verify(SUBSCRIPTION_REP, 1)).updateSObjects(subscriptionList);
        Assert.areEqual(
            newProduct.COMM_Airport__c,
            subscriptionList[0].COMM_AirportValue__c,
            'expected subscription to be updated with Product airport'
        );
    }
}