force-app/main/default/objects/COMM_Capacity__c/COMM_Capacity__c.object-meta.xml
<CustomObject>
    <description>The available capacity for a given Product</description>
    <label>Capacity</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Active__c.field-meta.xml
<CustomField>
    <fullName>COMM_Active__c</fullName>
    <description>Determine if Record is Active</description>
    <formula>COMM_ValidTo__c &gt; NOW()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Capacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Capacity__c</fullName>
    <description>It is the daily capacity set by hour, that is constant throughout the operating hours.

This capacity configuration is not applicable to subscriptions.

For the subscriptions, the capacity is calculated by multiplying the total number of parking spaces by the multiplier. This capacity is constant, therefore is not defined by hour.</description>
    <inlineHelpText>To put the product as suspended, changed capacity to 0.</inlineHelpText>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_IsDefaultCapacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_IsDefaultCapacity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if Record is to be used as the Default Capacity for the associated Product</description>
    <label>Is Default Capacity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>COMM_ProcessStatus__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT PROCESSED</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>FAILED</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>RUNNING</fullName>
                <label>Running</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the capacity for specific period of times will be applied</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>For Subscription, product must also be subscription.
For Capacity, product must also be a non-subscription</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Capacity</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>notEqual</operation>
            <value>Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Capacities</relationshipLabel>
    <relationshipName>Capacities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date and hour for which the capacity is valid</description>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the capacity is valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/COMM_ProductReadiness__c/COMM_ProductReadiness__c.object-meta.xml
<CustomObject>
    <description>Responsible to score the status of the product configuration and identify which information is missing</description>
    <label>Product Readiness</label>
    <nameField>
        <label>Product Readiness Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Readiness</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date and hour for which the price is valid</description>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the price is valid date for which the product is deemed valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_First15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_First15MinuteUnit__c</fullName>
    <description>The price applied during the first 15 minutes</description>
    <label>First 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FirstPeriodDailyMaximum__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstPeriodDailyMaximum__c</fullName>
    <description>The First Period Daily Maximum value aplied to the days defined between that period</description>
    <label>First Period Daily Maximum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FirstPeriodEndDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstPeriodEndDay__c</fullName>
    <description>The day the first Period&apos;s price stops being applied</description>
    <label>First Period End Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FirstPeriodStartDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstPeriodStartDay__c</fullName>
    <description>The day the first Period&apos;s price starts to be applied</description>
    <label>First Period Start Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Remaining15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Remaining15MinuteUnit__c</fullName>
    <description>The price applied during the remaining 15 minutes</description>
    <label>Remaining 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Second15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Second15MinuteUnit__c</fullName>
    <description>The price applied during the second 15 minutes</description>
    <label>Second 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Third15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Third15MinuteUnit__c</fullName>
    <description>The price applied during the third 15 minutes</description>
    <label>Third 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_HasUpdateForCommerce__c.field-meta.xml
<CustomField>
    <fullName>COMM_HasUpdateForCommerce__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To flag if a Product record has an update to be sent to Salesforce Commerce.</description>
    <label>Has update for Commerce?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_IsIntegratedInCommerce__c.field-meta.xml
<CustomField>
    <fullName>COMM_IsIntegratedInCommerce__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To flag if a Product record is integrated in Salesforce Commerce.</description>
    <label>Is Integrated in Commerce?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Product for the Product Record</description>
    <label>Parent Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Airport needs to be the same in both Parent and Child Product</errorMessage>
        <filterItems>
            <field>Product2.COMM_Airport__c</field>
            <operation>equals</operation>
            <valueField>$Source.COMM_Airport__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date for which the product is deemed valid</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_Async_ProductValidation.cls
/**
 * @author Ruben Rodrigues
 * @description Batch class to create records on the Product Readiness SObject based on rules defined on the Product Setting SObject.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Description
 * -----------------------------------------------------------------------------------
 * Ruben Rodrigues 09/04/2024      Original version
 **/
public with sharing class COMM_Async_ProductValidation extends FW_AsyncHandler implements Database.Batchable<sObject>, Database.Stateful {
    private FW_ISObjectRep sObjectRep;
    private COMM_SL_ProductValidation productValidationSl;

    public static final List<SObjectField> PRODUCT_FIELDS = new List<SObjectField>{
        Product2.Id,
        Product2.Family,
        Product2.IsActive,
        Product2.COMM_ValidFrom__c,
        Product2.COMM_ValidTo__c,
        Product2.COMM_IsIntegratedInCommerce__c,
        Product2.COMM_HasUpdateForCommerce__c,
        Product2.COMM_ParentProduct__c,
        Product2.ProductCode
    };

    /**
     * @description Class Constructor to initialize REP class
     */
    public COMM_Async_ProductValidation() {
        this.sObjectRep = new FW_SObjectRep();
        this.productValidationSl = new COMM_SL_ProductValidation();
    }

    @testVisible
    private COMM_Async_ProductValidation(
        FW_ISObjectRep sObjectRep,
        COMM_SL_ProductValidation productValidationSl,
        FW_IREP_JobExecution jobExecutionRep,
        FW_IREP_Parameters parameterRep
    ) {
        this.sObjectRep = sObjectRep;
        this.productValidationSl = productValidationSl;
        this.jobExecutionRep = jobExecutionRep;
        this.parameterRep = parameterRep;
    }

    /**
     * @description Batch Start Method. Initiates query to obtain all Product records.
     *
     * @param bc Context Information of the executed batch
     * @return Database.QueryLocator with the built query
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        setAsyncApexJobId(bc.getJobId());

        //Build Query. Retrieve Products and their respective Pricebook Entries and Capacities.
        //@example SELECT Id,Family,IsActive,COMM_ValidFrom__c,COMM_ValidTo__c,COMM_IsIntegratedInCommerce__c,COMM_HasUpdateForCommerce__c,
        //COMM_ParentProduct__c,ProductCode,(SELECT Id,UnitPrice,COMM_First15MinuteUnit__c,COMM_Second15MinuteUnit__c,COMM_Third15MinuteUnit__c,
        //COMM_Remaining15MinuteUnit__c,COMM_FirstPeriodStartDay__c,COMM_FirstPeriodEndDay__c,COMM_FirstPeriodDailyMaximum__c,
        //Pricebook2.IsStandard FROM PricebookEntries WHERE IsActive = true),(SELECT Id FROM Capacities__r
        //WHERE COMM_Active__c = true AND COMM_IsDefaultCapacity__c = true AND COMM_ProcessStatus__c in ('COMPLETED','PENDING')) FROM Product2
        FW_QueryBuilder query = new FW_QueryBuilder(Product2.sObjectType)
            .selectFields(PRODUCT_FIELDS)
            .selectSubquery(
                'PricebookEntries',
                new List<SObjectField>{
                    PricebookEntry.Id,
                    PricebookEntry.UnitPrice,
                    PricebookEntry.COMM_First15MinuteUnit__c,
                    PricebookEntry.COMM_Second15MinuteUnit__c,
                    PricebookEntry.COMM_Third15MinuteUnit__c,
                    PricebookEntry.COMM_Remaining15MinuteUnit__c,
                    PricebookEntry.COMM_FirstPeriodStartDay__c,
                    PricebookEntry.COMM_FirstPeriodEndDay__c,
                    PricebookEntry.COMM_FirstPeriodDailyMaximum__c
                }
            )
            .selectParentFields(PricebookEntry.Pricebook2Id, new List<SObjectField>{ Pricebook2.IsStandard })
            .whereEquals(PricebookEntry.IsActive, true)
            .getParent()
            .selectSubquery('Capacities__r', new List<SObjectField>{ COMM_Capacity__c.Id })
            .whereEquals(COMM_Capacity__c.COMM_Active__c, true)
            .whereEquals(COMM_Capacity__c.COMM_IsDefaultCapacity__c, true)
            .whereIn(
                COMM_Capacity__c.COMM_ProcessStatus__c,
                new List<String>{ COMM_DO_Capacity.PROCESS_STATUS_COMPLETED, COMM_DO_Capacity.PROCESS_STATUS_PENDING }
            )
            .getParent();

        return executeQuery(query);
    }

    /**
     * @description Batch Execute Method.
     *
     * @param bc Context Information of the executed batch
     * @param controllerList List of Product2 Records to verify validation
     */
    public void execute(Database.BatchableContext bc, List<Product2> records) {
        //Call SL Class to obtain Product Readiness Records
        List<COMM_ProductReadiness__c> prList = productValidationSl.verifyReadiness(records);

        if (!prList.isEmpty()) {
            sObjectRep.upsertSObjects(prList, COMM_ProductReadiness__c.Name);
        }
    }

    /**
     * @description Batch Finish Method. Initiates the Framework batch finished process.
     *
     * @param bc Context Information of the executed batch
     */
    public void finish(Database.BatchableContext bc) {
        finishBatch(bc.getJobId());
    }
}