force-app/main/default/objects/COMM_Capacity__c/COMM_Capacity__c.object-meta.xml
<CustomObject>
    <description>The available capacity for a given Product</description>
    <label>Capacity</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Capacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Capacity__c</fullName>
    <description>It is the daily capacity set by hour, that is constant throughout the operating hours.

This capacity configuration is not applicable to subscriptions.

For the subscriptions, the capacity is calculated by multiplying the total number of parking spaces by the multiplier. This capacity is constant, therefore is not defined by hour.</description>
    <inlineHelpText>To put the product as suspended, changed capacity to 0.</inlineHelpText>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_IsDefaultCapacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_IsDefaultCapacity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if Record is to be used as the Default Capacity for the associated Product</description>
    <label>Is Default Capacity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>COMM_ProcessStatus__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT PROCESSED</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>FAILED</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>RUNNING</fullName>
                <label>Running</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the capacity for specific period of times will be applied</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>For Subscription, product must also be subscription.
For Capacity, product must also be a non-subscription</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Capacity</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>notEqual</operation>
            <value>Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Capacities</relationshipLabel>
    <relationshipName>Capacities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date and hour for which the capacity is valid</description>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the capacity is valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/COMM_ProductReadiness__c/COMM_ProductReadiness__c.object-meta.xml
<CustomObject>
    <description>Responsible to score the status of the product configuration and identify which information is missing</description>
    <label>Product Readiness</label>
    <nameField>
        <label>Product Readiness Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Readiness</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_ProductReadiness__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Readiness</relationshipLabel>
    <relationshipName>Products_Readiness</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date and hour for which the price is valid</description>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the price is valid date for which the product is deemed valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_First15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_First15MinuteUnit__c</fullName>
    <description>The price applied during the first 15 minutes</description>
    <label>First 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FirstPeriodStartDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstPeriodStartDay__c</fullName>
    <description>The day the first Period&apos;s price starts to be applied</description>
    <label>First Period Start Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Remaining15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Remaining15MinuteUnit__c</fullName>
    <description>The price applied during the remaining 15 minutes</description>
    <label>Remaining 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Second15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Second15MinuteUnit__c</fullName>
    <description>The price applied during the second 15 minutes</description>
    <label>Second 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Third15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Third15MinuteUnit__c</fullName>
    <description>The price applied during the third 15 minutes</description>
    <label>Third 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ClosingOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_ClosingOperatingHours__c</fullName>
    <description>Specific time during which the product stops being operational to be sold to the customers</description>
    <label>Closing Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_CPMS__c.field-meta.xml
<CustomField>
    <fullName>COMM_CPMS__c</fullName>
    <description>Which CPMS provider is associated with park where the reservation was done</description>
    <label>Parking System Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_CPMS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_OpeningOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_OpeningOperatingHours__c</fullName>
    <description>Specific time during which the product starts being operational to be sold to the customers</description>
    <label>Opening Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Park__c.field-meta.xml
<CustomField>
    <fullName>COMM_Park__c</fullName>
    <description>Park associated with the Product</description>
    <label>Park</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Park</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <description>Defines the periodicity of the subscription</description>
    <label>Subscription Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubCategory__c</fullName>
    <description>Used to define the sub-category of the product.</description>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Park</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Fast Lane</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Exempt Official Entity</fullName>
            </value>
            <value>
                <fullName>ANA + Entities</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>RAC / Shuttle NL</fullName>
            </value>
            <value>
                <fullName>Staff Company</fullName>
            </value>
            <value>
                <fullName>Staff Individual</fullName>
            </value>
            <value>
                <fullName>Fast Track Plus</fullName>
            </value>
            <value>
                <fullName>Lounge Adult</fullName>
            </value>
            <value>
                <fullName>Lounge Child</fullName>
            </value>
            <value>
                <fullName>Lounge Adult with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Child with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Non Schengen</fullName>
            </value>
            <value>
                <fullName>Terminal</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non -Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Adult Non -Schengen</label>
            </value>
            <value>
                <fullName>Lounge Child Non - Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Child Non - Schengen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Tax__c.field-meta.xml
<CustomField>
    <fullName>COMM_Tax__c</fullName>
    <description>Defines the tax used for the product based on location</description>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>COMM_Airport__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continent</fullName>
            </value>
            <value>
                <fullName>Madeira</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date for which the product is deemed valid</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_SL_ProductValidationTest.cls
/**
 * @author Ruben Rodrigues
 * @description COMM_SL_ProductValidation test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer          Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Ruben Rodrigues    07/06/2024      90             Original version
 **/
@isTest
public class COMM_SL_ProductValidationTest {
    @testSetup
    static void setup() {
        List<Object> customPbs = COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Pricebook2',
            new Map<String, Object>{
                'Name' => 'Custom Parking Price Book',
                'Description' => 'Custom Parking Price Book',
                'IsActive' => true,
                'COMM_ValidFrom__c' => System.now().addSeconds(30),
                'COMM_ValidTo__c' => System.now().addDays(2)
            }
        );

        Pricebook2 customPb = (Pricebook2) customPbs[0];
        Time myTime = Time.newInstance(1, 2, 3, 0);
        // Insert Product2
        List<Object> products = COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'Parking Service',
                'ProductCode' => 'PS',
                'Description' => 'Parking Service',
                'IsActive' => false,
                'Family' => 'Parking',
                'COMM_ValidFrom__c' => System.now().addSeconds(30),
                'COMM_ValidTo__c' => System.now().addDays(2),
                'COMM_Airport__c' => 'LIS',
                'COMM_Tax__c' => 'Continent',
                'COMM_Park__c' => 'p0',
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_OpeningOperatingHours__c' => myTime,
                'COMM_ClosingOperatingHours__c' => myTime,
                'COMM_Periodicity__c' => 'Monthly',
                'COMM_SubCategory__c' => 'Park'
            }
        );

        Product2 parkingProduct = (Product2) products[0];

        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'COMM_Capacity__c',
            new Map<String, Object>{
                'COMM_ValidFrom__c' => Datetime.now().addSeconds(2),
                'COMM_ValidTo__c' => Datetime.now().addDays(2),
                'COMM_Capacity__c' => 10,
                'COMM_Product__c' => parkingProduct.Id,
                'COMM_IsDefaultCapacity__c' => true,
                'COMM_ProcessStatus__c' => 'PENDING'
            }
        );

        List<sObject> updatedProducts = COMM_TestDataFactory.updateRecords(
            new List<Id>{ parkingProduct.Id },
            'Product2',
            new Map<String, Object>{ 'IsActive' => true }
        );

        parkingProduct = (Product2) updatedProducts[0];
        // Insert PricebookEntry for Standard Pricebook
        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'PricebookEntry',
            new Map<String, Object>{
                'Pricebook2Id' => Test.getStandardPricebookId(),
                'Product2Id' => parkingProduct.Id,
                'UnitPrice' => 0,
                'IsActive' => true,
                'COMM_First15MinuteUnit__c' => 1,
                'COMM_Second15MinuteUnit__c' => 1,
                'COMM_Third15MinuteUnit__c' => 1,
                'COMM_Remaining15MinuteUnit__c' => 1,
                'COMM_FirstPeriodStartDay__c' => 1,
                'COMM_FirstPeriodEndDay__c' => 366,
                'COMM_FirstPeriodDailyMaximum__c' => 1
            }
        );

        // Insert PricebookEntry for Custom Parking Pricebook
        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'PricebookEntry',
            new Map<String, Object>{
                'Pricebook2Id' => customPb.Id,
                'Product2Id' => parkingProduct.Id,
                'UnitPrice' => 0,
                'IsActive' => true,
                'COMM_First15MinuteUnit__c' => 2,
                'COMM_Second15MinuteUnit__c' => 2,
                'COMM_Third15MinuteUnit__c' => 2,
                'COMM_Remaining15MinuteUnit__c' => 2,
                'COMM_FirstPeriodStartDay__c' => 1,
                'COMM_FirstPeriodEndDay__c' => 366,
                'COMM_FirstPeriodDailyMaximum__c' => 2
            }
        );

        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true,
            Type__c = COMM_GEN_Utility.TYPE_PUBLIC,
            COMM_ValidFrom__c = DateTime.newInstance(Date.today().year(), 1, 1, 0, 0, 0),
            COMM_ValidTo__c = DateTime.newInstance(Date.today().year(), 12, 31, 23, 59, 0)
        );
        update standardPricebook;

        //Insert Card Product and Pricebook Entry for testing
        Product2 fastTrackProduct = (Product2) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'Fast Track Product',
                'ProductCode' => 'FTrack',
                'Description' => 'FTrack',
                'IsActive' => false,
                'Family' => COMM_DO_Product2.CATEGORY_FASTTRACK,
                'COMM_ValidFrom__c' => System.now().addSeconds(30),
                'COMM_ValidTo__c' => System.now().addDays(2),
                'COMM_Airport__c' => 'LIS',
                'COMM_Tax__c' => 'Continent',
                'COMM_Park__c' => 'p0',
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_OpeningOperatingHours__c' => myTime,
                'COMM_ClosingOperatingHours__c' => myTime
            }
        )[0];

        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'PricebookEntry',
            new Map<String, Object>{
                'Pricebook2Id' => Test.getStandardPricebookId(),
                'Product2Id' => fastTrackProduct.Id,
                'UnitPrice' => 10,
                'IsActive' => true
            }
        );

        //Insert Lounge Product and Pricebook Entry for testing
        Product2 loungeProduct = (Product2) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'Lounge Product',
                'ProductCode' => 'lounge2',
                'Description' => 'lounge',
                'IsActive' => false,
                'Family' => COMM_DO_Product2.CATEGORY_LOUNGE,
                'COMM_ValidFrom__c' => System.now().addSeconds(30),
                'COMM_ValidTo__c' => System.now().addDays(2),
                'COMM_Airport__c' => 'LIS',
                'COMM_Tax__c' => 'Continent',
                'COMM_Park__c' => 'p0',
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_OpeningOperatingHours__c' => myTime,
                'COMM_ClosingOperatingHours__c' => myTime,
                'COMM_SubCategory__c' => 'Lounge'
            }
        )[0];
        products.add(loungeProduct);

        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'COMM_Capacity__c',
            new Map<String, Object>{
                'COMM_ValidFrom__c' => Datetime.now().addSeconds(2),
                'COMM_ValidTo__c' => Datetime.now().addDays(2),
                'COMM_Capacity__c' => 10,
                'COMM_Product__c' => loungeProduct.Id,
                'COMM_IsDefaultCapacity__c' => true,
                'COMM_ProcessStatus__c' => 'PENDING'
            }
        );

        // Insert Child Product
        Product2 pForCap = (Product2) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'Child',
                'ProductCode' => 'C2132',
                'Description' => 'Test Lounge',
                'IsActive' => true,
                'Family' => 'Lounge',
                'COMM_ValidFrom__c' => System.now().addMinutes(1),
                'COMM_ValidTo__c' => System.now().addDays(2),
                'COMM_Airport__c' => 'LIS',
                'COMM_Tax__c' => 'Continent',
                'COMM_OpeningOperatingHours__c' => myTime,
                'COMM_ClosingOperatingHours__c' => myTime,
                'COMM_ParentProduct__c' => loungeProduct.id,
                'COMM_SubCategory__c' => 'Lounge',
                'COMM_WhereProductAvailable__c' => COMM_DO_Product2.PRODUCT_AVAILABLE_IN_COMMERCE
            }
        )[0];

        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'COMM_Capacity__c',
            new Map<String, Object>{
                'COMM_ValidFrom__c' => Datetime.now().addSeconds(2),
                'COMM_ValidTo__c' => Datetime.now().addDays(2),
                'COMM_Capacity__c' => 10,
                'COMM_Product__c' => pForCap.Id,
                'COMM_IsDefaultCapacity__c' => true,
                'COMM_ProcessStatus__c' => 'PENDING'
            }
        );

        //Generate Product Settings
        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'COMM_ProductSetting__c',
            new Map<String, Object>{
                'Name' => 'Payment Type Settings (Test)',
                'COMM_FieldName__c' => 'Payment Type',
                'COMM_CoreEssential__c' => true,
                'COMM_CommerceEssential__c' => false,
                'COMM_FieldAPIName__c' => 'COMM_PaymentType__c',
                'COMM_CommerceMappingAttribute__c' => null,
                'COMM_EligibleProductType__c' => 'Parking;Lounge;Fast Track;Subscription'
            }
        );
        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'COMM_ProductSetting__c',
            new Map<String, Object>{
                'Name' => 'Price determined in Core Setting (Test)',
                'COMM_FieldName__c' => 'Price determined in Core',
                'COMM_CoreEssential__c' => false,
                'COMM_CommerceEssential__c' => true,
                'COMM_FieldAPIName__c' => 'COMM_PriceDeterminedInCore__c',
                'COMM_CommerceMappingAttribute__c' => 'c_externalPricing',
                'COMM_EligibleProductType__c' => 'Parking;Lounge;Fast Track;Subscription'
            }
        );
    }

    @isTest
    static void verifyReadinessTest() {
        //Scenario: Three products with missing field are verified
        //Expected: Three Product Readiness instances are generated

        //Query expected list
        List<Product2> productList = [
            SELECT
                Id,
                Family,
                IsActive,
                COMM_ValidFrom__c,
                COMM_ValidTo__c,
                COMM_IsIntegratedInCommerce__c,
                COMM_HasUpdateForCommerce__c,
                COMM_ParentProduct__c,
                ProductCode,
                (
                    SELECT
                        Id,
                        UnitPrice,
                        COMM_First15MinuteUnit__c,
                        COMM_Second15MinuteUnit__c,
                        COMM_Third15MinuteUnit__c,
                        COMM_Remaining15MinuteUnit__c,
                        COMM_FirstPeriodStartDay__c,
                        COMM_FirstPeriodEndDay__c,
                        COMM_FirstPeriodDailyMaximum__c,
                        Pricebook2.IsStandard
                    FROM PricebookEntries
                    WHERE IsActive = TRUE
                ),
                (
                    SELECT Id
                    FROM Capacities__r
                    WHERE COMM_Active__c = TRUE AND COMM_IsDefaultCapacity__c = TRUE AND COMM_ProcessStatus__c IN ('COMPLETED', 'PENDING')
                )
            FROM Product2
        ];

        Test.startTest();
        List<COMM_ProductReadiness__c> resultList = new COMM_SL_ProductValidation().verifyReadiness(productList);
        Test.stopTest();

        Assert.areEqual(productList.size(), resultList.size(), 'expected result list to contain a readiness record for each Product');
        for (Integer index = 0; index < resultList.size(); index++) {
            Assert.areEqual(productList[0].Id, resultList[0].COMM_Product__c, 'expected readiness record to be associated with product record');
        }
    }
}