force-app/main/default/objects/COMM_Capacity__c/COMM_Capacity__c.object-meta.xml
<CustomObject>
    <description>The available capacity for a given Product</description>
    <label>Capacity</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Active__c.field-meta.xml
<CustomField>
    <fullName>COMM_Active__c</fullName>
    <description>Determine if Record is Active</description>
    <formula>COMM_ValidTo__c &gt; NOW()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Capacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Capacity__c</fullName>
    <description>It is the daily capacity set by hour, that is constant throughout the operating hours.

This capacity configuration is not applicable to subscriptions.

For the subscriptions, the capacity is calculated by multiplying the total number of parking spaces by the multiplier. This capacity is constant, therefore is not defined by hour.</description>
    <inlineHelpText>To put the product as suspended, changed capacity to 0.</inlineHelpText>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>COMM_ProcessStatus__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT PROCESSED</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>FAILED</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>RUNNING</fullName>
                <label>Running</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the capacity for specific period of times will be applied</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>For Subscription, product must also be subscription.
For Capacity, product must also be a non-subscription</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Capacity</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>notEqual</operation>
            <value>Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Capacities</relationshipLabel>
    <relationshipName>Capacities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the capacity is valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/recordTypes/COMM_Subscription.recordType-meta.xml
<RecordType>
    <fullName>COMM_Subscription</fullName>
    <active>true</active>
    <description>Record Type for Capacity used in Subscription Products</description>
    <label>Subscription</label>
</RecordType>

force-app/main/default/objects/COMM_Subscription__c/COMM_Subscription__c.object-meta.xml
<CustomObject>
    <description>Object to represent a Subscription associated with a Client</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SBS-{0000}</displayFormat>
        <label>Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Active__c.field-meta.xml
<CustomField>
    <fullName>COMM_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if the Subscription is currently Active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_OCIEndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_OCIEndDate__c</fullName>
    <description>Field which will store the Product valid date to identify the possibility to extend the Subscription End Date based on the Periodicity.</description>
    <label>OCI End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product the Subscription is associated with</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Subscription can only be associated with a Subscription Product</errorMessage>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>COMM_Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Status__c.field-meta.xml
<CustomField>
    <fullName>COMM_Status__c</fullName>
    <description>Current Status of the Subscription</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Approval</fullName>
                <default>true</default>
                <label>In Approval</label>
            </value>
            <value>
                <fullName>Waiting Conclusion</fullName>
            </value>
            <value>
                <fullName>Process Concluded</fullName>
            </value>
            <value>
                <fullName>Request Denied</fullName>
            </value>
            <value>
                <fullName>Archieved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Pending Form</fullName>
                <isActive>false</isActive>
                <label>Pending Form</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Product for the Product Record</description>
    <label>Parent Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Airport needs to be the same in both Parent and Child Product</errorMessage>
        <filterItems>
            <field>Product2.COMM_Airport__c</field>
            <operation>equals</operation>
            <valueField>$Source.COMM_Airport__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/COMM_Subscription.recordType-meta.xml
<RecordType>
    <fullName>COMM_Subscription</fullName>
    <active>true</active>
    <description>This record type will used to typify subscriptions</description>
    <label>Subscription</label>
</RecordType>

force-app/main/default/classes/COMM_Async_CapacityEndDateExtension.cls
/**
 * @author Daniel Reto
 * @description Batch class to update the reservation on OCI
 * when a new Capacity with a hight ValidTo date is created and confirmed (Process Status = COMPLETED)
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      11/04/2024      ECOMM-204: Original version
 * Jose Passos      02/05/2024      Update ociReservation.reserve to request Prices as this is a parent product
 **/
public with sharing class COMM_Async_CapacityEndDateExtension extends FW_AsyncHandler implements Database.Batchable<SObject>, Database.Stateful {
    //batch framework parameters (used by the framework to pass values to the batch dynamically)
    @TestVisible
    private final static string PARAMETER_MINUTE_EXECUTE_SINCE = 'MinuteToExecute';
    @TestVisible
    private final static string PARAMETER_HOUR_EXECUTE_SINCE = 'HourToExecute';

    private COMM_IREP_Subscription subscriptionRep;

    private Integer minuteToExecute;
    private Integer hourToExecute;

    /**
     * @description Class Constructor to initialize REP class
     */
    public COMM_Async_CapacityEndDateExtension() {
        this.subscriptionRep = new COMM_REP_Subscription();
    }

    @testVisible
    private COMM_Async_CapacityEndDateExtension(
        COMM_IREP_Subscription subscriptionRep,
        FW_IREP_JobExecution jobExecutionRep,
        FW_IREP_Parameters parameterRep
    ) {
        this.subscriptionRep = subscriptionRep;
        this.jobExecutionRep = jobExecutionRep;
        this.parameterRep = parameterRep;
    }

    /**
     * @description Batch Start Method. According to the Batch Parameters, initiates query to obtain all records
     * of a specified SObject, whose specified Date Field is set in the past.
     *
     * @param bc Context Information of the executed batch
     * @return Database.QueryLocator with the built query
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        setAsyncApexJobId(bc.getJobId());

        minuteToExecute = Integer.valueOf(getParameterValue(PARAMETER_MINUTE_EXECUTE_SINCE));
        hourToExecute = Integer.valueOf(getParameterValue(PARAMETER_HOUR_EXECUTE_SINCE));

        DateTime dateTimeToExecute = DateTime.newInstance(
                DateTime.now().year(),
                DateTime.now().month(),
                DateTime.now().day(),
                hourToExecute,
                minuteToExecute,
                0
            )
            .addDays(-1);

        FW_QueryBuilder queryCapacity = new FW_QueryBuilder(COMM_Capacity__c.SObjectType)
            .selectFields(COMM_REP_Capacity.CAPACITY_FIELDS)
            .selectParentFields(COMM_Capacity__c.COMM_Product__c, new List<SObjectField>{ Product2.ProductCode })
            .setWhere('LastModifiedDate > ' + dateTimeToExecute.format('yyyy-MM-dd\'T\'HH:mm:ssXXX'))
            .whereEquals('COMM_Active__c', true)
            .whereEquals('COMM_ProcessStatus__c', COMM_DO_Capacity.PROCESS_STATUS_COMPLETED)
            .whereEquals(
                'RecordTypeId',
                Schema.SObjectType.COMM_Capacity__c.getRecordTypeInfosByDeveloperName().get('COMM_Subscription').RecordTypeId
            );
            //.orderByAsc('COMM_ValidTo__c');

        List<COMM_Capacity__c> capacityList = Database.query(queryCapacity.getQuery());

        List<String> parentProductIds = new List<String>();
        for (COMM_Capacity__c capacityRecord : capacityList) {
            parentProductIds.add(capacityRecord.COMM_Product__c);
        }


        //Subscriptions
        //List<COMM_Subscription__c> subscriptionList = subscriptionRep.getSubscriptionsByParentProductIds(parentIdSet);

        FW_QueryBuilder querySubscriptions = new FW_QueryBuilder(COMM_Subscription__c.SObjectType)
            .selectFields(COMM_REP_Subscription.SUBSCRIPTION_FIELDS)
            .selectParentFields(COMM_Subscription__c.COMM_Product__c, new List<SObjectField>{ Product2.ProductCode, Product2.COMM_ParentProduct__c })
            .whereEquals('COMM_Active__c', true)
            .whereIn('COMM_Product__r.COMM_ParentProduct__c', parentProductIds)
            .whereEquals('COMM_Status__c', COMM_DO_Subscription.STATUS_PROCESS_CONCLUDED);

        return executeQuery(querySubscriptions);
    }

    /**
     * @description Batch Execute Method. Updates the records active field to false that were obtained in the start method's query.
     *
     * @param bc Context Information of the executed batch
     * @param subscriptionList List of COMM_Subscription__c that will be renewed
     */
    public void execute(Database.BatchableContext bc, List<COMM_Subscription__c> subscriptionList) {
        Map<String, DateTime> valitToByParentIdMap = new Map<String, DateTime>();
        Map<Id, String> productCodeByParentIdMap = new Map<Id, String>();
        
        DateTime dateTimeToExecute = DateTime.newInstance(
                DateTime.now().year(),
                DateTime.now().month(),
                DateTime.now().day(),
                hourToExecute,
                minuteToExecute,
                0
            )
            .addDays(-1);

        List<Id> parentProductsIdSet = new List<Id>();
        for (COMM_Subscription__c subscriptionRecord : subscriptionList) {
            parentProductsIdSet.add(subscriptionRecord.COMM_Product__r.COMM_ParentProduct__c);
        }

        FW_QueryBuilder query = new FW_QueryBuilder(COMM_Capacity__c.SObjectType)
            .selectFields(COMM_REP_Capacity.CAPACITY_FIELDS)
            .selectParentFields(COMM_Capacity__c.COMM_Product__c, new List<SObjectField>{ Product2.ProductCode })
            .setWhere('LastModifiedDate > ' + dateTimeToExecute.format('yyyy-MM-dd\'T\'HH:mm:ssXXX'))
            .whereEquals('COMM_Active__c', true)
            .whereEquals('COMM_ProcessStatus__c', COMM_DO_Capacity.PROCESS_STATUS_COMPLETED)
            .whereEquals(
                'RecordTypeId',
                Schema.SObjectType.COMM_Capacity__c.getRecordTypeInfosByDeveloperName().get('COMM_Subscription').RecordTypeId
            )
            .whereIn('COMM_Product__c', parentProductsIdSet)
            .orderByAsc('COMM_ValidTo__c');

        List<COMM_Capacity__c> capacityList = Database.query(query.getQuery());

        for (COMM_Capacity__c capacityRecord : capacityList) {
            valitToByParentIdMap.put(capacityRecord.COMM_Product__c, capacityRecord.COMM_ValidTo__c);
            productCodeByParentIdMap.put(capacityRecord.COMM_Product__c, capacityRecord.COMM_Product__r.ProductCode);
        }

        if (subscriptionList != null && !subscriptionList.isEmpty()) {
            COMM_WS_ReservationInput input = new COMM_WS_ReservationInput();
            input.expirationSeconds = 0;
            input.product = new List<COMM_WS_ReservationInput.Product>();

            for (COMM_Subscription__c subscriptionRecord : subscriptionList) {
                DateTime ociEndDateValue = DateTime.newInstance(subscriptionRecord.COMM_OCIEndDate__c, Time.newInstance(0, 0, 0, 0)).addDays(1);
                if (valitToByParentIdMap.get(subscriptionRecord.COMM_Product__r.COMM_ParentProduct__c) > ociEndDateValue) {
                    COMM_WS_ReservationInput.Product product = new COMM_WS_ReservationInput.Product();
                    product.productId = productCodeByParentIdMap.get(subscriptionRecord.COMM_Product__r.COMM_ParentProduct__c);
                    product.startDate = ociEndDateValue;
                    product.endDate = valitToByParentIdMap.get(subscriptionRecord.COMM_Product__r.COMM_ParentProduct__c);
                    input.product.add(product);

                    subscriptionRecord.COMM_OCIEndDate__c = valitToByParentIdMap.get(subscriptionRecord.COMM_Product__r.COMM_ParentProduct__c).date();
                }
            }

            if (!input.product.isEmpty()) {
                COMM_SL_WS_OCIReservations ociReservation = new COMM_SL_WS_OCIReservations();
                ociReservation.reserve(input, false);
            }

            subscriptionRep.updateSObjects(subscriptionList);
        }
    }

    /**
     * @description Batch Finish Method. Initiates the Framework batch finished process.
     *
     * @param bc Context Information of the executed batch
     */
    public void finish(Database.BatchableContext bc) {
        finishBatch(bc.getJobId());
    }
}