force-app/main/default/objects/COMM_Capacity__c/COMM_Capacity__c.object-meta.xml
<CustomObject>
    <description>The available capacity for a given Product</description>
    <label>Capacity</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Capacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Capacity__c</fullName>
    <description>It is the daily capacity set by hour, that is constant throughout the operating hours.

This capacity configuration is not applicable to subscriptions.

For the subscriptions, the capacity is calculated by multiplying the total number of parking spaces by the multiplier. This capacity is constant, therefore is not defined by hour.</description>
    <inlineHelpText>To put the product as suspended, changed capacity to 0.</inlineHelpText>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the capacity for specific period of times will be applied</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>For Subscription, product must also be subscription.
For Capacity, product must also be a non-subscription</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Capacity</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>notEqual</operation>
            <value>Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Capacities</relationshipLabel>
    <relationshipName>Capacities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the capacity is valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Product for the Product Record</description>
    <label>Parent Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Airport needs to be the same in both Parent and Child Product</errorMessage>
        <filterItems>
            <field>Product2.COMM_Airport__c</field>
            <operation>equals</operation>
            <valueField>$Source.COMM_Airport__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_SL_GetProductAvailability.cls
/**
 * @author Carlos Fusco
 * @description Service Layer class to get Product Availability for new Subscriptions request
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Carlos Fusco   28/03/2024       Original version
 * Daniel Reto    02/05/2024       ECOMM-957
 * Daniel Reto    07/05/2024       ECOMM-281
 **/
public inherited sharing class COMM_SL_GetProductAvailability {
    private static COMM_IREP_Product2 productRep = new COMM_REP_Product2();
    /**
     * @description Get product pricing information
     *
     * @param inputWrapper Wrapper with variable defined from Flow
     * @return List of choices with the options to display for selection on Flow
     */
    public static Map<String, Integer> getProductAvailability(List<COMM_SL_GetProductPrice.InputWrapper> inputWrapper) {
        List<Product2> productsList = new List<Product2>();
        Map<String, List<Product2>> productsByParentMap = new Map<String, List<Product2>>();
        List<COMM_Capacity__c> capacitiesList = new List<COMM_Capacity__c>();
        Map<String, COMM_Capacity__c> capacityByProducCodeMap = new Map<String, COMM_Capacity__c>();
        Map<String, Integer> quantitiesByProductCodeMap = new Map<String, Integer>();

        productsList = productRep.getProductsByProductCodes(inputWrapper.get(0).codes).values();

        for (Product2 product : productsList) {
            if (!productsByParentMap.containsKey(product.COMM_ParentProduct__c)) {
                productsByParentMap.put(product.COMM_ParentProduct__c, new List<Product2>());
            }
            productsByParentMap.get(product.COMM_ParentProduct__c).add(product);
        }

        COMM_REP_Capacity capacityRep = new COMM_REP_Capacity();
        capacitiesList = capacityRep.getCapacityByProductIds(productsByParentMap.keySet());

        for (COMM_Capacity__c capacity : capacitiesList) {
            List<Product2> productsToProcess = productsByParentMap.get(capacity.COMM_Product__c);

            for (Product2 currentProduct : productsToProcess) {
                capacityByProducCodeMap.put(currentProduct.ProductCode, capacity);
            }
        }

        for (String productCode : capacityByProducCodeMap.keySet()) {
            COMM_WS_AvailabilityInput input = new COMM_WS_AvailabilityInput();
            COMM_WS_AvailabilityInput.Product productRecordInput = new COMM_WS_AvailabilityInput.Product();
            productRecordInput.productId = capacityByProducCodeMap.get(productCode).COMM_Product__r.ProductCode;
            productRecordInput.startDate = System.today();
            productRecordInput.endDate = capacityByProducCodeMap.get(productCode).COMM_ValidTo__c;
            input.products = new List<COMM_WS_AvailabilityInput.Product>{ productRecordInput };

            COMM_SL_WS_OCIAvailability ociAvailability = new COMM_SL_WS_OCIAvailability();
            COMM_WS_AvailabilityOutput output = ociAvailability.checkAvailability(input, true);

            for (COMM_WS_AvailabilityOutput.Product product : output.products) {
                if (product.available > 0) {
                    quantitiesByProductCodeMap.put(productCode, product.available.intValue());
                }
            }
        }

        return quantitiesByProductCodeMap;
    }
}