force-app/main/default/objects/COMM_Capacity__c/COMM_Capacity__c.object-meta.xml
<CustomObject>
    <description>The available capacity for a given Product</description>
    <label>Capacity</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Capacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Capacity__c</fullName>
    <description>It is the daily capacity set by hour, that is constant throughout the operating hours.

This capacity configuration is not applicable to subscriptions.

For the subscriptions, the capacity is calculated by multiplying the total number of parking spaces by the multiplier. This capacity is constant, therefore is not defined by hour.</description>
    <inlineHelpText>To put the product as suspended, changed capacity to 0.</inlineHelpText>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the capacity for specific period of times will be applied</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>For Subscription, product must also be subscription.
For Capacity, product must also be a non-subscription</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Capacity</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>notEqual</operation>
            <value>Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Capacities</relationshipLabel>
    <relationshipName>Capacities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the capacity is valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Product for the Product Record</description>
    <label>Parent Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Airport needs to be the same in both Parent and Child Product</errorMessage>
        <filterItems>
            <field>Product2.COMM_Airport__c</field>
            <operation>equals</operation>
            <valueField>$Source.COMM_Airport__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_SL_SetProductReservation.cls
/**
 * @author Carlos Fusco
 * @description Service Layer class to set Product Reservation for new Subscriptions request
 * process defined in Flow
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Carlos Fusco     28/03/2024       Original version
 * Jose Passos      02/05/2024       Update ociReservation.reserve to request Prices as this is a parent product
 **/
public inherited sharing class COMM_SL_SetProductReservation {
    private static COMM_IREP_Product2 productRep = new COMM_REP_Product2();
    /**
     * @description Wrapper definition with variable set from Flow
     */
    public class InputWrapper {
        @InvocableVariable(label='Codes' description='Product Codes')
        public List<String> codes;
    }

    /**
     * @description Set product reservation
     *
     * @param inputWrapper Wrapper with variable defined from Flow
     * @return List of choices with the options to display for selection on Flow
     */
    @InvocableMethod(label='Set Product Reservation' description='Set Product Reservation depending on chosen product code')
    public static List<List<COMM_SL_FlowChoice>> setProductReservation(List<InputWrapper> inputWrapper) {
        InputWrapper inputs = inputWrapper.get(0);
        List<COMM_SL_FlowChoice> flowChoices = new List<COMM_SL_FlowChoice>();

        List<String> codes = inputWrapper.get(0).codes;
        setReserve(codes);
        flowChoices.add(new COMM_SL_FlowChoice());

        return new List<List<COMM_SL_FlowChoice>>{ flowChoices };
    }

    /**
     * @description Call OCI reservation service
     *
     * @param codes Product codes to reserve
     */
    @future(callout=true)
    private static void setReserve(List<String> codes) {
        List<Product2> productsList = new List<Product2>();
        Map<String, List<Product2>> productsByParentMap = new Map<String, List<Product2>>();
        List<COMM_Capacity__c> capacitiesList = new List<COMM_Capacity__c>();
        Map<String, COMM_Capacity__c> capacityByProductCodeMap = new Map<String, COMM_Capacity__c>();

        productsList = productRep.getProductsByProductCodes(codes).values();

        for (Product2 product : productsList) {
            if (!productsByParentMap.containsKey(product.COMM_ParentProduct__c)) {
                productsByParentMap.put(product.COMM_ParentProduct__c, new List<Product2>());
            }
            productsByParentMap.get(product.COMM_ParentProduct__c).add(product);
        }

        COMM_REP_Capacity capacityRep = new COMM_REP_Capacity();
        capacitiesList = capacityRep.getCapacityByProductIds(productsByParentMap.keySet());

        for (COMM_Capacity__c capacity : capacitiesList) {
            List<Product2> productsToProcess = productsByParentMap.get(capacity.COMM_Product__c);

            for (Product2 currentProduct : productsToProcess) {
                capacityByProductCodeMap.put(currentProduct.ProductCode, capacity);
            }
        }

        COMM_WS_ReservationInput input = new COMM_WS_ReservationInput();
        input.expirationSeconds = 0;
        input.product = new List<COMM_WS_ReservationInput.Product>();

        for (String code : codes) {
            COMM_WS_ReservationInput.Product product = new COMM_WS_ReservationInput.Product();
            product.productId = capacityByProductCodeMap.get(code).COMM_Product__r.ProductCode;
            product.startDate = System.now();
            product.endDate = capacityByProductCodeMap.get(code).COMM_ValidTo__c;
            input.product.add(product);
        }

        COMM_SL_WS_OCIReservations ociReservation = new COMM_SL_WS_OCIReservations();
        ociReservation.reserve(input, false);
    }
}