force-app/main/default/objects/COMM_Capacity__c/COMM_Capacity__c.object-meta.xml
<CustomObject>
    <description>The available capacity for a given Product</description>
    <label>Capacity</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Active__c.field-meta.xml
<CustomField>
    <fullName>COMM_Active__c</fullName>
    <description>Determine if Record is Active</description>
    <formula>COMM_ValidTo__c &gt; NOW()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_CalculatedCapacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_CalculatedCapacity__c</fullName>
    <description>Field to calculate the used Capacity. For non-subscription Products, the Capacity will be value on the manual capacity field. If a Subscription Product, the capacity will be the result of applying the multiplier to the Parking Spaces.</description>
    <formula>IF(RecordType.DeveloperName = &apos;COMM_Subscription&apos;, FLOOR(COMM_ParkingSpaces__c * COMM_Multiplier__c), COMM_Capacity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_IsDefaultCapacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_IsDefaultCapacity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if Record is to be used as the Default Capacity for the associated Product</description>
    <label>Is Default Capacity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>COMM_ProcessStatus__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT PROCESSED</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>FAILED</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>RUNNING</fullName>
                <label>Running</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the capacity for specific period of times will be applied</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>For Subscription, product must also be subscription.
For Capacity, product must also be a non-subscription</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Capacity</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>notEqual</operation>
            <value>Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Capacities</relationshipLabel>
    <relationshipName>Capacities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date and hour for which the capacity is valid</description>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the capacity is valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Product for the Product Record</description>
    <label>Parent Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Airport needs to be the same in both Parent and Child Product</errorMessage>
        <filterItems>
            <field>Product2.COMM_Airport__c</field>
            <operation>equals</operation>
            <valueField>$Source.COMM_Airport__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_SAPLocation__c.field-meta.xml
<CustomField>
    <fullName>COMM_SAPLocation__c</fullName>
    <description>SAP Location product code as defined in SAP.</description>
    <label>SAP Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Tax__c.field-meta.xml
<CustomField>
    <fullName>COMM_Tax__c</fullName>
    <description>Defines the tax used for the product based on location</description>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>COMM_Airport__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continent</fullName>
            </value>
            <value>
                <fullName>Madeira</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_TimeZoneByAirport__c.field-meta.xml
<CustomField>
    <fullName>COMM_TimeZoneByAirport__c</fullName>
    <description>Formula field used to discover product Timezone based on the Airport.</description>
    <formula>IF( OR( ISPICKVAL(COMM_Airport__c, &apos;LIS&apos;), ISPICKVAL(COMM_Airport__c, &apos;OPO&apos;), ISPICKVAL(COMM_Airport__c, &apos;FAO&apos;)),
 &apos;Europe/Lisbon&apos;,
 IF( ISPICKVAL(COMM_Airport__c, &apos;FNC&apos;),
  &apos;Atlantic/Madeira&apos;,
   IF( ISPICKVAL(COMM_Airport__c, &apos;PDL&apos;),
    &apos;Atlantic/Azores&apos;,
    &apos;&apos;
  )
 )
)</formula>
    <label>Time Zone by Airport</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date for which the product is deemed valid</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_REP_Product2.cls
/**
 * @author Daniel Lascas
 * @description Product2 repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    20/03/2024       Original version
 * Jose Passos      21/03/2024       Add getProductsByProductCodes
 * Daniel Lascas    26/04/2024       ECOMM-891: Add getProductAndCapacitiesByProductCodes
 **/
public inherited sharing class COMM_REP_Product2 extends FW_SobjectRep implements COMM_IREP_Product2 {
    private COMM_REP_Capacity CAPACITY_REP = new COMM_REP_Capacity();
    public static final List<SObjectField> PRODUCT_FIELDS = new List<SObjectField>{
        Product2.Id,
        Product2.COMM_ParentProduct__c,
        Product2.ProductCode
    };

    /**
     * @description Retrieve a list of Active Products by a set of Product Ids
     *
     * @param productIds Set of Product Id's to query
     * @return List of Product Records found
     **/
    public List<Product2> getActiveProductsByIds(Set<Id> productIds) {
        return [
            SELECT Id
            FROM Product2
            WHERE Id IN :productIds AND IsActive = TRUE
            WITH USER_MODE
        ];
    }

    /**
     * @description Given a list of ProductCodes get Product2 details
     *
     * @param productCodeList List<Product2>
     * @return Map<String, Product2>
     */
    public Map<String, Product2> getProductsByProductCodes(List<String> productCodeList) {
        List<Product2> products = [
            SELECT
                Id,
                Name,
                ProductCode,
                Family,
                COMM_ParentProduct__c,
                COMM_ParentProduct__r.ProductCode,
                COMM_TimeZoneByAirport__c,
                COMM_Tax__c,
                COMM_SAPLocation__c
            FROM Product2
            WHERE ProductCode IN :productCodeList AND isActive = TRUE
            WITH SECURITY_ENFORCED
        ];

        Map<String, Product2> product2Map = new Map<String, Product2>();
        for (Product2 product : products) {
            product2Map.put(product.ProductCode, product);
        }

        return product2Map;
    }

    /**
     * @description Retrieve a list of Products and their processed default capacity by a set of Product Codes
     *
     * @param productCodes Set of Product Codes to query
     * @return List of Products with list of default capacities found
     */
    public List<Product2> getProductAndCapacitiesByProductCodes(Set<String> productCodes) {
        return [
            SELECT
                Id,
                ProductCode,
                COMM_ParentProduct__c,
                COMM_ParentProduct__r.ProductCode,
                Family,
                (
                    SELECT COMM_CalculatedCapacity__c
                    FROM Capacities__r
                    WHERE
                        COMM_IsDefaultCapacity__c = TRUE
                        AND COMM_Active__c = TRUE
                        AND COMM_ProcessStatus__c = :COMM_DO_Capacity.PROCESS_STATUS_COMPLETED
                )
            FROM Product2
            WHERE ProductCode IN :productCodes
            WITH USER_MODE
        ];
    }

    /**
     * @description Retrieve a list of Products with dynamic Field, set of fields on "productSettingsValues" Set<String>
     *
     * @param productSettingsValues Set of Product fields to query
     * @return List of Products
     */
    public List<Product2> getProductWithDynamicFields(Set<String> productSettingsValues) {
        // Construct the SOQL query to fetch all relevant fields from Product2
        String fieldNames = 'Id, Family';
        for (String fieldName : productSettingsValues) {
            fieldNames += ', ' + fieldName;
        }

        String dynamicQuery = 'SELECT ' + fieldNames + ' FROM Product2 WITH USER_MODE';
        return Database.query(dynamicQuery);
    }

    /**
     * @description Retrieve a list of valid Products and their processed default capacities
     * by a set of Product Ids
     *
     * @param productIdSet Set of Product Ids to query
     * @return List of Products with list of default capacities found
     */
    public List<Product2> getValidProductAndCapacitiesByIds(Set<Id> productIdSet) {
        return [
            SELECT
                Id,
                Family,
                (
                    SELECT Id
                    FROM Capacities__r
                    WHERE
                        COMM_IsDefaultCapacity__c = TRUE
                        AND COMM_Active__c = TRUE
                        AND COMM_ProcessStatus__c IN (:COMM_DO_Capacity.PROCESS_STATUS_COMPLETED, :COMM_DO_Capacity.PROCESS_STATUS_PENDING)
                )
            FROM Product2
            WHERE Id IN :productIdSet AND COMM_ValidFrom__c <= TODAY AND COMM_ValidTo__c >= TODAY
            WITH USER_MODE
        ];
    }

    /**
     * @description Retrieve a list of Products by a set of Product Ids
     *
     * @param productIds Set of Product Id's to query
     * @return List of Product Records found
     **/
    public List<Product2> getProductsByIds(Set<Id> productIds) {
        return [
            SELECT Id, COMM_Airport__c, COMM_TimeZoneByAirport__c
            FROM Product2
            WHERE Id IN :productIds
            WITH SECURITY_ENFORCED
        ];
    }
}