force-app/main/default/objects/COMM_Capacity__c/COMM_Capacity__c.object-meta.xml
<CustomObject>
    <description>The available capacity for a given Product</description>
    <label>Capacity</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Capacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Capacity__c</fullName>
    <description>It is the daily capacity set by hour, that is constant throughout the operating hours.

This capacity configuration is not applicable to subscriptions.

For the subscriptions, the capacity is calculated by multiplying the total number of parking spaces by the multiplier. This capacity is constant, therefore is not defined by hour.</description>
    <inlineHelpText>To put the product as suspended, changed capacity to 0.</inlineHelpText>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_IsDefaultCapacity__c.field-meta.xml
<CustomField>
    <fullName>COMM_IsDefaultCapacity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if Record is to be used as the Default Capacity for the associated Product</description>
    <label>Is Default Capacity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the capacity for specific period of times will be applied</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>For Subscription, product must also be subscription.
For Capacity, product must also be a non-subscription</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Capacity</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>notEqual</operation>
            <value>Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Capacities</relationshipLabel>
    <relationshipName>Capacities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date and hour for which the capacity is valid</description>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/COMM_Capacity__c/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the capacity is valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date and hour for which the price is valid</description>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <description>End date and hour for which the price is valid date for which the product is deemed valid</description>
    <label>Valid To</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of Price Book used (Public or Reseller)</description>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_First15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_First15MinuteUnit__c</fullName>
    <description>The price applied during the first 15 minutes</description>
    <label>First 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FirstPeriodDailyMaximum__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstPeriodDailyMaximum__c</fullName>
    <description>The First Period Daily Maximum value aplied to the days defined between that period</description>
    <label>First Period Daily Maximum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FirstPeriodEndDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstPeriodEndDay__c</fullName>
    <description>The day the first Period&apos;s price stops being applied</description>
    <label>First Period End Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_FirstPeriodStartDay__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstPeriodStartDay__c</fullName>
    <description>The day the first Period&apos;s price starts to be applied</description>
    <label>First Period Start Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Remaining15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Remaining15MinuteUnit__c</fullName>
    <description>The price applied during the remaining 15 minutes</description>
    <label>Remaining 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Second15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Second15MinuteUnit__c</fullName>
    <description>The price applied during the second 15 minutes</description>
    <label>Second 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COMM_Third15MinuteUnit__c.field-meta.xml
<CustomField>
    <fullName>COMM_Third15MinuteUnit__c</fullName>
    <description>The price applied during the third 15 minutes</description>
    <label>Third 15 minute unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ClosingOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_ClosingOperatingHours__c</fullName>
    <description>Specific time during which the product stops being operational to be sold to the customers</description>
    <label>Closing Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_CPMS__c.field-meta.xml
<CustomField>
    <fullName>COMM_CPMS__c</fullName>
    <description>Which CPMS provider is associated with park where the reservation was done</description>
    <label>Parking System Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_CPMS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_OpeningOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_OpeningOperatingHours__c</fullName>
    <description>Specific time during which the product starts being operational to be sold to the customers</description>
    <label>Opening Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Park__c.field-meta.xml
<CustomField>
    <fullName>COMM_Park__c</fullName>
    <description>Park associated with the Product</description>
    <label>Park</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Park</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <description>Defines the periodicity of the subscription</description>
    <label>Subscription Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubCategory__c</fullName>
    <description>Used to define the sub-category of the product.</description>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Park</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Fast Lane</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Exempt Official Entity</fullName>
            </value>
            <value>
                <fullName>ANA + Entities</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>RAC / Shuttle NL</fullName>
            </value>
            <value>
                <fullName>Staff Company</fullName>
            </value>
            <value>
                <fullName>Staff Individual</fullName>
            </value>
            <value>
                <fullName>Fast Track Plus</fullName>
            </value>
            <value>
                <fullName>Lounge Adult</fullName>
            </value>
            <value>
                <fullName>Lounge Child</fullName>
            </value>
            <value>
                <fullName>Lounge Adult with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Child with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Non Schengen</fullName>
            </value>
            <value>
                <fullName>Terminal</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non -Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Adult Non -Schengen</label>
            </value>
            <value>
                <fullName>Lounge Child Non - Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Child Non - Schengen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Tax__c.field-meta.xml
<CustomField>
    <fullName>COMM_Tax__c</fullName>
    <description>Defines the tax used for the product based on location</description>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>COMM_Airport__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continent</fullName>
            </value>
            <value>
                <fullName>Madeira</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date for which the product is deemed valid</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_REP_PricebookEntryTest.cls
/**
 * @author Ricardo Dias
 * @description COMM_REP_PricebookEntry test class
 *
 * Modification Log
 * -----------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Ricardo Dias     23/02/2024		100            Original version
 * Daniel Lascas    10/04/2024		100            ECOMM-194: Added test for getCardPBEByIds
 * Daniel Reto      01/05/2024		100            ECOMM-997: Added test for getPBEByProductCodeDataBaseQueryList
 * Daniel Lascas    07/06/2024		100            ECOMM-997: Added test for getPBEByProductAndPricebookIds
 **/
@isTest
private class COMM_REP_PricebookEntryTest {
    @TestSetup
    static void makeData() {
        List<Object> customPbs = COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Pricebook2',
            new Map<String, Object>{
                'Name' => 'Custom Parking Price Book',
                'Description' => 'Custom Parking Price Book',
                'IsActive' => true,
                'COMM_ValidFrom__c' => System.now().addSeconds(30),
                'COMM_ValidTo__c' => System.now().addDays(2)
            }
        );

        Pricebook2 customPb = (Pricebook2) customPbs[0];
        Time myTime = Time.newInstance(1, 2, 3, 0);
        // Insert Product2
        List<Object> products = COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'Parking Service',
                'ProductCode' => 'PS',
                'Description' => 'Parking Service',
                'IsActive' => false,
                'Family' => 'Parking',
                'COMM_ValidFrom__c' => System.now().addSeconds(30),
                'COMM_ValidTo__c' => System.now().addDays(2),
                'COMM_Airport__c' => 'LIS',
                'COMM_Tax__c' => 'Continent',
                'COMM_Park__c' => 'p0',
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_OpeningOperatingHours__c' => myTime,
                'COMM_ClosingOperatingHours__c' => myTime,
                'COMM_Periodicity__c' => 'Monthly',
                'COMM_SubCategory__c' => 'Park'
            }
        );

        Product2 parkingProduct = (Product2) products[0];

        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'COMM_Capacity__c',
            new Map<String, Object>{
                'COMM_ValidFrom__c' => Datetime.now().addHours(1),
                'COMM_ValidTo__c' => Datetime.now().addDays(2),
                'COMM_Capacity__c' => 10,
                'COMM_Product__c' => parkingProduct.Id,
                'COMM_IsDefaultCapacity__c' => true
            }
        );

        List<sObject> updatedProducts = COMM_TestDataFactory.updateRecords(
            new List<Id>{ parkingProduct.Id },
            'Product2',
            new Map<String, Object>{ 'IsActive' => true }
        );

        parkingProduct = (Product2) updatedProducts[0];
        // Insert PricebookEntry for Standard Pricebook
        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'PricebookEntry',
            new Map<String, Object>{
                'Pricebook2Id' => Test.getStandardPricebookId(),
                'Product2Id' => parkingProduct.Id,
                'UnitPrice' => 0,
                'IsActive' => true,
                'COMM_First15MinuteUnit__c' => 1,
                'COMM_Second15MinuteUnit__c' => 1,
                'COMM_Third15MinuteUnit__c' => 1,
                'COMM_Remaining15MinuteUnit__c' => 1,
                'COMM_FirstPeriodStartDay__c' => 1,
                'COMM_FirstPeriodEndDay__c' => 366,
                'COMM_FirstPeriodDailyMaximum__c' => 1
            }
        );

        // Insert PricebookEntry for Custom Parking Pricebook
        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'PricebookEntry',
            new Map<String, Object>{
                'Pricebook2Id' => customPb.Id,
                'Product2Id' => parkingProduct.Id,
                'UnitPrice' => 0,
                'IsActive' => true,
                'COMM_First15MinuteUnit__c' => 2,
                'COMM_Second15MinuteUnit__c' => 2,
                'COMM_Third15MinuteUnit__c' => 2,
                'COMM_Remaining15MinuteUnit__c' => 2,
                'COMM_FirstPeriodStartDay__c' => 1,
                'COMM_FirstPeriodEndDay__c' => 366,
                'COMM_FirstPeriodDailyMaximum__c' => 2
            }
        );

        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true,
            Type__c = COMM_GEN_Utility.TYPE_PUBLIC,
            COMM_ValidFrom__c = DateTime.newInstance(Date.today().year(), 1, 1, 0, 0, 0),
            COMM_ValidTo__c = DateTime.newInstance(Date.today().year(), 12, 31, 23, 59, 0)
        );
        update standardPricebook;

        //Insert Card Product and Pricebook Entry for testing
        Product2 cardProduct = (Product2) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'Card',
                'ProductCode' => 'Card',
                'Description' => 'Card',
                'IsActive' => false,
                'Family' => COMM_DO_Product2.CATEGORY_CARD,
                'COMM_ValidFrom__c' => System.now().addSeconds(30),
                'COMM_ValidTo__c' => System.now().addDays(2),
                'COMM_Airport__c' => 'LIS',
                'COMM_Tax__c' => 'Continent',
                'COMM_Park__c' => 'p0',
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_OpeningOperatingHours__c' => myTime,
                'COMM_ClosingOperatingHours__c' => myTime
            }
        )[0];

        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'PricebookEntry',
            new Map<String, Object>{
                'Pricebook2Id' => Test.getStandardPricebookId(),
                'Product2Id' => cardProduct.Id,
                'UnitPrice' => 0,
                'IsActive' => true
            }
        );
    }

    @isTest
    static void getPBEByProductCodeList() {
        // Retrieve the Product2 record to get its ProductCode for the test
        Product2 testProduct = [SELECT Id, ProductCode FROM Product2 WHERE Name = 'Parking Service0' LIMIT 1];

        Test.startTest();
        List<PricebookEntry> actualEntries = new COMM_REP_PricebookEntry().getPBEByProductCodeList(new Set<String>{ testProduct.ProductCode });
        Test.stopTest();

        // Verify the number of entries retrieved matches expectations
        System.assertEquals(1, actualEntries.size(), 'Expected to retrieve 1 Pricebook Entries for the given product code.');
    }

    @isTest
    static void getCardPBEByIdsTest() {
        // Retrieve the Card Product record to get its Id for the test
        Product2 testProduct = [SELECT Id FROM Product2 WHERE Family = :COMM_DO_Product2.CATEGORY_CARD LIMIT 1];

        Test.startTest();
        List<PricebookEntry> actualEntries = new COMM_REP_PricebookEntry().getCardPBEByIds(new Set<Id>{ testProduct.Id });
        Test.stopTest();

        // Verify the number of entries retrieved matches expectations
        Assert.areEqual(1, actualEntries.size(), 'Expected to retrieve 1 Pricebook Entries for the given product Id.');
    }

    @isTest
    static void getPBEByProductCodeDataBaseQueryList() {
        // Retrieve the Product2 record to get its ProductCode for the test
        Product2 testProduct = [SELECT Id, ProductCode FROM Product2 WHERE Name = 'Parking Service0' LIMIT 1];

        Test.startTest();
        List<PricebookEntry> actualEntries = new COMM_REP_PricebookEntry()
            .getPBEByProductCodeDataBaseQueryList(new Set<String>{ testProduct.ProductCode });
        Test.stopTest();

        // Verify the number of entries retrieved matches expectations
        System.assertEquals(1, actualEntries.size(), 'Expected to retrieve 1 Pricebook Entries for the given product code.');
    }

    @isTest
    static void getPBEByProductAndPricebookIdsTest() {
        // Retrieve the Product2 record to get its ProductCode for the test
        PricebookEntry testPB = [SELECT Id, Product2Id, Pricebook2Id FROM PricebookEntry LIMIT 1];

        Test.startTest();
        List<PricebookEntry> actualEntries = new COMM_REP_PricebookEntry()
            .getPBEByProductAndPricebookIds(new Set<Id>{ testPB.Product2Id }, new Set<Id>{ testPB.Pricebook2Id });
        Test.stopTest();

        // Verify the number of entries retrieved matches expectations
        Assert.areEqual(testPB.Id, actualEntries[0].Id, 'Obtained Pricebook Entry does not match expected');
    }
}