force-app/main/default/objects/COMM_ProductSynchronizationFieldConvert__mdt/COMM_ProductSynchronizationFieldConvert__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to store conversion mapping of values between Salesforce and Commerce during Product Synchronization</description>
    <label>Product Synchronization Field Convert</label>
    <pluralLabel>Product Synchronization Field Converts</pluralLabel>
</CustomObject>

force-app/main/default/objects/COMM_ProductSynchronizationFieldConvert__mdt/fields/COMM_CommerceValue__c.field-meta.xml
<CustomField>
    <fullName>COMM_CommerceValue__c</fullName>
    <description>Value store in Commerce</description>
    <label>Commerce Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_ProductSynchronizationFieldConvert__mdt/fields/COMM_IntegrationApiName__c.field-meta.xml
<CustomField>
    <fullName>COMM_IntegrationApiName__c</fullName>
    <description>API Name of the field used in integration (OCAPI)</description>
    <label>Integration API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_ProductSynchronizationFieldConvert__mdt/fields/COMM_SalesforceValue__c.field-meta.xml
<CustomField>
    <fullName>COMM_SalesforceValue__c</fullName>
    <description>Value stored in Salesforce</description>
    <label>Salesforce Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_DO_ProductSyncFieldConvertTest.cls
/**
 * @author Daniel Lascas
 * @description COMM_DO_ProductSyncFieldConvert test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    15/04/2024      100            ECOMM-808: Original version
 **/
@isTest
private class COMM_DO_ProductSyncFieldConvertTest {
    private static final COMM_DO_ProductSyncFieldConvert CONVERT_DO = new COMM_DO_ProductSyncFieldConvert();
    @isTest
    static void conversionTest() {
        //Scenario: Commerce requires diferent values from the ones used in Code
        //Expected: Value is converted
        List<COMM_ProductSynchronizationFieldConvert__mdt> metadataList = COMM_ProductSynchronizationFieldConvert__mdt.getAll().values();
        Map<String, Object> valueMap = new Map<String, Object>{
            metadataList[0].COMM_IntegrationApiName__c => metadataList[0].COMM_SalesforceValue__c
        };
        Test.startTest();
        CONVERT_DO.verifyValueConversion(valueMap);
        Test.stopTest();

        Assert.areEqual(
            metadataList[0].COMM_CommerceValue__c,
            valueMap.get(metadataList[0].COMM_IntegrationApiName__c),
            'expected value to be converted'
        );
    }

    @isTest
    static void noConversionTest() {
        //Scenario: Map has no values that require conversion
        //Expected: Value is not converted
        Map<String, Object> valueMap = new Map<String, Object>{ 'c_testField' => 'testValue' };
        Test.startTest();
        CONVERT_DO.verifyValueConversion(valueMap);
        Test.stopTest();

        Assert.areEqual(1, valueMap.size(), 'map size does not match expected');
        Assert.areEqual('testValue', valueMap.get('c_testField'), 'expected value to not change');
    }
}