force-app/main/default/objects/Product2/fields/COMM_Tax__c.field-meta.xml
<CustomField>
    <fullName>COMM_Tax__c</fullName>
    <description>Defines the tax used for the product based on location</description>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>COMM_Airport__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continent</fullName>
            </value>
            <value>
                <fullName>Madeira</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/COMM_IREP_SapTaxCodesMapMdt.cls
/**
 * @author Rui Salgado
 * @description SAP Tax Codes map interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Rui Salgado      21/04/2024       Original version
 **/

public interface COMM_IREP_SapTaxCodesMapMdt {
    /**
     * @description get value of SAP Tax Codes map
     * @param instanceName instance name
     * @return Value of Instance COMM_Sap_Code__c
     */
    String getSapTaxCodesMap(String instanceName);

    /**
     * @description get value of SAP Tax Codes map
     * <TipoDoc>_<Local>_<TipoCliente>
     * @param docType document type (FT or NC)
     * @param location Product2.COMM_Tax__c
     * @param clientType  NAC, COM, OT (Nacional, comunitário, outro)
     * @return Value of Instance COMM_Sap_Code__c
     */
    String getSapTaxCodesMap(String docType, String location, String clientType);
}