force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Alarmistic__c.field-meta.xml
<CustomField>
    <fullName>COMM_Alarmistic__c</fullName>
    <description>The alarmistic percentage defined in this field will be the same for the default capacity and the capacity defined for a specific period.</description>
    <label>Alarmistic %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ClosingOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_ClosingOperatingHours__c</fullName>
    <description>Specific time during which the product stops being operational to be sold to the customers</description>
    <label>Closing Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_CPMS__c.field-meta.xml
<CustomField>
    <fullName>COMM_CPMS__c</fullName>
    <description>Which CPMS provider is associated with park where the reservation was done</description>
    <label>Parking System Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_CPMS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_OpeningOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_OpeningOperatingHours__c</fullName>
    <description>Specific time during which the product starts being operational to be sold to the customers</description>
    <label>Opening Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Park__c.field-meta.xml
<CustomField>
    <fullName>COMM_Park__c</fullName>
    <description>Park associated with the Product</description>
    <label>Park</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Park</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <description>Defines the periodicity of the subscription</description>
    <label>Subscription Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubCategory__c</fullName>
    <description>Used to define the sub-category of the product.</description>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Park</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Fast Lane</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Exempt Official Entity</fullName>
            </value>
            <value>
                <fullName>ANA + Entities</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>RAC / Shuttle NL</fullName>
            </value>
            <value>
                <fullName>Staff Company</fullName>
            </value>
            <value>
                <fullName>Staff Individual</fullName>
            </value>
            <value>
                <fullName>Fast Track Plus</fullName>
            </value>
            <value>
                <fullName>Lounge Adult</fullName>
            </value>
            <value>
                <fullName>Lounge Child</fullName>
            </value>
            <value>
                <fullName>Lounge Adult with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Child with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Non Schengen</fullName>
            </value>
            <value>
                <fullName>Terminal</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non -Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Adult Non -Schengen</label>
            </value>
            <value>
                <fullName>Lounge Child Non - Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Child Non - Schengen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Tax__c.field-meta.xml
<CustomField>
    <fullName>COMM_Tax__c</fullName>
    <description>Defines the tax used for the product based on location</description>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>COMM_Airport__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continent</fullName>
            </value>
            <value>
                <fullName>Madeira</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date for which the product is deemed valid</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/COMM_Product.recordType-meta.xml
<RecordType>
    <fullName>COMM_Product</fullName>
    <active>true</active>
    <description>This record type will be used to typify the products</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/COMM_Subscription.recordType-meta.xml
<RecordType>
    <fullName>COMM_Subscription</fullName>
    <active>true</active>
    <description>This record type will used to typify subscriptions</description>
    <label>Subscription</label>
</RecordType>

force-app/main/default/classes/COMM_OCI_UtilsTest.cls
/**
 * @author           Daniel Reto
 * @description      COMM_OCI_Utils test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      14/05/2024      100            Original version - ECOMM-281
 **/
@isTest
private class COMM_OCI_UtilsTest {
    @TestSetup
    static void makeData() {
        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'ParkProduct',
                'ProductCode' => 'ParkProduct',
                'Family' => COMM_OCI_Constants.PRODUCT_FAMILY_PARKING,
                'isActive' => false,
                'COMM_Alarmistic__c' => 25,
                'COMM_Airport__c' => 'OPO',
                'COMM_ClosingOperatingHours__c' => Time.newInstance(0, 0, 0, 0),
                'COMM_OpeningOperatingHours__c' => Time.newInstance(0, 0, 0, 0),
                'COMM_ValidFrom__c' => DateTime.now().addDays(1),
                'COMM_ValidTo__c' => DateTime.now().addDays(2),
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_Park__c' => 'P3',
                'COMM_Periodicity__c' => null,
                'COMM_Tax__c' => 'Continent',
                'COMM_SubCategory__c' => 'Park',
                'RecordTypeId' => Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('COMM_Product').RecordTypeId
            }
        );

        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'SubscriptionProduct',
                'ProductCode' => 'SubscriptionProduct',
                'Family' => COMM_OCI_Constants.PRODUCT_FAMILY_SUBSCRIPTION,
                'COMM_SubCategory__c' => 'Park',
                'COMM_Periodicity__c' => 'Monthly',
                'isActive' => false,
                'COMM_Airport__c' => 'LIS',
                'COMM_ClosingOperatingHours__c' => Time.newInstance(0, 0, 0, 0),
                'COMM_OpeningOperatingHours__c' => Time.newInstance(0, 0, 0, 0),
                'COMM_ValidFrom__c' => DateTime.now().addDays(1),
                'COMM_ValidTo__c' => DateTime.now().addDays(2),
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_Park__c' => 'P0',
                'COMM_Periodicity__c' => null,
                'COMM_Tax__c' => 'Continent',
                'COMM_SubCategory__c' => 'Park',
                'RecordTypeId' => Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('COMM_Subscription').RecordTypeId
            }
        );

        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'ProductWithoutFamily',
                'ProductCode' => 'ProductWithoutFamily',
                'Family' => null,
                'isActive' => false,
                'COMM_Airport__c' => 'LIS',
                'COMM_ClosingOperatingHours__c' => Time.newInstance(0, 0, 0, 0),
                'COMM_OpeningOperatingHours__c' => Time.newInstance(0, 0, 0, 0),
                'COMM_ValidFrom__c' => DateTime.now().addDays(1),
                'COMM_ValidTo__c' => DateTime.now().addDays(2),
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_Park__c' => 'P0',
                'COMM_Periodicity__c' => null,
                'COMM_Tax__c' => 'Continent',
                'COMM_SubCategory__c' => null,
                'RecordTypeId' => Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('COMM_Product').RecordTypeId
            }
        );
    }

    /**
     * @description Test method of COMM_OCI_Utils.generateProductList
     */
    @isTest
    static void generateProductListTest() {
        Test.startTest();
        List<Product2> productList = [SELECT id, ProductCode FROM Product2 LIMIT 1];
        List<String> fullDayProductsList = new List<String>();
        List<String> firstDayProductsList = new List<String>();
        List<String> lastDayProductsList = new List<String>();
        DateTime startDateTime = DateTime.newInstanceGMT(2024, 1, 1, 0, 0, 0);
        DateTime endDateTime = DateTime.newInstanceGMT(2024, 4, 1, 0, 0, 0);

        for (Product2 product : productList) {
            COMM_OCI_Utils.generateProductList(
                product.ProductCode,
                startDateTime,
                endDateTime,
                firstDayProductsList,
                fullDayProductsList,
                lastDayProductsList
            );
        }
        Test.stopTest();

        Assert.isFalse(firstDayProductsList.size() == 0, 'First Day is empty');
        Assert.isFalse(fullDayProductsList.size() == 0, 'Full Days is empty');
        Assert.isFalse(lastDayProductsList.size() == 0, 'Last Day is empty');
    }

    /**
     * @description Test method of COMM_OCI_Utils.getInventoryAPISetting
     */
    @isTest
    static void getInventoryAPISettingTest() {
        Test.startTest();
        String config = COMM_OCI_Utils.getInventoryAPISetting();
        Test.stopTest();
        Assert.isFalse(config == null, 'INVENTORY_API configuration not found');
    }

    /**
     * @description Test method of COMM_OCI_Utils.groupProductsByCategory
     */
    @isTest
    static void groupProductsByCategoryTest() {
        Map<String, List<String>> productsMap = new Map<String, List<String>>();

        Test.startTest();
        List<Product2> productList = new List<Product2>();
        productList = [
            SELECT Id, ProductCode, Family
            FROM Product2
            WHERE ProductCode = 'ParkProduct'
        ];
        productsMap = COMM_OCI_Utils.groupProductsByCategory(null, productList);
        Assert.isFalse(productsMap.size() == 0, 'Parking productsMap is empty');

        productsMap.clear();
        productList = [
            SELECT Id, ProductCode, Family
            FROM Product2
            WHERE ProductCode = 'SubscriptionProduct'
        ];
        productsMap = COMM_OCI_Utils.groupProductsByCategory(null, productList);
        Assert.isFalse(productsMap.size() == 0, 'Subscription productsMap is empty');

        productsMap.clear();
        productList = [
            SELECT Id, ProductCode, Family
            FROM Product2
            WHERE ProductCode = 'ProductWithoutFamily'
        ];
        try {
            productsMap = COMM_OCI_Utils.groupProductsByCategory(null, productList);
        } catch (Exception e) {
            Assert.isFalse(productsMap.size() != 0, 'productsMap without family is not expected');
        }
        Test.stopTest();
    }

    /**
     * @description Test method of COMM_OCI_Utils.generateLocationList Single Day
     */
    @isTest
    static void generateLocationListSingleDayTest() {
        String family = COMM_OCI_Constants.PRODUCT_FAMILY_PARKING;
        Datetime startDateTime = DateTime.newInstanceGMT(2024, 1, 1, 0, 0, 0);
        Datetime endDateTime = DateTime.newInstanceGMT(2024, 1, 1, 23, 59, 0);
        List<String> firstDayLocationsList = new List<String>();
        List<String> fullDayLocationsList = new List<String>();
        List<String> lastDayLocationsList = new List<String>();

        Test.startTest();
        COMM_OCI_Utils.generateLocationList(family, startDateTime, endDateTime, firstDayLocationsList, fullDayLocationsList, lastDayLocationsList);
        Test.stopTest();

        Assert.isFalse(firstDayLocationsList.size() == 0, 'First Day is empty');
        Assert.isFalse(fullDayLocationsList.size() != 0, 'Full Days is not empty');
        Assert.isFalse(lastDayLocationsList.size() != 0, 'Last Day is not empty');
    }

    /**
     * @description Test method of COMM_OCI_Utils.generateLocationList Multiple Days
     */
    @isTest
    static void generateLocationListMultipleDaysTest() {
        String family = COMM_OCI_Constants.PRODUCT_FAMILY_PARKING;
        Datetime startDateTime = DateTime.newInstanceGMT(2024, 1, 1, 0, 0, 0);
        Datetime endDateTime = DateTime.newInstanceGMT(2024, 1, 6, 23, 59, 0);
        List<String> firstDayLocationsList = new List<String>();
        List<String> fullDayLocationsList = new List<String>();
        List<String> lastDayLocationsList = new List<String>();

        Test.startTest();
        COMM_OCI_Utils.generateLocationList(family, startDateTime, endDateTime, firstDayLocationsList, fullDayLocationsList, lastDayLocationsList);
        Test.stopTest();

        Assert.isFalse(firstDayLocationsList.size() == 0, 'First Day is empty');
        Assert.isFalse(fullDayLocationsList.size() == 0, 'Full Days is empty');
        Assert.isFalse(lastDayLocationsList.size() == 0, 'Last Day is empty');
    }

    /**
     * @description Test method of COMM_OCI_Utils.generateLocationList Multiple Days Subscription
     */
    @isTest
    static void generateLocationSubscriptionTest() {
        String family = COMM_OCI_Constants.PRODUCT_FAMILY_SUBSCRIPTION;
        Datetime startDateTime = DateTime.newInstanceGMT(2024, 1, 1, 0, 0, 0);
        Datetime endDateTime = DateTime.newInstanceGMT(2024, 1, 6, 23, 59, 0);
        List<String> firstDayLocationsList = new List<String>();
        List<String> fullDayLocationsList = new List<String>();
        List<String> lastDayLocationsList = new List<String>();

        Test.startTest();
        COMM_OCI_Utils.generateLocationList(family, startDateTime, endDateTime, firstDayLocationsList, fullDayLocationsList, lastDayLocationsList);
        Test.stopTest();

        Assert.isFalse(firstDayLocationsList.size() == 0, 'First Day is empty');
        Assert.isFalse(fullDayLocationsList.size() == 0, 'Full Days is empty');
        Assert.isFalse(lastDayLocationsList.size() == 0, 'Last Day is empty');
    }

    /**
     * @description Test method of COMM_OCI_Utils.newGuid
     */
    @isTest
    static void newGuidTest() {
        String guid = COMM_OCI_Utils.newGuid();
        Assert.isFalse(guid == null, 'guid generation failed');
    }

    /**
     * @description Test method of COMM_OCI_Utils.generateProductLocationList to Products with Family different of Subscription
     */
    @isTest
    static void generateProductLocationListTest() {
        
        List<Product2> productList = new List<Product2>();
        productList = [
            SELECT id, ProductCode, Family
            FROM Product2
            WHERE ProductCode = 'ParkProduct'
        ];
        
        String apexRestRequestBodyMock =
            '{' +
            '   "products": [' +
            '       {' +
            '           "startDate": "2024-01-01T00:00:00",' +
            '           "endDate": "2024-01-03T23:00:00",' +
            '           "productId": "ParkProduct"' +
            '       }' +
            '   ]' +
            '}';

        COMM_WS_AvailabilityInput inputRequest = COMM_WS_AvailabilityInput.parse(apexRestRequestBodyMock);
        Map<String, List<String>> productDayByLocationMap = new Map<String, List<String>>();

        Test.startTest();
        Map<String, List<String>> productsMap = COMM_OCI_Utils.groupProductsByCategory(null, productList);
        COMM_OCI_Utils.generateProductLocationList('Others', inputRequest, productDayByLocationMap, productsMap);
        Test.stopTest();

        Assert.isFalse(productDayByLocationMap.size() == 0, 'ProductDayByLocationMap is empty');
    }
    
    /**
     * @description Test method of COMM_OCI_Utils.generateProductLocationList to Subscription Products
     */
    @isTest
    static void generateProductLocationSubscriptionListTest() {
        
        List<Product2> productList = new List<Product2>();
        productList = [
            SELECT id, ProductCode, Family
            FROM Product2
            WHERE ProductCode = 'SubscriptionProduct'
        ];
        
        String apexRestRequestBodyMock =
            '{' +
            '   "products": [' +
            '       {' +
            '           "startDate": "2024-01-01T00:00:00",' +
            '           "endDate": "2024-01-03T23:00:00",' +
            '           "productId": "SubscriptionProduct"' +
            '       }' +
            '   ]' +
            '}';

        COMM_WS_AvailabilityInput inputRequest = COMM_WS_AvailabilityInput.parse(apexRestRequestBodyMock);
        Map<String, List<String>> productDayByLocationMap = new Map<String, List<String>>();

        Test.startTest();
        Map<String, List<String>> productsMap = COMM_OCI_Utils.groupProductsByCategory(null, productList);
        COMM_OCI_Utils.generateProductLocationList(COMM_OCI_Constants.PRODUCT_FAMILY_SUBSCRIPTION, inputRequest, productDayByLocationMap, productsMap);
        Test.stopTest();

        Assert.isFalse(productDayByLocationMap.size() == 0, 'ProductDayByLocationMap is empty');
    }
}