force-app/main/default/objects/Account/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airports that the client will have access</description>
    <label>Airport</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_AirportTextList__c.field-meta.xml
<CustomField>
    <fullName>COMM_AirportTextList__c</fullName>
    <description>Field used on Sharing Rules. Due multi-picklist limitation.</description>
    <label>Airport Text List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_TW_Account_AirportUpdate.cls
/**
 * @author Daniel Lascas
 * @description Trigger worker that verifies if the multi-picklist COMM_Airport__c
 * was changed. If it was copy value to COMM_AirportTextList__c to update sharing.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    11/07/2024		ECOMM-1602: CR-33
 **/
public with sharing class COMM_TW_Account_AirportUpdate {
    /**
     * @description Execute Trigger Worker Logic.
     *
     * @param newAccountList List with the Account Records in after context.
     * @param oldAccountMap Map with the Account Records in before context.
     */
    public void execute(List<Account> newAccountList, Map<Id, Account> oldAccountMap) {
        for (Account newAccount : newAccountList) {
            //Verify Airport Field Changed
            if (COMM_GEN_Utility.isChangedField(newAccount, oldAccountMap, Account.COMM_Airport__c)) {
                newAccount.COMM_AirportTextList__c = newAccount.COMM_Airport__c;
            }
        }
    }
}