force-app/main/default/objects/Account/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airports that the client will have access</description>
    <label>Airport</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <label>License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>Unique number that identifies a taxable person (business) or non-taxable legal entity that is registered for VAT.</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_VehicleBrand__c.field-meta.xml
<CustomField>
    <fullName>COMM_VehicleBrand__c</fullName>
    <label>Vehicle Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_VehicleModel__c.field-meta.xml
<CustomField>
    <fullName>COMM_VehicleModel__c</fullName>
    <label>Vehicle Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <label>Airport</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_FirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstName__c</fullName>
    <label>Case First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_InitialSubscriptionMonth__c.field-meta.xml
<CustomField>
    <fullName>COMM_InitialSubscriptionMonth__c</fullName>
    <label>Initial Subscription Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_JobRole__c.field-meta.xml
<CustomField>
    <fullName>COMM_JobRole__c</fullName>
    <label>Job Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_LastName__c.field-meta.xml
<CustomField>
    <fullName>COMM_LastName__c</fullName>
    <label>Case Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <label>License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Park__c.field-meta.xml
<CustomField>
    <fullName>COMM_Park__c</fullName>
    <formula>TEXT(Product.COMM_Park__c)</formula>
    <label>Park</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <label>Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_PhoneNumber__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubCategory__c</fullName>
    <formula>COMM_Subscription__r.COMM_SubCategory__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub-Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>This is the unique number that identifies a taxable person (business) or non-taxable legal entity that is registered for VAT.</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_VehicleBrand__c.field-meta.xml
<CustomField>
    <fullName>COMM_VehicleBrand__c</fullName>
    <label>Vehicle Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_VehicleModel__c.field-meta.xml
<CustomField>
    <fullName>COMM_VehicleModel__c</fullName>
    <label>Vehicle Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/COMM_NewSubscription.recordType-meta.xml
<RecordType>
    <fullName>COMM_NewSubscription</fullName>
    <active>true</active>
    <businessProcess>New Subscription</businessProcess>
    <description>Case to renew a subscription manually</description>
    <label>New Subscription</label>
</RecordType>

force-app/main/default/objects/COMM_EmailTemplatesEncryptionSettings__c/COMM_EmailTemplatesEncryptionSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to set record detail encryption on email templates.</description>
    <label>Email Templates Encryption Settings</label>
</CustomObject>

force-app/main/default/objects/COMM_EmailTemplatesEncryptionSettings__c/fields/COMM_SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubscriptionKey__c</fullName>
    <description>Key used to encrypt Id of the Case related to a Subscription.</description>
    <label>Subscription Key</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Alarmistic__c.field-meta.xml
<CustomField>
    <fullName>COMM_Alarmistic__c</fullName>
    <description>The alarmistic percentage defined in this field will be the same for the default capacity and the capacity defined for a specific period.</description>
    <label>Alarmistic %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ClosingOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_ClosingOperatingHours__c</fullName>
    <description>Specific time during which the product stops being operational to be sold to the customers</description>
    <label>Closing Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_CPMS__c.field-meta.xml
<CustomField>
    <fullName>COMM_CPMS__c</fullName>
    <description>Which CPMS provider is associated with park where the reservation was done</description>
    <label>Parking System Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_CPMS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_OpeningOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_OpeningOperatingHours__c</fullName>
    <description>Specific time during which the product starts being operational to be sold to the customers</description>
    <label>Opening Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Park__c.field-meta.xml
<CustomField>
    <fullName>COMM_Park__c</fullName>
    <description>Park associated with the Product</description>
    <label>Park</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Park</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <description>Defines the periodicity of the subscription</description>
    <label>Subscription Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubCategory__c</fullName>
    <description>Used to define the sub-category of the product.</description>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Park</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Fast Lane</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Exempt Official Entity</fullName>
            </value>
            <value>
                <fullName>ANA + Entities</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>RAC / Shuttle NL</fullName>
            </value>
            <value>
                <fullName>Staff Company</fullName>
            </value>
            <value>
                <fullName>Staff Individual</fullName>
            </value>
            <value>
                <fullName>Fast Track Plus</fullName>
            </value>
            <value>
                <fullName>Lounge Adult</fullName>
            </value>
            <value>
                <fullName>Lounge Child</fullName>
            </value>
            <value>
                <fullName>Lounge Adult with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Child with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Non Schengen</fullName>
            </value>
            <value>
                <fullName>Terminal</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non -Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Adult Non -Schengen</label>
            </value>
            <value>
                <fullName>Lounge Child Non - Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Child Non - Schengen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Tax__c.field-meta.xml
<CustomField>
    <fullName>COMM_Tax__c</fullName>
    <description>Defines the tax used for the product based on location</description>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>COMM_Airport__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continent</fullName>
            </value>
            <value>
                <fullName>Madeira</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date for which the product is deemed valid</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/COMM_Subscription.recordType-meta.xml
<RecordType>
    <fullName>COMM_Subscription</fullName>
    <active>true</active>
    <description>This record type will used to typify subscriptions</description>
    <label>Subscription</label>
</RecordType>

force-app/main/default/classes/COMM_WS_PostFormDetailsTest.cls
/**
 * @author           Daniel Reto
 * @description      COMM_WS_PostFormDetails test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      29/10/2024      100            Original version
 **/
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
@isTest
private class COMM_WS_PostFormDetailsTest {
    @TestSetup
    static void makeData() {
        // Create Custom Setting record
        COMM_EmailTemplatesEncryptionSettings__c customSettingEmailTemplatesEncrypt = new COMM_EmailTemplatesEncryptionSettings__c();
        customSettingEmailTemplatesEncrypt.Name = 'Test Setting';
        customSettingEmailTemplatesEncrypt.COMM_SubscriptionKey__c = 'asdfghjklpoiuytr';
        insert customSettingEmailTemplatesEncrypt;
        
        //Products for Mocking Test
        List<Product2> productRecordList = (List<Product2>) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'T-0',
                'ProductCode' => 'T-0',
                'description' => 'T-0',
                'Family' => COMM_OCI_Constants.PRODUCT_FAMILY_SUBSCRIPTION,
                'isActive' => false,
                'COMM_Airport__c' => 'OPO',
                'COMM_Alarmistic__c' => 25,
                'COMM_ClosingOperatingHours__c' => Time.newInstance(0, 0, 0, 0),
                'COMM_OpeningOperatingHours__c' => Time.newInstance(0, 0, 0, 0),
                'COMM_ValidFrom__c' => DateTime.now().addDays(1),
                'COMM_ValidTo__c' => DateTime.now().addDays(2),
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_Park__c' => 'P3',
                'COMM_Periodicity__c' => null,
                'COMM_Tax__c' => 'Continent',
                'COMM_SubCategory__c' => 'Park',
                'RecordTypeId' => Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('COMM_Subscription').RecordTypeId
            }
        );

        //Mock Person Account
        Account accountRecord = (Account) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Account',
            new Map<String, Object>{
                'FirstName' => 'Test',
                'LastName' => 'User',
                'PersonEmail' => 'test@user.com.invalid'
            }
        )[0];
        
        //Case for Mocking Test
        Case caseRecord = (Case) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Case',
            new Map<String, Object>{
                'ProductId' => productRecordList[0].Id,
                'AccountId' => accountRecord.Id,
                'Status' => COMM_DO_Case.IN_APPROVAL_STATUS,
                'COMM_FirstName__c' => 'test',
                'COMM_LastName__c' => 'client',
                'COMM_PhoneNumber__c' => '+351 930123456',
                'COMM_VATNumber__c' => 'PT290765432',
                'SuppliedEmail' => 'test@client.invalid',
                'COMM_JobRole__c' => 'Manager',
                'COMM_LicensePlate__c' => '00-AA-01',
                'COMM_VehicleBrand__c' => 'FIAT',
                'COMM_VehicleModel__c' => 'Punto',
                'COMM_Address__Street__s' => 'Avenida Teste',
                'COMM_Address__City__s' => 'Lisbon',
                'COMM_Address__PostalCode__s' => '1500',
                'COMM_Address__CountryCode__s' => 'PT',
                'COMM_Periodicity__c' => 'Monthly',
                'COMM_InitialSubscriptionMonth__c' => 'January',
                'COMM_EndDate__c' => Date.today().addDays(-1),
                'COMM_StartDate__c' => Date.newInstance(Date.today().year(), 12, Date.today().day()).addYears(-1),
                'RecordTypeId' => COMM_GEN_Utility.getRecordTypeIdByDevName(Case.sObjectType, 'COMM_NewSubscription')
            }
        )[0];
    }

    @IsTest
    static void getPostFormDetailsSuccessResponseTest() {
        
        Case caseRecord = [SELECT Id FROM Case][0];
        String encryptedId = COMM_GEN_Utility.encryptRecordIdentifier(caseRecord.Id, COMM_GEN_Utility.SUBSCRIPTION_KEY_NAME);
        
        String apexRestRequestBodyMock =
            '{"caseId":"' + encryptedId + '", "personalFirstName":"Test", "personalLastName":"Test", "personalVAT":"123456789", "personalEmail":"test@test.com", "personalPhoneNumber":"911111111", "personalAddress":"Address Test", "personalZipCode":"1111-111", "personalCity":"Test City", "personalCountry":"Test Country", "jobRole":"Tester", "vehicleLicense":"AA-11-AA", "vehicleBrand":"Brand", "vehicleModel":"Model", "secondVehicleLicense":"", "secondVehicleBrand":"", "secondVehicleModel":"", "privacyConsent":"", "licenseReadingConsent":"", "marketingConsent":"", "formLanguage":"pt_PT", "status":"Waiting Approval", "fileName":"", "fileData":"", "airport":"LIS"}';

        // Build Request ApexRest
        String sfdcBaseURL = URL.getOrgDomainURL().toExternalForm();
        String endpoint = sfdcBaseURL + '/services/apexrest/postFormDetails';

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = endpoint; //Request URL
        req.httpMethod = 'POST'; //HTTP Request Type
        req.requestBody = Blob.valueof(apexRestRequestBodyMock);
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        COMM_WS_PostFormDetails.postFormDetails();
        Test.stopTest();

        // Asserts - Expecting a success response
        System.assertEquals(200, RestContext.response.statusCode, 'Expected a 200 HTTP status code.');
    }

    @IsTest
    static void getPostFormDetailsWrongDatesTest() {

        String caseId = fflib_IDGenerator.generate(Case.sObjectType);
        String encryptedId = COMM_GEN_Utility.encryptRecordIdentifier(caseId, COMM_GEN_Utility.SUBSCRIPTION_KEY_NAME);

        String apexRestRequestBodyMock = '';

        // Build Request ApexRest
        String sfdcBaseURL = URL.getOrgDomainURL().toExternalForm();
        String endpoint = sfdcBaseURL + '/services/apexrest/postFormDetails';

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = endpoint; //Request URL
        req.httpMethod = 'POST'; //HTTP Request Type
        req.requestBody = Blob.valueof(apexRestRequestBodyMock);
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        COMM_WS_PostFormDetails.postFormDetails();
        Test.stopTest();

        // Asserts - Expecting a failure response
        Assert.areEqual(500, RestContext.response.statusCode, 'Expected a 500 HTTP status code due to invalid input.');
    }
}