force-app/main/default/objects/Account/fields/COMM_BillingFirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_BillingFirstName__c</fullName>
    <description>First Name of the Person the Billing will be associated with.</description>
    <label>Billing First Name</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_BillingLastName__c.field-meta.xml
<CustomField>
    <fullName>COMM_BillingLastName__c</fullName>
    <description>Last Name of the Person the Billing will be associated with</description>
    <label>Billing Last Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_Email__c.field-meta.xml
<CustomField>
    <fullName>COMM_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <label>License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>COMM_PaymentMethod__c</fullName>
    <description>In this field, the ANA Admin defines the payment method associated to the account</description>
    <inlineHelpText>The Affiliates can pay by cash or credit
Partners can pay by cash, credit or/and courtesy
B2C can only pay by cash</inlineHelpText>
    <label>Payment Method</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VD</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_SecondaryLicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryLicensePlate__c</fullName>
    <label>Secondary License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>Unique number that identifies a taxable person (business) or non-taxable legal entity that is registered for VAT.</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/COMM_Subscription__c.object-meta.xml
<CustomObject>
    <description>Object to represent a Subscription associated with a Client</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SBS-{0000}</displayFormat>
        <label>Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Account__c.field-meta.xml
<CustomField>
    <fullName>COMM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account associated with the Subscription Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Contact__c.field-meta.xml
<CustomField>
    <fullName>COMM_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact associated with the Subscription Record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Email__c.field-meta.xml
<CustomField>
    <fullName>COMM_Email__c</fullName>
    <description>Email of the client associated with the Subscription</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EndDate__c</fullName>
    <description>Date when the Subscription is scheduled to end</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_FirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstName__c</fullName>
    <description>First Name of the Client associated with the Subscription</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_InitialSubscriptionMonth__c.field-meta.xml
<CustomField>
    <fullName>COMM_InitialSubscriptionMonth__c</fullName>
    <description>Month where the Subscription will initially start</description>
    <label>Initial Subscription Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_LastName__c.field-meta.xml
<CustomField>
    <fullName>COMM_LastName__c</fullName>
    <description>Last Name of the Client associated with the Subscription</description>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <description>License Plate of the Vehicle associated with the Subscription</description>
    <label>License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Order__c.field-meta.xml
<CustomField>
    <fullName>COMM_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order associated with the Subscription</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order Product associated with the Subscription</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_OrderSummary__c.field-meta.xml
<CustomField>
    <fullName>COMM_OrderSummary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order Summary  associated with the Subscription</description>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>COMM_PaymentMethod__c</fullName>
    <description>Picklist field with Payment Method selected for Subscription acquisition.</description>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_PaymentType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <description>Defines the periodicity of the subscription</description>
    <label>Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_PhoneNumber__c</fullName>
    <description>Phone Number of the Client associated with the Subscription</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Price__c.field-meta.xml
<CustomField>
    <fullName>COMM_Price__c</fullName>
    <description>Price of all products: Subscription or Subscription + Card</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product the Subscription is associated with</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Subscription can only be associated with a Subscription Product</errorMessage>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>COMM_Subscription</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_SecondaryLicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryLicensePlate__c</fullName>
    <description>License Plate of a Secondary Vehicle associated with the Subscription</description>
    <label>Secondary License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_StartDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date when the Subscription starts</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Status__c.field-meta.xml
<CustomField>
    <fullName>COMM_Status__c</fullName>
    <description>Current Status of the Subscription</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Approval</fullName>
                <default>true</default>
                <label>In Approval</label>
            </value>
            <value>
                <fullName>Waiting Conclusion</fullName>
            </value>
            <value>
                <fullName>Process Concluded</fullName>
            </value>
            <value>
                <fullName>Request Denied</fullName>
            </value>
            <value>
                <fullName>Archieved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Pending Form</fullName>
                <isActive>false</isActive>
                <label>Pending Form</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>VAT Number of the Client associated with the Subscription</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/recordTypes/COMM_DirectSales.recordType-meta.xml
<RecordType>
    <fullName>COMM_DirectSales</fullName>
    <active>true</active>
    <description>Represents a Subscription associated with Direct Sales</description>
    <label>Direct Sales</label>
</RecordType>

force-app/main/default/objects/COMM_Subscription__c/recordTypes/COMM_Partner.recordType-meta.xml
<RecordType>
    <fullName>COMM_Partner</fullName>
    <active>true</active>
    <description>Represents a Subscription associated with a Partner</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/OrderItemSummary/fields/COMM_AffiliateNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_AffiliateNumber__c</fullName>
    <label>Affiliate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <description>License plate to communicate with CPMS</description>
    <label>Reservation License Plate</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/COMM_ReservationEnd__c.field-meta.xml
<CustomField>
    <fullName>COMM_ReservationEnd__c</fullName>
    <description>Used for stock reservation (end date time)</description>
    <label>Reservation End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/COMM_ReservationStart__c.field-meta.xml
<CustomField>
    <fullName>COMM_ReservationStart__c</fullName>
    <description>Used for stock reservation (start date time)</description>
    <label>Reservation Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/COMM_SecondaryLicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryLicensePlate__c</fullName>
    <label>Reservation Secondary License Plate</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>COMM_Periodicity__c</fullName>
    <description>Defines the periodicity of the subscription</description>
    <label>Subscription Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Periodicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/COMM_DO_Subscription.cls
/**
 * @author           Daniel Reto
 * @description      Subscription SObject Domain object class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      09/04/2024       ECOMM-192: Original version
 * Sofia Silva      17/10/2025       TICKET-280170: Add payment method to Public Subscription creation (always VD)
 **/
public inherited sharing class COMM_DO_Subscription implements COMM_IDO_Subscription {
    //Subscription Record Type Values
    public final static string RECORDTYPE_PARTNER = 'COMM_Partner';
    public final static string RECORDTYPE_DIRECT_SALES = 'COMM_DirectSales';
    //Subscription Status Picklist Values
    public final static string STATUS_PROCESS_CONCLUDED = 'Process Concluded';
    public final static string STATUS_ARCHIEVED = 'Archieved';
    public final static string STATUS_WAITING_CONCLUSION = 'Waiting Conclusion';
    //Subscription Periodicity Picklist Values
    public final static string PERIODICITY_MONTHLY = 'Monthly';
    public final static string PERIODICITY_QUARTERLY = 'Quarterly';
    public final static string PERIODICITY_HALF_YEARLY = 'Half Yearly';
    public final static string PERIODICITY_YEARLY = 'Yearly';
    //Subscription Payment Method
    public final static string PAYMENT_VD = 'VD';
    public final static string PAYMENT_CREDIT = 'Credit';
    public final static string PAYMENT_COURTESY = 'Courtesy';

    /**
     * @description Define Subscription records to be created base on Order Item Summary record details.
     * @param orderItemSummary List of Order Item Summary records to process.
     * @return Subscription record to be created.
     */
    public static COMM_Subscription__c setSubscriptionToCreate(OrderItemSummary orderItemSummary) {
        COMM_Subscription__c subscriptionToCreate = new COMM_Subscription__c();
        subscriptionToCreate.COMM_Order__c = orderItemSummary.OriginalOrderItem.OrderId;
        subscriptionToCreate.COMM_OrderProduct__c = orderItemSummary.OriginalOrderItemId;
        subscriptionToCreate.COMM_OrderSummary__c = orderItemSummary.OrderSummaryId;
        subscriptionToCreate.RecordTypeId = Schema.SObjectType.COMM_Subscription__c.getRecordTypeInfosByDeveloperName()
            .get(RECORDTYPE_DIRECT_SALES)
            .RecordTypeId;
        subscriptionToCreate.COMM_Account__c = orderItemSummary.OriginalOrderItem.Order.AccountId;
        subscriptionToCreate.COMM_Contact__c = orderItemSummary.OriginalOrderItem.Order.BillToContactId;
        subscriptionToCreate.COMM_Status__c = STATUS_WAITING_CONCLUSION;
        subscriptionToCreate.COMM_Price__c = orderItemSummary.OriginalOrderItem.TotalPrice;
        subscriptionToCreate.COMM_Product__c = orderItemSummary.OriginalOrderItem.Product2Id;
        subscriptionToCreate.COMM_InitialSubscriptionMonth__c = datetime.now().format('MMMM');
        subscriptionToCreate.COMM_StartDate__c = orderItemSummary.OriginalOrderItem.COMM_ReservationStart__c?.date();
        subscriptionToCreate.COMM_EndDate__c = orderItemSummary.OriginalOrderItem.COMM_ReservationEnd__c?.date();
        subscriptionToCreate.COMM_LicensePlate__c = orderItemSummary.OriginalOrderItem.COMM_LicensePlate__c;
        subscriptionToCreate.COMM_SecondaryLicensePlate__c = orderItemSummary.OriginalOrderItem.COMM_SecondaryLicensePlate__c;
        subscriptionToCreate.COMM_AffiliateNumber__c = orderItemSummary.OriginalOrderItem.COMM_AffiliateNumber__c;
        subscriptionToCreate.COMM_Periodicity__c = orderItemSummary.OriginalOrderItem.Product2.COMM_Periodicity__c;
        subscriptionToCreate.COMM_FirstName__c = orderItemSummary.OriginalOrderItem.Order.Account.COMM_BillingFirstName__c;
        subscriptionToCreate.COMM_LastName__c = orderItemSummary.OriginalOrderItem.Order.Account.COMM_BillingLastName__c;
        subscriptionToCreate.COMM_VATNumber__c = orderItemSummary.OriginalOrderItem.Order.Account.COMM_VATNumber__c;
        subscriptionToCreate.COMM_PhoneNumber__c = orderItemSummary.OriginalOrderItem.Order.Account.IsPersonAccount ? orderItemSummary.OriginalOrderItem.Order.Account.PersonMobilePhone : orderItemSummary.OriginalOrderItem.Order.Account.Phone;
        subscriptionToCreate.COMM_Email__c = orderItemSummary.OrderSummary.Account.RecordType.DeveloperName ==
            COMM_DO_Account.PERSON_ACCOUNT_RECORD_TYPE
            ? orderItemSummary.OrderSummary.Account.PersonEmail
            : orderItemSummary.OrderSummary.Account.COMM_Email__c;
        subscriptionToCreate.COMM_Address__Street__s = orderItemSummary.OriginalOrderItem.Order.Account.BillingStreet;
        subscriptionToCreate.COMM_Address__City__s = orderItemSummary.OriginalOrderItem.Order.Account.BillingCity;
        subscriptionToCreate.COMM_Address__CountryCode__s = orderItemSummary.OriginalOrderItem.Order.Account.BillingCountryCode;
        subscriptionToCreate.COMM_Address__PostalCode__s = orderItemSummary.OriginalOrderItem.Order.Account.BillingPostalCode;
        subscriptionToCreate.COMM_PaymentMethod__c = PAYMENT_VD;

        return subscriptionToCreate;
    }
}