force-app/main/default/objects/Account/fields/COMM_ResellerId__c.field-meta.xml
<CustomField>
    <fullName>COMM_ResellerId__c</fullName>
    <description>Field containing the reseller id for the account</description>
    <label>Reseller Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <label>Batch Definition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <inlineHelpText>This is used programmatically to execute the batch.</inlineHelpText>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Finished_with_Errors</fullName>
                <label>Finished with Errors</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/COMM_ResellerVoucherStatus__c.field-meta.xml
<CustomField>
    <fullName>COMM_ResellerVoucherStatus__c</fullName>
    <description>Status of integration between Salesforce and Mulesoft for Reseller Order Voucher</description>
    <label>Reseller Voucher Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>FATAL_ERROR</fullName>
            </value>
            <value>
                <fullName>INTEGRATED</fullName>
            </value>
            <value>
                <fullName>RETRY_EXHAUSTED</fullName>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/COMM_ResellerVoucherStatusDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_ResellerVoucherStatusDate__c</fullName>
    <label>Reseller Voucher Status Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Defines the value of the parameter, can be a set of Ids, a status value, a constant etc</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/COMM_Async_OrderVoucherIntegrRetryTest.cls
/**
 * @author Daniel Reto
 * @description COMM_Async_OrderVoucherIntegrRetry test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date          Coverage(%)   Description
 * ----------------------------------------------------------------------------------------------
 * Daniel Reto      30/10/2024    100           Original version - ECOMM-327
 **/
@isTest
private class COMM_Async_OrderVoucherIntegrRetryTest {
    private final static fflib_ApexMocks MOCKS = new fflib_ApexMocks();
    private final static COMM_IREP_OrderSummary ORDERSUMMARY_REP = (COMM_REP_OrderSummary) MOCKS.mock(COMM_REP_OrderSummary.class);
    private final static FW_IREP_JobExecution JOB_EXECUTION_REP = (FW_REP_JobExecution) MOCKS.mock(FW_REP_JobExecution.class);
    private final static FW_IREP_Parameters PARAMETERS_REP = (FW_REP_Parameters) MOCKS.mock(FW_REP_Parameters.class);

    @testSetup
    static void setup() {
        Id orderId = COMM_OMS_TestDataFactory.createOrderAndRelated();


    }

    @isTest
    private static void executeSuccessTest() {
        //Create Mocked Batch_Definition Record
        List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>{
            new Batch_Definition__c(
                Id = fflib_IDGenerator.generate(Batch_Definition__c.sObjectType),
                Batch_Name__c = 'Reseller Order Voucher Integration',
                Class_Name__c = 'COMM_Async_OrderVoucherIntegrRetry',
                Job_Size__c = 100,
                SObject_API_Name__c = 'OrderSummary'
            )
        };

        //Create Mocked JobExecution Record
        List<Job_Execution__c> jobExecutionList = new List<Job_Execution__c>{
            new Job_Execution__c(
                Id = fflib_IDGenerator.generate(Job_Execution__c.sObjectType),
                Batch_Definition__c = batchDefinitionList[0].Id,
                Run_With_Defaults__c = true,
                Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_NEW
            )
        };

        //Create Mocked Parameters Record
        List<Parameters__c> parametersList = new List<Parameters__c>{
            new Parameters__c(Id = fflib_IDGenerator.generate(Parameters__c.sObjectType), Name = FW_AsyncHandler.DEFAULT_PARAMETER),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = COMM_Async_OrderVoucherIntegrRetry.PARAMETER_MAX_ATTEMPTS,
                Value__c = '5'
            ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = COMM_Async_OrderVoucherIntegrRetry.PARAMETER_RETRY_CYCLE,
                Value__c = '1'
            )
        };

        //OrderSummary for Mocking Test
        List<SObjectField> ACCOUNT_FIELDS = new List<SObjectField>{ Account.COMM_ResellerId__c };
        String queryOrderSummary = new FW_QueryBuilder(OrderSummary.sObjectType)
            .selectFields(COMM_REP_OrderSummary.ORDERSUMMARY_FIELDS)
            .selectParentFields(OrderSummary.AccountId, ACCOUNT_FIELDS)
            .getQuery();

        DateTime resellerVoucherStatusDate = Datetime.now().addHours(-1);
        List<OrderSummary> orderSummaryRecordList = (List<OrderSummary>) Database.query(queryOrderSummary);
        for(OrderSummary orderSummaryRecord : orderSummaryRecordList){
            orderSummaryRecord.COMM_ResellerVoucherStatus__c = COMM_DO_OrderSummary.ERROR_RESELLER_VOUCHER_STATUS;
            orderSummaryRecord.COMM_ResellerVoucherStatusDate__c = resellerVoucherStatusDate;
        }

        //Expected OrderSummary for Mocking Test
        List<OrderSummary> expectedOrderSummaryRecordList = (List<OrderSummary>) Database.query(queryOrderSummary);
        for(OrderSummary orderSummaryRecord : orderSummaryRecordList){
            orderSummaryRecord.COMM_ResellerVoucherStatus__c = COMM_DO_OrderSummary.SENT_RESELLER_VOUCHER_STATUS;
            orderSummaryRecord.COMM_ResellerVoucherStatusDate__c = resellerVoucherStatusDate;
        }

        //Mock Queries
        MOCKS.startStubbing();
        MOCKS.when(ORDERSUMMARY_REP.updateSObjects(expectedOrderSummaryRecordList)).thenReturn(new List<Database.SaveResult>());
        MOCKS.when(JOB_EXECUTION_REP.getJobExecWithBatchDefinitionsByIdSet((Set<Id>) fflib_match.anyObject())).thenReturn(jobExecutionList);
        MOCKS.when(JOB_EXECUTION_REP.getJobExecutionByAsyncApexJobIdSet((Id) fflib_match.anyObject())).thenReturn(jobExecutionList);
        MOCKS.when(PARAMETERS_REP.getParametersByParentId((Set<Id>) fflib_match.anyObject())).thenReturn(parametersList);
        MOCKS.stopStubbing();

        //Start Test
        Test.startTest();
        Boolean errorOccured = false;
        try {
            COMM_Async_OrderVoucherIntegrRetry newBatchRun = new COMM_Async_OrderVoucherIntegrRetry();
            newBatchRun = new COMM_Async_OrderVoucherIntegrRetry(ORDERSUMMARY_REP, JOB_EXECUTION_REP, PARAMETERS_REP);
            Database.executeBatch(newBatchRun);
            newBatchRun.setAsyncApexJobId(null);
            newBatchRun.execute(null, orderSummaryRecordList);
        } catch (Exception e) {
            errorOccured = true;
        }
        Test.stopTest();

        Assert.isFalse(errorOccured, 'User Obfuscated and Account deleted');
    }

    @isTest
    private static void executeSuccessOutOfMaxTimeTest() {
        //Create Mocked Batch_Definition Record
        List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>{
            new Batch_Definition__c(
                Id = fflib_IDGenerator.generate(Batch_Definition__c.sObjectType),
                Batch_Name__c = 'Reseller Order Voucher Integration',
                Class_Name__c = 'COMM_Async_OrderVoucherIntegrRetry',
                Job_Size__c = 100,
                SObject_API_Name__c = 'OrderSummary'
            )
        };

        //Create Mocked JobExecution Record
        List<Job_Execution__c> jobExecutionList = new List<Job_Execution__c>{
            new Job_Execution__c(
                Id = fflib_IDGenerator.generate(Job_Execution__c.sObjectType),
                Batch_Definition__c = batchDefinitionList[0].Id,
                Run_With_Defaults__c = true,
                Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_NEW
            )
        };

        //Create Mocked Parameters Record
        List<Parameters__c> parametersList = new List<Parameters__c>{
            new Parameters__c(Id = fflib_IDGenerator.generate(Parameters__c.sObjectType), Name = FW_AsyncHandler.DEFAULT_PARAMETER),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = COMM_Async_OrderVoucherIntegrRetry.PARAMETER_MAX_ATTEMPTS,
                Value__c = '5'
            ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = COMM_Async_OrderVoucherIntegrRetry.PARAMETER_RETRY_CYCLE,
                Value__c = '1'
            )
        };

        //OrderSummary for Mocking Test
        List<SObjectField> ACCOUNT_FIELDS = new List<SObjectField>{ Account.COMM_ResellerId__c };
        String queryOrderSummary = new FW_QueryBuilder(OrderSummary.sObjectType)
            .selectFields(COMM_REP_OrderSummary.ORDERSUMMARY_FIELDS)
            .selectParentFields(OrderSummary.AccountId, ACCOUNT_FIELDS)
            .getQuery();

        DateTime resellerVoucherStatusDate = Datetime.now().addHours(-10);
        List<OrderSummary> orderSummaryRecordList = (List<OrderSummary>) Database.query(queryOrderSummary);
        for(OrderSummary orderSummaryRecord : orderSummaryRecordList){
            orderSummaryRecord.COMM_ResellerVoucherStatus__c = COMM_DO_OrderSummary.ERROR_RESELLER_VOUCHER_STATUS;
            orderSummaryRecord.COMM_ResellerVoucherStatusDate__c = resellerVoucherStatusDate;
        }

        //Expected OrderSummary for Mocking Test
        List<OrderSummary> expectedOrderSummaryRecordList = (List<OrderSummary>) Database.query(queryOrderSummary);
        for(OrderSummary orderSummaryRecord : orderSummaryRecordList){
            orderSummaryRecord.COMM_ResellerVoucherStatus__c = COMM_DO_OrderSummary.RETRY_EXHAUSTED_RESELLER_VOUCHER_STATUS;
            orderSummaryRecord.COMM_ResellerVoucherStatusDate__c = resellerVoucherStatusDate;
        }

        //Mock Queries
        MOCKS.startStubbing();
        MOCKS.when(ORDERSUMMARY_REP.updateSObjects(expectedOrderSummaryRecordList)).thenReturn(new List<Database.SaveResult>());
        MOCKS.when(JOB_EXECUTION_REP.getJobExecWithBatchDefinitionsByIdSet((Set<Id>) fflib_match.anyObject())).thenReturn(jobExecutionList);
        MOCKS.when(JOB_EXECUTION_REP.getJobExecutionByAsyncApexJobIdSet((Id) fflib_match.anyObject())).thenReturn(jobExecutionList);
        MOCKS.when(PARAMETERS_REP.getParametersByParentId((Set<Id>) fflib_match.anyObject())).thenReturn(parametersList);
        MOCKS.stopStubbing();

        //Start Test
        Test.startTest();
        Boolean errorOccured = false;
        try {
            COMM_Async_OrderVoucherIntegrRetry newBatchRun = new COMM_Async_OrderVoucherIntegrRetry();
            newBatchRun = new COMM_Async_OrderVoucherIntegrRetry(ORDERSUMMARY_REP, JOB_EXECUTION_REP, PARAMETERS_REP);
            Database.executeBatch(newBatchRun);
            newBatchRun.setAsyncApexJobId(null);
            newBatchRun.execute(null, orderSummaryRecordList);
        } catch (Exception e) {
            errorOccured = true;
        }
        Test.stopTest();

        Assert.isFalse(errorOccured, 'User Obfuscated and Account deleted');
    }
}