force-app/main/default/objects/Account/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airports that the client will have access</description>
    <label>Airport</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <label>License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_SecondaryLicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryLicensePlate__c</fullName>
    <label>Secondary License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>Unique number that identifies a taxable person (business) or non-taxable legal entity that is registered for VAT.</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_VehicleBrand__c.field-meta.xml
<CustomField>
    <fullName>COMM_VehicleBrand__c</fullName>
    <label>Vehicle Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_VehicleModel__c.field-meta.xml
<CustomField>
    <fullName>COMM_VehicleModel__c</fullName>
    <label>Vehicle Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <label>Airport</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Card__c.field-meta.xml
<CustomField>
    <fullName>COMM_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_CardPrice__c.field-meta.xml
<CustomField>
    <fullName>COMM_CardPrice__c</fullName>
    <description>Field with the Price of a Card related on Subscription on Case.</description>
    <label>Card Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_FirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstName__c</fullName>
    <label>Case First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_JobRole__c.field-meta.xml
<CustomField>
    <fullName>COMM_JobRole__c</fullName>
    <label>Job Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_LastName__c.field-meta.xml
<CustomField>
    <fullName>COMM_LastName__c</fullName>
    <label>Case Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <label>License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_NewCardRequest__c.field-meta.xml
<CustomField>
    <fullName>COMM_NewCardRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Card Request?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_PhoneNumber__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SecondaryLicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryLicensePlate__c</fullName>
    <label>Secondary License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SecondaryVehicleBrand__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryVehicleBrand__c</fullName>
    <label>Secondary Vehicle Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SecondaryVehicleModel__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryVehicleModel__c</fullName>
    <label>Secondary Vehicle Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Subscription__c.field-meta.xml
<CustomField>
    <fullName>COMM_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>COMM_Subscription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SubscriptionPrice__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubscriptionPrice__c</fullName>
    <description>Field with the Price of a Subscription related on Case.</description>
    <label>Subscription Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>This is the unique number that identifies a taxable person (business) or non-taxable legal entity that is registered for VAT.</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_VehicleBrand__c.field-meta.xml
<CustomField>
    <fullName>COMM_VehicleBrand__c</fullName>
    <label>Vehicle Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_VehicleModel__c.field-meta.xml
<CustomField>
    <fullName>COMM_VehicleModel__c</fullName>
    <label>Vehicle Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/COMM_Subscription__c.object-meta.xml
<CustomObject>
    <description>Object to represent a Subscription associated with a Client</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SBS-{0000}</displayFormat>
        <label>Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport the Subscription is associated with</description>
    <formula>CASE(COMM_Product__r.COMM_Airport__c,
&quot;OPO&quot;, &quot;Porto&quot;,
&quot;LIS&quot;,&quot;Lisbon&quot;,
&quot;FAO&quot;,&quot;Faro&quot;,
&quot;FNC&quot;,&quot;Madeira&quot;,
&quot;PDL&quot;,&quot;Ponta Delgada&quot;,
&quot;&quot;)</formula>
    <label>Airport</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Card__c.field-meta.xml
<CustomField>
    <fullName>COMM_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Card to be included with the Subscription</description>
    <label>Card</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Associated Product can only be a Card</errorMessage>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Card</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions (Card)</relationshipLabel>
    <relationshipName>CardSubscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_FirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstName__c</fullName>
    <description>First Name of the Client associated with the Subscription</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_JobRole__c.field-meta.xml
<CustomField>
    <fullName>COMM_JobRole__c</fullName>
    <description>Job Role of the Client associated with the Subscription</description>
    <label>Job Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_LastName__c.field-meta.xml
<CustomField>
    <fullName>COMM_LastName__c</fullName>
    <description>Last Name of the Client associated with the Subscription</description>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_LicensePlate__c</fullName>
    <description>License Plate of the Vehicle associated with the Subscription</description>
    <label>License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_PhoneNumber__c</fullName>
    <description>Phone Number of the Client associated with the Subscription</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_SecondaryLicensePlate__c.field-meta.xml
<CustomField>
    <fullName>COMM_SecondaryLicensePlate__c</fullName>
    <description>License Plate of a Secondary Vehicle associated with the Subscription</description>
    <label>Secondary License Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>VAT Number of the Client associated with the Subscription</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_REP_Case.cls
/**
 * @author           Daniel Lascas
 * @description      Case repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    18/03/2024       ECOMM-368: Original version
 * Daniel Lascas    18/03/2024       ECOMM-194: Added getSubscriptionCaseByIds
 **/
public inherited sharing class COMM_REP_Case extends FW_SobjectRep implements COMM_IREP_Case {
    /**
     * @description Query Cases of Record Type "Individual Staff Request" that are on "In Pending"
     * status associated with a set of Accounts
     *
     * @param accountIds Set of Account Id's to find Cases related to it
     * @param securityEnforced Uses the security enforced clause or not.
     * @return List of Queried Case Records
     */
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public List<Case> getIndividualStaffRequestPendingByAccountId(Set<Id> accountIds, Boolean securityEnforced) {
        if (securityEnforced) {
            return [
                SELECT Id
                FROM Case
                WHERE
                    RecordType.DeveloperName = :COMM_DO_Case.INDIVIDUAL_STAFF_REQUEST_RT
                    AND Status = :COMM_DO_Case.IN_APPROVAL_STATUS
                    AND AccountId IN :accountIds
                WITH USER_MODE
            ];
        } else {
            return [
                SELECT Id
                FROM Case
                WHERE
                    RecordType.DeveloperName = :COMM_DO_Case.INDIVIDUAL_STAFF_REQUEST_RT
                    AND Status IN (:COMM_DO_Case.IN_APPROVAL_STATUS, :COMM_DO_Case.WAITING_APPROVAL_STATUS)
                    AND AccountId IN :accountIds
            ];
        }
    }

    /**
     * @description Query Cases by specified identifiers
     *
     * @param caseIds Set of Case Id's
     * @return List of Queried Case Records
     */
    public List<Case> getCasesByCaseIds(Set<Id> caseIds) {
        return [
            SELECT
                Id,
                COMM_FirstName__c,
                COMM_LastName__c,
                COMM_VATNumber__c,
                COMM_Address__Street__s,
                COMM_Address__City__s,
                COMM_Address__CountryCode__s,
                COMM_Address__PostalCode__s,
                COMM_PhoneNumber__c,
                SuppliedEmail,
                COMM_JobRole__c,
                COMM_VehicleBrand__c,
                COMM_VehicleModel__c,
                COMM_LicensePlate__c,
                COMM_SecondaryVehicleBrand__c,
                COMM_SecondaryVehicleModel__c,
                COMM_SecondaryLicensePlate__c,
                RecordType.Name,
                RecordType.DeveloperName,
                COMM_Airport__c,
                Status
            FROM Case
            WHERE Id IN :caseIds
        ];
    }

    /**
     * @description Query Subscription Cases with a set of Ids
     *
     * @param caseIds Set of Case Id's to query
     * @param securityEnforced Uses the security enforced clause or not.
     * @return List of Queried Case Records
     */
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public List<Case> getSubscriptionCaseByIds(Set<Id> caseIds, Boolean securityEnforced) {
        if (securityEnforced) {
            return [
                SELECT
                    Id,
                    AccountId,
                    COMM_Card__c,
                    COMM_NewCardRequest__c,
                    COMM_Subscription__c,
                    ProductId,
                    COMM_SubscriptionPrice__c,
                    COMM_CardPrice__c,
                    RecordType.DeveloperName
                FROM Case
                WHERE Id IN :caseIds
                WITH USER_MODE
            ];
        } else {
            return [
                SELECT
                    Id,
                    AccountId,
                    COMM_Card__c,
                    COMM_NewCardRequest__c,
                    COMM_Subscription__c,
                    ProductId,
                    COMM_SubscriptionPrice__c,
                    COMM_CardPrice__c,
                    RecordType.DeveloperName
                FROM Case
                WHERE Id IN :caseIds
            ];
        }
    }
}