force-app/main/default/objects/Account/fields/COMM_Email__c.field-meta.xml
<CustomField>
    <fullName>COMM_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Active__c.field-meta.xml
<CustomField>
    <fullName>COMM_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Card__c.field-meta.xml
<CustomField>
    <fullName>COMM_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_CardPrice__c.field-meta.xml
<CustomField>
    <fullName>COMM_CardPrice__c</fullName>
    <description>Field with the Price of a Card related on Subscription on Case.</description>
    <label>Card Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_FirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstName__c</fullName>
    <label>Case First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_NewCardRequest__c.field-meta.xml
<CustomField>
    <fullName>COMM_NewCardRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Card Request?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_Subscription__c.field-meta.xml
<CustomField>
    <fullName>COMM_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>COMM_Subscription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/COMM_SubscriptionPrice__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubscriptionPrice__c</fullName>
    <description>Field with the Price of a Subscription related on Case.</description>
    <label>Subscription Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/COMM_Subscription__c.object-meta.xml
<CustomObject>
    <description>Object to represent a Subscription associated with a Client</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SBS-{0000}</displayFormat>
        <label>Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Account__c.field-meta.xml
<CustomField>
    <fullName>COMM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account associated with the Subscription Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Active__c.field-meta.xml
<CustomField>
    <fullName>COMM_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if the Subscription is currently Active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_AutomaticRenewal__c.field-meta.xml
<CustomField>
    <fullName>COMM_AutomaticRenewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbos to identify if Subscription record must be renewed automatically.</description>
    <label>Automatic Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_CancellationDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_CancellationDate__c</fullName>
    <description>Field used to store the exact date when a Subscription is canceled</description>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_CarBrand__c.field-meta.xml
<CustomField>
    <fullName>COMM_CarBrand__c</fullName>
    <description>Brand of the Vehicle associated with the Subscription</description>
    <label>Car Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Card__c.field-meta.xml
<CustomField>
    <fullName>COMM_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Card to be included with the Subscription</description>
    <label>Card</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Associated Product can only be a Card</errorMessage>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Card</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions (Card)</relationshipLabel>
    <relationshipName>CardSubscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_CarModel__c.field-meta.xml
<CustomField>
    <fullName>COMM_CarModel__c</fullName>
    <description>Model of the Vehicle associated with the Subscription</description>
    <label>Car Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Contact__c.field-meta.xml
<CustomField>
    <fullName>COMM_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact associated with the Subscription Record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Email__c.field-meta.xml
<CustomField>
    <fullName>COMM_Email__c</fullName>
    <description>Email of the client associated with the Subscription</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EndDate__c</fullName>
    <description>Date when the Subscription is scheduled to end</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_FirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FirstName__c</fullName>
    <description>First Name of the Client associated with the Subscription</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Price__c.field-meta.xml
<CustomField>
    <fullName>COMM_Price__c</fullName>
    <description>Price of all products: Subscription or Subscription + Card</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/COMM_Subscription__c/fields/COMM_Status__c.field-meta.xml
<CustomField>
    <fullName>COMM_Status__c</fullName>
    <description>Current Status of the Subscription</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Approval</fullName>
                <default>true</default>
                <label>In Approval</label>
            </value>
            <value>
                <fullName>Waiting Conclusion</fullName>
            </value>
            <value>
                <fullName>Process Concluded</fullName>
            </value>
            <value>
                <fullName>Request Denied</fullName>
            </value>
            <value>
                <fullName>Archieved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Pending Form</fullName>
                <isActive>false</isActive>
                <label>Pending Form</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/COMM_SubscriptionInvoice__c.object-meta.xml
<CustomObject>
    <description>Represents an Invoice for a Subscription</description>
    <label>Subscription Invoice</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Subscription Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_Account__c.field-meta.xml
<CustomField>
    <fullName>COMM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account associated with the invoice</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Invoices</relationshipLabel>
    <relationshipName>SubscriptionInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_CardAmount__c.field-meta.xml
<CustomField>
    <fullName>COMM_CardAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount payed for the card (when requested)</description>
    <label>Card Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_CardProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_CardProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Card Product associated with the Invoice</description>
    <label>Card Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Card Product must be Category=card</errorMessage>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Card</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Invoices (Card)</relationshipLabel>
    <relationshipName>SubscriptionInvoicesCard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_Status__c.field-meta.xml
<CustomField>
    <fullName>COMM_Status__c</fullName>
    <description>Status of the Invoice</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_SubscriptionAmount__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubscriptionAmount__c</fullName>
    <description>Subscription Amount transferred in the invoice</description>
    <label>Subscription Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_Subscripton__c.field-meta.xml
<CustomField>
    <fullName>COMM_Subscripton__c</fullName>
    <description>The Subscription that generated the Invoice</description>
    <label>Subscripton</label>
    <referenceTo>COMM_Subscription__c</referenceTo>
    <relationshipLabel>Subscription Invoices</relationshipLabel>
    <relationshipName>SubscriptionInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_SubscriptonProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubscriptonProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Subscription Product associated with the Invoice</description>
    <label>Subscripton Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Invoices</relationshipLabel>
    <relationshipName>SubscriptionInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoice__c/fields/COMM_SubscriptonRequest__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubscriptonRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Request that started the Subscription</description>
    <label>Subscripton Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Subscription Invoices</relationshipLabel>
    <relationshipName>SubscriptionInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_SubscriptionInvoiceGenerator__e/COMM_SubscriptionInvoiceGenerator__e.object-meta.xml
<CustomObject>
    <description>Platform Event to generate a Subscription Invoice Record</description>
    <label>Subscription Invoice Generator</label>
    <pluralLabel>Subscription Invoice Generators</pluralLabel>
</CustomObject>

force-app/main/default/objects/COMM_SubscriptionInvoiceGenerator__e/fields/COMM_CaseId__c.field-meta.xml
<CustomField>
    <fullName>COMM_CaseId__c</fullName>
    <description>Id of the Case the Subscription Invoice will be related to</description>
    <label>Case Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_TW_SubInvGen_GenerateInvoiceTest.cls
/**
 * @author Daniel Lascas
 * @description COMM_TW_SubInvGen_GenerateInvoice test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    01/04/2024      100            ECOMM-194: Original version
 * Daniel Reto      03/05/2024		100            ECOMM-1027
 **/
@isTest
private class COMM_TW_SubInvGen_GenerateInvoiceTest {
    private final static fflib_ApexMocks MOCKS = new fflib_ApexMocks();
    private final static COMM_IREP_Case CASE_REP = (COMM_REP_Case) MOCKS.mock(COMM_REP_Case.class);
    private final static COMM_IREP_Subscription SUBSCRIPTION_REP = (COMM_REP_Subscription) MOCKS.mock(COMM_REP_Subscription.class);
    private final static COMM_IREP_SubscriptionInvoice SUBSCRIPTION_INVOICE_REP = (COMM_REP_SubscriptionInvoice) MOCKS.mock(
        COMM_REP_SubscriptionInvoice.class
    );
    private final static Id CASE_NEW_SUB_RT = SObjectType.Case.getRecordTypeInfosByDeveloperName()
        .get(COMM_DO_Case.SUBSCRIPTION_REQUEST_RT)
        .getRecordTypeId();

    @isTest
    static void invoiceGenerationSuccessWithCaseIdTest() {
        //Scenario: A Case to start a new Subscription was concluded.
        //Expected: A Subscription Invoice Record is generated.

        //Mock Case
        List<Case> caseList = (List<Case>) COMM_TestDataFactory.insertRecords(
            1,
            false,
            'Case',
            new Map<String, Object>{
                'Id' => fflib_IDGenerator.generate(Case.sObjectType),
                'AccountId' => fflib_IDGenerator.generate(Account.sObjectType),
                'COMM_Card__c' => fflib_IDGenerator.generate(Product2.sObjectType),
                'COMM_Subscription__c' => fflib_IDGenerator.generate(COMM_Subscription__c.sObjectType),
                'ProductId' => fflib_IDGenerator.generate(Product2.sObjectType),
                'COMM_NewCardRequest__c' => true,
                'COMM_CardPrice__c' => 5.00,
                'COMM_SubscriptionPrice__c' => 100.00,
                'RecordTypeId' => CASE_NEW_SUB_RT
            }
        );
        caseList[0].RecordType = new RecordType(Id = CASE_NEW_SUB_RT, DeveloperName = COMM_DO_Case.SUBSCRIPTION_REQUEST_RT);

        caseList[0].COMM_Subscription__r = (COMM_Subscription__c) COMM_TestDataFactory.insertRecords(
            1,
            false,
            'COMM_Subscription__c',
            new Map<String, Object>{ 'Id' => caseList[0].COMM_Subscription__c, 'COMM_Price__c' => 100.00 }
        )[0];

        //Mock Platform Event that started logic
        List<COMM_SubscriptionInvoiceGenerator__e> pEventList = (List<COMM_SubscriptionInvoiceGenerator__e>) COMM_TestDataFactory.insertRecords(
            1,
            false,
            'COMM_SubscriptionInvoiceGenerator__e',
            new Map<String, Object>{ 'COMM_CaseId__c' => caseList[0].Id }
        );

        //Expected invoice to be generated
        COMM_SubscriptionInvoice__c expectedInvoice = new COMM_SubscriptionInvoice__c();
        expectedInvoice.COMM_Status__c = COMM_DO_SubscriptionInvoice.PENDING_STATUS;
        expectedInvoice.COMM_SubscriptonRequest__c = caseList[0].Id;
        expectedInvoice.COMM_Account__c = caseList[0].AccountId;
        expectedInvoice.COMM_CardProduct__c = caseList[0].COMM_Card__c;
        expectedInvoice.COMM_Subscripton__c = caseList[0].COMM_Subscription__c;
        expectedInvoice.COMM_SubscriptonProduct__c = caseList[0].ProductId;
        expectedInvoice.COMM_SubscriptionAmount__c = caseList[0].COMM_SubscriptionPrice__c;
        expectedInvoice.COMM_CardAmount__c = caseList[0].COMM_CardPrice__c;

        //Mocks Queries
        MOCKS.startStubbing();
        MOCKS.when(CASE_REP.getSubscriptionCaseByIds((Set<Id>) fflib_Match.anyObject(), fflib_Match.anyBoolean())).thenReturn(caseList);
        MOCKS.when(SUBSCRIPTION_INVOICE_REP.insertSObjects((List<COMM_SubscriptionInvoice__c>) fflib_Match.anyList()))
            .thenReturn(new List<Database.SaveResult>());
        MOCKS.stopStubbing();

        Test.startTest();
        COMM_TW_SubInvGen_GenerateInvoice worker = new COMM_TW_SubInvGen_GenerateInvoice();
        worker = new COMM_TW_SubInvGen_GenerateInvoice(CASE_REP, SUBSCRIPTION_REP, SUBSCRIPTION_INVOICE_REP);
        worker.execute(pEventList);
        Test.stopTest();

        List<Error_Log__c> errorList = [SELECT Id FROM Error_Log__c];

        //Verify Results
        ((COMM_IREP_SubscriptionInvoice) mocks.verify(SUBSCRIPTION_INVOICE_REP, 1))
            .insertSObjects(new List<COMM_SubscriptionInvoice__c>{ expectedInvoice });
        Assert.isTrue(errorList.isEmpty(), 'expected no error logs to have been created');
    }

    @isTest
    static void invoiceGenerationSuccessWithSubscriptionIdTest() {
        //Scenario: A automatic renewal Subscription was renewed.
        //Expected: A Subscription Invoice Record is generated.

        //Subscription for Mocking Test
        List<COMM_Subscription__c> subscriptionRecordList = (List<COMM_Subscription__c>) COMM_TestDataFactory.insertRecords(
            1,
            false,
            'COMM_Subscription__c',
            new Map<String, Object>{
                'Id' => fflib_IDGenerator.generate(COMM_Subscription__c.SObjectType),
                'COMM_Account__c' => fflib_IDGenerator.generate(Account.SObjectType),
                'COMM_Active__c' => true,
                'COMM_AutomaticRenewal__c' => true,
                'COMM_CancellationDate__c' => Date.today(),
                'COMM_CarBrand__c' => 'Mazda',
                'COMM_CarModel__c' => 'Standard 2.0',
                'COMM_Card__c' => fflib_IDGenerator.generate(Product2.SObjectType),
                'COMM_Contact__c' => fflib_IDGenerator.generate(Contact.SObjectType),
                'COMM_Email__c' => 'test@test.com.invalid',
                'COMM_EndDate__c' => Date.today().addYears(1),
                'COMM_FirstName__c' => 'Test',
                'COMM_InitialSubscriptionMonth__c' => 'December',
                'COMM_LastName__c' => 'Subscription',
                'COMM_LicensePlate__c' => 'AS.54.AS',
                'COMM_OCIEndDate__c' => Date.today().addYears(1),
                'COMM_Periodicity__c' => COMM_DO_Subscription.PERIODICITY_YEARLY,
                'COMM_PhoneNumber__c' => '+351911911911',
                'COMM_Price__c' => 100,
                'COMM_Product__c' => fflib_IDGenerator.generate(Product2.SObjectType),
                'RecordTypeId' => Schema.SObjectType.COMM_Subscription__c.getRecordTypeInfosByDeveloperName()
                    .get(COMM_DO_Subscription.RECORDTYPE_PARTNER)
                    .RecordTypeId,
                'COMM_StartDate__c' => Date.newInstance(Date.today().year(), 12, Date.today().day()).addYears(-1),
                'COMM_Status__c' => COMM_DO_Subscription.STATUS_PROCESS_CONCLUDED,
                'COMM_SubscriptionNumber__c' => '522200',
                'COMM_VATNumber__c' => '321654321'
            }
        );

        //Mock Platform Event that started logic
        List<COMM_SubscriptionInvoiceGenerator__e> pEventList = (List<COMM_SubscriptionInvoiceGenerator__e>) COMM_TestDataFactory.insertRecords(
            1,
            false,
            'COMM_SubscriptionInvoiceGenerator__e',
            new Map<String, Object>{ 'COMM_SubscriptionId__c' => subscriptionRecordList[0].Id }
        );

        //Expected invoice to be generated
        COMM_SubscriptionInvoice__c expectedInvoice = new COMM_SubscriptionInvoice__c();
        expectedInvoice.COMM_Status__c = COMM_DO_SubscriptionInvoice.PENDING_STATUS;
        expectedInvoice.COMM_Account__c = subscriptionRecordList[0].COMM_Account__c;
        expectedInvoice.COMM_Subscripton__c = subscriptionRecordList[0].Id;
        expectedInvoice.COMM_SubscriptonProduct__c = subscriptionRecordList[0].COMM_Product__c;
        expectedInvoice.COMM_SubscriptionAmount__c = subscriptionRecordList[0].COMM_Price__c;

        //Mocks Queries
        MOCKS.startStubbing();
        MOCKS.when(SUBSCRIPTION_REP.getSubscriptionsByIds((Set<Id>) fflib_Match.anyObject())).thenReturn(subscriptionRecordList);
        MOCKS.when(SUBSCRIPTION_INVOICE_REP.insertSObjects((List<COMM_SubscriptionInvoice__c>) fflib_Match.anyList()))
            .thenReturn(new List<Database.SaveResult>());
        MOCKS.stopStubbing();

        Test.startTest();
        COMM_TW_SubInvGen_GenerateInvoice worker = new COMM_TW_SubInvGen_GenerateInvoice();
        worker = new COMM_TW_SubInvGen_GenerateInvoice(CASE_REP, SUBSCRIPTION_REP, SUBSCRIPTION_INVOICE_REP);
        worker.execute(pEventList);
        Test.stopTest();

        List<Error_Log__c> errorList = [SELECT Id FROM Error_Log__c];

        //Verify Results
        ((COMM_IREP_SubscriptionInvoice) mocks.verify(SUBSCRIPTION_INVOICE_REP, 1))
            .insertSObjects(new List<COMM_SubscriptionInvoice__c>{ expectedInvoice });
        Assert.isTrue(errorList.isEmpty(), 'expected no error logs to have been created');
    }
}