force-app/main/default/objects/Account/fields/COMM_BillingFirstName__c.field-meta.xml
<CustomField>
    <fullName>COMM_BillingFirstName__c</fullName>
    <description>First Name of the Person the Billing will be associated with.</description>
    <label>Billing First Name</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_BillingLastName__c.field-meta.xml
<CustomField>
    <fullName>COMM_BillingLastName__c</fullName>
    <description>Last Name of the Person the Billing will be associated with</description>
    <label>Billing Last Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_CompanyName__c.field-meta.xml
<CustomField>
    <fullName>COMM_CompanyName__c</fullName>
    <description>Name of the Company the Person associated with the Person Account belongs to. For use in billing.</description>
    <label>Company Name</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_CompanyVATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_CompanyVATNumber__c</fullName>
    <description>VAT Number of the Company the Person associated with the Person Account belongs to. For use in billing.</description>
    <label>Company VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_Email__c.field-meta.xml
<CustomField>
    <fullName>COMM_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_IndividualStaff__c.field-meta.xml
<CustomField>
    <fullName>COMM_IndividualStaff__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked indicates that this account will be able to see in Commerce the products with the checkbox “Requires Airport Staff”checked</description>
    <label>Individual Staff?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_IsAffiliate__c.field-meta.xml
<CustomField>
    <fullName>COMM_IsAffiliate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>In this field, the ANA Admin chooses whether the account type is an affiliate or not</description>
    <label>Is Affiliate?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_IsPartner__c.field-meta.xml
<CustomField>
    <fullName>COMM_IsPartner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>In this field, the ANA Admin chooses whether the account type is an subscription partner or not</description>
    <label>Is Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_MarketingAndCommunicationConsent__c.field-meta.xml
<CustomField>
    <fullName>COMM_MarketingAndCommunicationConsent__c</fullName>
    <description>Picklist that indicates if the account accepts to receive Marketing and communication content</description>
    <label>Marketing Communications Consent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Confirmation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_ParentAccount__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field containing related Parent Account</description>
    <label>Affiliate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_ParentAccountData__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentAccountData__c</fullName>
    <description>Field to store JSON of Parent Account. Used to show data to affiliates in Community without bypassing sharing rules.</description>
    <formula>&apos;{&quot;isB2C&quot;: &apos; + IF(Parent.IsPersonAccount, &apos;true&apos;, &apos;false&apos;) + &apos;, &quot;isAffiliate&quot;: &apos; +  IF(COMM_ParentAccount__r.COMM_IsAffiliate__c, &apos;true&apos;, &apos;false&apos;) + &apos;, &quot;companyEmail&quot;: &quot;&apos;+ COMM_ParentAccount__r.COMM_Email__c + &apos;&quot;,&quot;companyName&quot;: &quot;&apos; + COMM_ParentAccount__r.Name + &apos;&quot;,&quot;companyVATNumber&quot;: &quot;&apos; +  COMM_ParentAccount__r.COMM_VATNumber__c + &apos;&quot;,&quot;companyCountry&quot;: &quot;&apos; + TEXT(COMM_ParentAccount__r.BillingCountryCode) + &apos;&quot;,&quot;companyCity&quot;: &quot;&apos; + COMM_ParentAccount__r.BillingCity + &apos;&quot;,&quot;companyZipCode&quot;: &quot;&apos; +  COMM_ParentAccount__r.BillingPostalCode + &apos;&quot;,&quot;companyAddress&quot;: &quot;&apos; + COMM_ParentAccount__r.BillingStreet+ &apos;&quot;}&apos;</formula>
    <label>Parent Account Data</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_ParentAccountIsAffiliate__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentAccountIsAffiliate__c</fullName>
    <description>Indicate if Parent Account is an affiliate</description>
    <formula>COMM_ParentAccount__r.COMM_IsAffiliate__c</formula>
    <label>Parent Account is Affiliate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>COMM_PaymentMethod__c</fullName>
    <description>In this field, the ANA Admin defines the payment method associated to the account</description>
    <inlineHelpText>The Affiliates can pay by cash or credit
Partners can pay by cash, credit or/and courtesy
B2C can only pay by cash</inlineHelpText>
    <label>Payment Method</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VD</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_PreferredContact__c.field-meta.xml
<CustomField>
    <fullName>COMM_PreferredContact__c</fullName>
    <description>The preferred contact method (e-mail or phone)</description>
    <label>Preferred Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Mail</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/COMM_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_VATNumber__c</fullName>
    <description>Unique number that identifies a taxable person (business) or non-taxable legal entity that is registered for VAT.</description>
    <label>VAT Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_EffectiveAccountId__c.field-meta.xml
<CustomField>
    <fullName>COMM_EffectiveAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that the Contact is using. Used to dynamically control Sharing in Community when using Account Switcher.</description>
    <label>Effective Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Effective Contacts</relationshipLabel>
    <relationshipName>EffectiveContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_EmailValidationChangedAddress__c.field-meta.xml
<CustomField>
    <fullName>COMM_EmailValidationChangedAddress__c</fullName>
    <description>Field for Email Change Request Validation, used to confirm what the new email the contact is expected to use once validated</description>
    <label>Email Validation Changed Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_EmailValidationExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EmailValidationExpirationDate__c</fullName>
    <description>This field has the date of when the user validation email link will expire.</description>
    <label>Email Validation Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_EmailValidationStatus__c.field-meta.xml
<CustomField>
    <fullName>COMM_EmailValidationStatus__c</fullName>
    <description>Contains the status of the email validation</description>
    <label>Email Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Validation</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_IsPasswordReseted__c.field-meta.xml
<CustomField>
    <fullName>COMM_IsPasswordReseted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an informative field to be checked if the user used the option forogot password.</description>
    <label>Is Password Reseted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_MarketingAndCommunicationConsent__c.field-meta.xml
<CustomField>
    <fullName>COMM_MarketingAndCommunicationConsent__c</fullName>
    <label>Marketing and Communication Consent?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Confirmation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_PreferredContact__c.field-meta.xml
<CustomField>
    <fullName>COMM_PreferredContact__c</fullName>
    <description>Indicates the contact method that the Client prefers to receive communications</description>
    <label>Contact Preferred Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/COMM_EffectiveAccountId__c.field-meta.xml
<CustomField>
    <fullName>COMM_EffectiveAccountId__c</fullName>
    <description>Saves the Id of the account the user has chosen to manage</description>
    <label>Effective Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/COMM_EmailValidationChangedAddress__c.field-meta.xml
<CustomField>
    <fullName>COMM_EmailValidationChangedAddress__c</fullName>
    <description>Field for Email Change Request Validation, used to confirm what the new email the user is expected to use once validated and merge field for emails sent to user</description>
    <label>Email Validation Changed Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User/fields/COMM_EmailValidationExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_EmailValidationExpirationDate__c</fullName>
    <description>Field used to validate if URL for email validation has expired</description>
    <label>Email Validation Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/COMM_EmailValidationStatus__c.field-meta.xml
<CustomField>
    <fullName>COMM_EmailValidationStatus__c</fullName>
    <description>Status of the email validation process when a user registers</description>
    <label>Email Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Validation</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/COMM_IsPasswordReseted__c.field-meta.xml
<CustomField>
    <fullName>COMM_IsPasswordReseted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an informative field to be checked if the user used the option forgot password.</description>
    <label>Is Password Reseted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/COMM_LastPasswordRetrievalTime__c.field-meta.xml
<CustomField>
    <fullName>COMM_LastPasswordRetrievalTime__c</fullName>
    <description>Record the last time a password retrieval request was made.</description>
    <label>Last Password Retrieval Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/COMM_LoginType__c.field-meta.xml
<CustomField>
    <fullName>COMM_LoginType__c</fullName>
    <description>Used to identify the type of Login the User uses when logging in from the Community Site</description>
    <label>Login Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Azure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/COMM_PasswordRetrievalCount__c.field-meta.xml
<CustomField>
    <fullName>COMM_PasswordRetrievalCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>To store the count of password retrieval requests related to the Reset Password Feature in Customer Portal</description>
    <label>Password Retrieval Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/COMM_ResetPasswordEmailExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_ResetPasswordEmailExpirationDate__c</fullName>
    <description>Field to store the date when the users forgot password and change password email link expires.</description>
    <label>Reset Password Email Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/COMM_REP_User.cls
/**
 * @author Luis Oliveira
 * @description User repository class to query data.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Luis Oliveira    27/02/2024       Original version
 * Miguel Justo     28/02/2024       Added getUser
 * Daniel Lascas    28/02/2024       Added methods getUserByEmailAndLoginType and getUsersById
 * Daniel Lascas    08/03/2024       Added method getUserAccountAndContactDataById
 * Daniel Lascas    26/03/2024       Added method getAzureUserByEmail
 * Miguel Freire    23/03/2024       Added method getUsersByIdEmailValidation and getUserByEmailValidationStatusAndDate
 * Daniel Reto      29/05/2024       PDM warning messages fix
 * Miguel Freire    19/07/2024       Added method getActiveNonPartnerUserByEmail
 **/
public inherited sharing class COMM_REP_User extends FW_SobjectRep implements COMM_IREP_User {
    /**
     * @description Get active portal user given the email.
     *
     * @param Email - The user's email.
     * @param securityEnforced - Uses the security enforced clause or not.
     * @return The active user, null otherwise.
     */
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public User getActivePortalUserByEmail(String email, Boolean securityEnforced) {
        List<User> users = new List<User>();
        if (securityEnforced) {
            users = [
                SELECT Id, Name, Email, IsActive, Username
                FROM User
                WHERE Email = :email AND ContactId != NULL AND Contact.AccountId != NULL AND IsActive = TRUE
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
        } else {
            users = [
                SELECT Id, Name, Email, IsActive, Username
                FROM User
                WHERE Email = :email AND ContactId != NULL AND Contact.AccountId != NULL AND IsActive = TRUE
                LIMIT 1
            ];
        }

        return users.size() > 0 ? users[0] : null;
    }

    /**
     * @description Retrieve a User  by its ID from the database
     * @param userId - User identifier.
     * @return User data.
     **/
    public List<User> getUser(Set<Id> userIds) {
        List<User> users = new List<User>();
        users = [
            SELECT Id, Name, FirstName, LastName, Username, Email, COMM_EffectiveAccountId__c, ContactId
            FROM User
            WHERE Id IN :userIds AND IsActive = TRUE
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        return users;
    }

    /**
     * @description Retrieve the list of Active User Records by a Set of Ids
     *
     * @param userIds Set of User Ids to query Users
     * @return List of User Records found
     **/
    public List<User> getUsersById(Set<Id> userIds) {
        return [
            SELECT
                Id,
                ContactId,
                COMM_LoginType__c,
                COMM_EffectiveAccountId__c,
                COMM_ResetPasswordEmailExpirationDate__c,
                COMM_IsPasswordReseted__c,
                COMM_EmailValidationExpirationDate__c,
                COMM_EmailValidationChangedAddress__c,
                LanguageLocaleKey,
                Email
            FROM User
            WHERE Id IN :userIds AND IsActive = TRUE
            WITH USER_MODE
        ];
    }

    /**
     * @description Retrieve the list of Active User Records with their language by a set of Ids.
     *
     * @param userIds Set of User Ids to query Users.
     * @param securityEnforced - Uses the security enforced clause or not.
     * @return List of User Records found.
     **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public List<User> getUserWithLaguageFieldById(Set<Id> userIds, Boolean securityEnforced) {
        List<User> users = new List<User>();
        if (securityEnforced) {
            users = [
                SELECT Id, LanguageLocaleKey
                FROM User
                WHERE Id IN :userIds AND IsActive = TRUE
                WITH USER_MODE
            ];
        } else {
            users = [
                SELECT Id, LanguageLocaleKey
                FROM User
                WHERE Id IN :userIds AND IsActive = TRUE
            ];
        }

        return users;
    }

    /**
     * @description Retrieve the list of Active User Records by a Set of Ids
     * with fields used for Email Change Validation.
     *
     * @param userIds Set of User Ids to query Users
     * @param securityEnforced - Uses the user mode security clause or not.
     * @return List of User Records found
     **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public List<User> getUsersWithEmailChangeValidationById(Set<Id> userIds, Boolean securityEnforced) {
        if (securityEnforced) {
            return [
                SELECT Id, ContactId, COMM_EmailValidationExpirationDate__c, COMM_EmailValidationChangedAddress__c
                FROM User
                WHERE Id IN :userIds AND IsActive = TRUE
                WITH USER_MODE
            ];
        } else {
            return [
                SELECT Id, ContactId, COMM_EmailValidationExpirationDate__c, COMM_EmailValidationChangedAddress__c
                FROM User
                WHERE Id IN :userIds AND IsActive = TRUE
            ];
        }
    }

    /**
     * @description Retrieve the list of Active User Records that use a set of Emails and a set of Identifiers.
     *
     * @param emails Set of Emails to query Users
     * @param identifiers Set of Identifiers that User's use to Login
     * @param securityEnforced - Uses the security enforced clause or not.
     * @return List of User Records found
     **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public List<User> getUserByEmailAndLoginType(Set<String> emails, Set<String> identifiers, Boolean securityEnforced) {
        List<User> users = new List<User>();
        if (securityEnforced) {
            users = [
                SELECT Id, Email, LanguageLocaleKey, COMM_LoginType__c, Username
                FROM User
                WHERE Email IN :emails AND COMM_LoginType__c IN :identifiers AND IsActive = TRUE
                WITH USER_MODE
            ];
        } else {
            users = [
                SELECT Id, Email, LanguageLocaleKey, COMM_LoginType__c, Username
                FROM User
                WHERE Email IN :emails AND COMM_LoginType__c IN :identifiers AND IsActive = TRUE
            ];
        }

        return users;
    }

    /**
     * @description Retrieve the list of Active User Records with their
     * associated Contact and Account Record by a Set of Ids
     *
     * @param userIds Set of User Ids to query Users
     * @return List of User Records with Account and Contact found
     **/
    public List<User> getUserAccountAndContactDataById(Set<Id> userIds) {
        return [
            SELECT
                Id,
                AccountId,
                ContactId,
                COMM_EffectiveAccountId__c,
                Account.Id,
                Account.Name,
                Account.FirstName,
                Account.LastName,
                Account.PersonEmail,
                Account.PersonMobilePhone,
                Account.isPersonAccount,
                Account.Phone,
                Account.RecordTypeId,
                Account.COMM_ParentAccountIsAffiliate__c,
                Account.COMM_ParentAccountData__c,
                Account.COMM_Email__c,
                Account.COMM_IsPartner__c,
                Account.COMM_IsAffiliate__c,
                Account.COMM_IndividualStaff__c,
                Account.COMM_BillingFirstName__c,
                Account.COMM_BillingLastName__c,
                Account.COMM_VATNumber__c,
                Account.COMM_PaymentMethod__c,
                Account.BillingStreet,
                Account.BillingPostalCode,
                Account.BillingCity,
                Account.BillingCountryCode,
                Account.COMM_CompanyName__c,
                Account.COMM_CompanyVATNumber__c,
                Account.COMM_CompanyBillingAddress__Street__s,
                Account.COMM_CompanyBillingAddress__PostalCode__s,
                Account.COMM_CompanyBillingAddress__City__s,
                Account.COMM_CompanyBillingAddress__CountryCode__s,
                Account.COMM_PreferredContact__c,
                Account.COMM_PreferredContact__pc,
                Account.COMM_MarketingAndCommunicationConsent__c,
                Account.COMM_MarketingAndCommunicationConsent__pc,
                Account.COMM_ParentAccount__c,
                Contact.Id,
                Contact.FirstName,
                Contact.LastName,
                Contact.Email,
                Contact.MobilePhone,
                Contact.COMM_MarketingAndCommunicationConsent__c,
                Contact.COMM_PreferredContact__c
            FROM User
            WHERE Id IN :userIds AND IsActive = TRUE
            WITH USER_MODE
        ];
    }

    /**
     * @description Retrieve the list of Active Azure User Records.
     * An Azure User has Login Type set as Azure and FederationId EQUALS Email
     *
     * @param emails Set of Emails to query Users
     * @param securityEnforced - Uses the security enforced clause or not.
     * @return List of User Records found
     **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public List<User> getAzureUsersByEmail(Set<String> emails, Boolean securityEnforced) {
        List<User> users = new List<User>();
        if (securityEnforced) {
            users = [
                SELECT Id, Email, LanguageLocaleKey, COMM_LoginType__c
                FROM User
                WHERE
                    Email IN :emails
                    AND COMM_LoginType__c = :COMM_DO_User.AZURE_SSO_IDENTIFIER
                    AND FederationIdentifier IN :emails
                    AND IsActive = TRUE
                WITH USER_MODE
            ];
        } else {
            users = [
                SELECT Id, Email, LanguageLocaleKey, COMM_LoginType__c
                FROM User
                WHERE
                    Email IN :emails
                    AND COMM_LoginType__c = :COMM_DO_User.AZURE_SSO_IDENTIFIER
                    AND FederationIdentifier IN :emails
                    AND IsActive = TRUE
            ];
        }

        return users;
    }

    /**
     * @description Retrieve the list of User Records by a Set of Ids without user mode
     *
     * @param userIds Set of User Ids to query Users
     * @return List of User Records found
     **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public List<User> getUsersByIdEmailValidation(Set<Id> userIds, Boolean securityEnforced) {
        List<User> users = new List<User>();
        if (securityEnforced) {
            users = [
                SELECT Id, isActive, COMM_EmailValidationExpirationDate__c, COMM_EmailValidationStatus__c, LanguageLocaleKey
                FROM User
                WHERE Id IN :userIds
                WITH USER_MODE
            ];
        } else {
            users = [
                SELECT Id, isActive, COMM_EmailValidationExpirationDate__c, COMM_EmailValidationStatus__c, LanguageLocaleKey
                FROM User
                WHERE Id IN :userIds
            ];
        }
        return users;
    }

    /**
     * @description Retrieve the list of inactive User Records that the email validation link has expired.
     *
     * @param securityEnforced - Uses the security enforced clause or not.
     * @return List of User Records found
     **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public List<User> getUserByInValidationExpiredEmail(Boolean securityEnforced) {
        List<User> users = new List<User>();
        if (securityEnforced) {
            users = [
                SELECT Id, COMM_EmailValidationExpirationDate__c, COMM_EmailValidationStatus__c, accountId
                FROM User
                WHERE
                    COMM_EmailValidationStatus__c = :COMM_DO_User.EMAIL_VALIDATION_PICKLIST_INVALIDATION
                    AND COMM_EmailValidationExpirationDate__c <= :Datetime.now()
                    AND accountId != NULL
                WITH USER_MODE
            ];
        } else {
            users = [
                SELECT Id, COMM_EmailValidationExpirationDate__c, COMM_EmailValidationStatus__c, accountId
                FROM User
                WHERE
                    COMM_EmailValidationStatus__c = :COMM_DO_User.EMAIL_VALIDATION_PICKLIST_INVALIDATION
                    AND COMM_EmailValidationExpirationDate__c <= :Datetime.now()
                    AND accountId != NULL
            ];
        }
        return users;
    }

    /**
     * @description Retrieve the list of Active User Records by a Set of Ids
     * with fields used for Password, Email validation
     *
     * @param userIds Set of User Ids to query Users
     * @param securityEnforced - Uses the security enforced clause or not.
     * @return List of User Records found
     **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public List<User> getUserValidationById(Set<Id> userIds, Boolean securityEnforced) {
        if (securityEnforced) {
            return [
                SELECT
                    Id,
                    COMM_ResetPasswordEmailExpirationDate__c,
                    COMM_IsPasswordReseted__c,
                    COMM_PasswordRetrievalCount__c,
                    COMM_LastPasswordRetrievalTime__c,
                    COMM_EmailValidationExpirationDate__c,
                    COMM_EmailValidationChangedAddress__c,
                    Email,
                    FirstName,
                    LastName
                FROM User
                WHERE Id IN :userIds AND IsActive = TRUE
                WITH USER_MODE
            ];
        } else {
            return [
                SELECT
                    Id,
                    COMM_ResetPasswordEmailExpirationDate__c,
                    COMM_IsPasswordReseted__c,
                    COMM_PasswordRetrievalCount__c,
                    COMM_LastPasswordRetrievalTime__c,
                    COMM_EmailValidationExpirationDate__c,
                    COMM_EmailValidationChangedAddress__c,
                    Email,
                    FirstName,
                    LastName
                FROM User
                WHERE Id IN :userIds AND IsActive = TRUE
            ];
        }
    }
    /**
     * @description Get active non partner user given the email.
     *
     * @param Email - The user's email.
     * @param securityEnforced - Uses the security enforced clause or not.
     * @return The active user, null otherwise.
     */
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public User getActiveNonPartnerUserByEmail(String email, Boolean securityEnforced) {
        List<User> users = new List<User>();
        if (securityEnforced) {
            users = [
                SELECT Id, Name, Email, IsActive, Username
                FROM User
                WHERE
                    Email = :email
                    AND IsActive = TRUE
                    AND Profile.Name NOT IN (:COMM_DO_Profile.PROFILE_NAME_PARTNER_ADMIN, :COMM_DO_Profile.PROFILE_NAME_SUPER_PARTNER_ADMIN)
                WITH USER_MODE
                LIMIT 1
            ];
        } else {
            users = [
                SELECT Id, Name, Email, IsActive, Username
                FROM User
                WHERE
                    Email = :email
                    AND IsActive = TRUE
                    AND Profile.Name NOT IN (:COMM_DO_Profile.PROFILE_NAME_PARTNER_ADMIN, :COMM_DO_Profile.PROFILE_NAME_SUPER_PARTNER_ADMIN)
                LIMIT 1
            ];
        }

        return users.size() > 0 ? users[0] : null;
    }
}