force-app/main/default/objects/COMM_FreeVoucher__c/COMM_FreeVoucher__c.object-meta.xml
<CustomObject>
    <description>Object that represents a record of a free voucher to be given to customers</description>
    <label>Free Voucher</label>
    <nameField>
        <displayFormat>FV-{0000}</displayFormat>
        <label>Free Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport the Voucher is associated with</description>
    <formula>IF(TEXT($User.LanguageLocaleKey) = &apos;pt_PT&apos;,
   CASE(COMM_Product__r.COMM_Airport__c,
      &quot;OPO&quot;, &quot;Porto&quot;,
      &quot;LIS&quot;,&quot;Lisboa&quot;,
      &quot;FAO&quot;,&quot;Faro&quot;,
      &quot;FNC&quot;,&quot;Madeira&quot;,
      &quot;PDL&quot;,&quot;Ponta Delgada&quot;,
      TEXT(COMM_Product__r.COMM_Airport__c)),
IF(TEXT($User.LanguageLocaleKey) = &apos;es&apos;,
   CASE(COMM_Product__r.COMM_Airport__c,
      &quot;OPO&quot;, &quot;OPorto&quot;,
      &quot;LIS&quot;,&quot;Lisboa&quot;,
      &quot;FAO&quot;,&quot;Faro&quot;,
      &quot;FNC&quot;,&quot;Madeira&quot;,
      &quot;PDL&quot;,&quot;Ponta Delgada&quot;,
      TEXT(COMM_Product__r.COMM_Airport__c)),
CASE(COMM_Product__r.COMM_Airport__c,
   &quot;OPO&quot;, &quot;Porto&quot;,
   &quot;LIS&quot;,&quot;Lisbon&quot;,
   &quot;FAO&quot;,&quot;Faro&quot;,
   &quot;FNC&quot;,&quot;Madeira&quot;,
   &quot;PDL&quot;,&quot;Ponta Delgada&quot;,
   TEXT(COMM_Product__r.COMM_Airport__c))))</formula>
    <label>Airport</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_Email__c.field-meta.xml
<CustomField>
    <fullName>COMM_Email__c</fullName>
    <description>Customer&apos;s Email address where the voucher is sent</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_Language__c.field-meta.xml
<CustomField>
    <fullName>COMM_Language__c</fullName>
    <description>Language used in emails that are sent to the Customer</description>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the Voucher is associated with</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Only Fast Track and Lounge Products that are Child can be associated with a Free Voucher.</errorMessage>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Fast Track</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Lounge</value>
        </filterItems>
        <filterItems>
            <field>Product2.COMM_ParentProduct__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Free Vouchers</relationshipLabel>
    <relationshipName>FreeVouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_QRCodeImage__c.field-meta.xml
<CustomField>
    <fullName>COMM_QRCodeImage__c</fullName>
    <description>Field to store QR Code Image of the Voucher</description>
    <label>QR Code Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_ReservationName__c.field-meta.xml
<CustomField>
    <fullName>COMM_ReservationName__c</fullName>
    <description>Name of the Customer on the Reservation the Voucher is associated with</description>
    <label>Reservation Name</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_StartDate__c</fullName>
    <description>Date of when Voucher can be used</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ClosingOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_ClosingOperatingHours__c</fullName>
    <description>Specific time during which the product stops being operational to be sold to the customers</description>
    <label>Closing Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_CPMS__c.field-meta.xml
<CustomField>
    <fullName>COMM_CPMS__c</fullName>
    <description>Which CPMS provider is associated with park where the reservation was done</description>
    <label>Parking System Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_CPMS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_OpeningOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_OpeningOperatingHours__c</fullName>
    <description>Specific time during which the product starts being operational to be sold to the customers</description>
    <label>Opening Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>COMM_ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Product for the Product Record</description>
    <label>Parent Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Airport needs to be the same in both Parent and Child Product</errorMessage>
        <filterItems>
            <field>Product2.COMM_Airport__c</field>
            <operation>equals</operation>
            <valueField>$Source.COMM_Airport__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Park__c.field-meta.xml
<CustomField>
    <fullName>COMM_Park__c</fullName>
    <description>Park associated with the Product</description>
    <label>Park</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Park</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubCategory__c</fullName>
    <description>Used to define the sub-category of the product.</description>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Park</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Fast Lane</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Exempt Official Entity</fullName>
            </value>
            <value>
                <fullName>ANA + Entities</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>RAC / Shuttle NL</fullName>
            </value>
            <value>
                <fullName>Staff Company</fullName>
            </value>
            <value>
                <fullName>Staff Individual</fullName>
            </value>
            <value>
                <fullName>Fast Track Plus</fullName>
            </value>
            <value>
                <fullName>Lounge Adult</fullName>
            </value>
            <value>
                <fullName>Lounge Child</fullName>
            </value>
            <value>
                <fullName>Lounge Adult with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Child with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Non Schengen</fullName>
            </value>
            <value>
                <fullName>Terminal</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non -Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Adult Non -Schengen</label>
            </value>
            <value>
                <fullName>Lounge Child Non - Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Child Non - Schengen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Tax__c.field-meta.xml
<CustomField>
    <fullName>COMM_Tax__c</fullName>
    <description>Defines the tax used for the product based on location</description>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>COMM_Airport__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continent</fullName>
            </value>
            <value>
                <fullName>Madeira</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date for which the product is deemed valid</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_WhereProductAvailable__c.field-meta.xml
<CustomField>
    <fullName>COMM_WhereProductAvailable__c</fullName>
    <description>Multi Picklist that indicates in which platform the product will be available</description>
    <label>Where is the product available?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Subscriptions Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/COMM_SL_FreeVoucherReservationTest.cls
/**
 * @author           Daniel Lascas
 * @description      COMM_SL_FreeVoucherReservation test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    24/10/2024      92            ECOMM-2248: Original version
 **/
@isTest
private class COMM_SL_FreeVoucherReservationTest {
    private static final List<String> QRCODE_RESPONSE_DATA = new List<String>{
        '"content": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdj+Gkf9x8ABmEClm+bvsMAAAAASUVORK5CYII="',
        '"fileType": "img/png"'
    };

    @TestSetup
    static void setup() {
        Time testTime = Time.newInstance(1, 2, 3, 0);
        //Insert Lounge Product for testing
        Product2 loungeProduct = (Product2) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'Lounge Product',
                'ProductCode' => 'lounge2',
                'Description' => 'lounge',
                'IsActive' => false,
                'Family' => COMM_DO_Product2.CATEGORY_LOUNGE,
                'COMM_ValidFrom__c' => System.now().addSeconds(30),
                'COMM_ValidTo__c' => System.now().addDays(2),
                'COMM_Airport__c' => 'LIS',
                'COMM_Tax__c' => 'Continent',
                'COMM_Park__c' => 'p0',
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_OpeningOperatingHours__c' => testTime,
                'COMM_ClosingOperatingHours__c' => testTime,
                'COMM_SubCategory__c' => 'Lounge'
            }
        )[0];

        // Insert Child Product
        Product2 pForCap = (Product2) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'Child',
                'ProductCode' => 'C2132',
                'Description' => 'Test Lounge',
                'IsActive' => true,
                'Family' => 'Lounge',
                'COMM_ValidFrom__c' => System.now().addMinutes(1),
                'COMM_ValidTo__c' => System.now().addDays(2),
                'COMM_Airport__c' => 'LIS',
                'COMM_Tax__c' => 'Continent',
                'COMM_OpeningOperatingHours__c' => testTime,
                'COMM_ClosingOperatingHours__c' => testTime,
                'COMM_ParentProduct__c' => loungeProduct.id,
                'COMM_SubCategory__c' => 'Lounge',
                'COMM_WhereProductAvailable__c' => COMM_DO_Product2.PRODUCT_AVAILABLE_IN_COMMERCE
            }
        )[0];

        //Insert Free Voucher Record
        COMM_TestDataFactory.insertRecords(
            1,
            true,
            'COMM_FreeVoucher__c',
            new Map<String, Object>{
                'COMM_ReservationName__c' => 'Joao Teste',
                'COMM_StartDate__c' => Datetime.now(),
                'COMM_Email__c' => 'joao.teste@test.invalid',
                'COMM_Language__c' => 'pt_PT',
                'COMM_Product__c' => pForCap.Id
            }
        );
    }

    @isTest
    static void testCreateReservationVouchers() {
        //Scenario: QR Code for Free Voucher is requested
        //Expected: QR Code generated.
        List<COMM_FreeVoucher__c> fvList = [SELECT Id FROM COMM_FreeVoucher__c LIMIT 1];
        Assert.areEqual(fvList.isEmpty(), false, 'Free Voucher not found.');

        Test.setMock(HttpCalloutMock.class, new HttpResponseSuccessMock('{' + String.join(QRCODE_RESPONSE_DATA, ',') + '}'));

        Test.startTest();
        COMM_SL_FreeVoucherReservation.createFreeReservationVouchers(new List<Id>{ fvList[0].Id });
        Test.stopTest();

        List<COMM_FreeVoucher__c> actualFvList = [SELECT Id, COMM_QRCodeImage__c FROM COMM_FreeVoucher__c WHERE Id = :fvList[0].Id];

        Assert.isNotNull(actualFvList[0].COMM_QRCodeImage__c, 'QR Codes were not created');
    }

    @isTest
    static void testCreateVouchersExceptionAndResolve() {
        //Scenario: QR Code for Free Voucher is requested but fails to generate.
        //Expected: QR Code isn't generated.
        List<COMM_FreeVoucher__c> fvList = [SELECT Id FROM COMM_FreeVoucher__c LIMIT 1];
        Assert.areEqual(fvList.isEmpty(), false, 'Free Voucher not found.');

        Test.setMock(HttpCalloutMock.class, new HttpResponseSuccessMock('{}'));

        Boolean errorOccured = false;
        Test.startTest();
        try {
            COMM_SL_FreeVoucherReservation.createFreeReservationVouchers(new List<Id>{ fvList[0].Id });
        } catch (Exception e) {
            errorOccured = true;
        }
        Test.stopTest();

        List<COMM_FreeVoucher__c> actualFvList = [SELECT Id, COMM_QRCodeImage__c FROM COMM_FreeVoucher__c WHERE Id = :fvList[0].Id];

        Assert.isTrue(errorOccured, 'expected an error to occur');
        Assert.isNull(actualFvList[0].COMM_QRCodeImage__c, 'expected QR Codes to not be created');
    }
}