force-app/main/default/objects/COMM_FreeVoucher__c/COMM_FreeVoucher__c.object-meta.xml
<CustomObject>
    <description>Object that represents a record of a free voucher to be given to customers</description>
    <label>Free Voucher</label>
    <nameField>
        <displayFormat>FV-{0000}</displayFormat>
        <label>Free Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport the Voucher is associated with</description>
    <formula>IF(TEXT($User.LanguageLocaleKey) = &apos;pt_PT&apos;,
   CASE(COMM_Product__r.COMM_Airport__c,
      &quot;OPO&quot;, &quot;Porto&quot;,
      &quot;LIS&quot;,&quot;Lisboa&quot;,
      &quot;FAO&quot;,&quot;Faro&quot;,
      &quot;FNC&quot;,&quot;Madeira&quot;,
      &quot;PDL&quot;,&quot;Ponta Delgada&quot;,
      TEXT(COMM_Product__r.COMM_Airport__c)),
IF(TEXT($User.LanguageLocaleKey) = &apos;es&apos;,
   CASE(COMM_Product__r.COMM_Airport__c,
      &quot;OPO&quot;, &quot;OPorto&quot;,
      &quot;LIS&quot;,&quot;Lisboa&quot;,
      &quot;FAO&quot;,&quot;Faro&quot;,
      &quot;FNC&quot;,&quot;Madeira&quot;,
      &quot;PDL&quot;,&quot;Ponta Delgada&quot;,
      TEXT(COMM_Product__r.COMM_Airport__c)),
CASE(COMM_Product__r.COMM_Airport__c,
   &quot;OPO&quot;, &quot;Porto&quot;,
   &quot;LIS&quot;,&quot;Lisbon&quot;,
   &quot;FAO&quot;,&quot;Faro&quot;,
   &quot;FNC&quot;,&quot;Madeira&quot;,
   &quot;PDL&quot;,&quot;Ponta Delgada&quot;,
   TEXT(COMM_Product__r.COMM_Airport__c))))</formula>
    <label>Airport</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the Voucher is associated with</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Only Fast Track and Lounge Products that are Child can be associated with a Free Voucher.</errorMessage>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Fast Track</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Lounge</value>
        </filterItems>
        <filterItems>
            <field>Product2.COMM_ParentProduct__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Free Vouchers</relationshipLabel>
    <relationshipName>FreeVouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_QRCode__c.field-meta.xml
<CustomField>
    <fullName>COMM_QRCode__c</fullName>
    <description>The text value of the QR Code of the Voucher</description>
    <label>QR Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_QRCodeImage__c.field-meta.xml
<CustomField>
    <fullName>COMM_QRCodeImage__c</fullName>
    <description>Field to store QR Code Image of the Voucher</description>
    <label>QR Code Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_StartDate__c</fullName>
    <description>Date of when Voucher can be used</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubCategory__c</fullName>
    <description>Used to define the sub-category of the product.</description>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Park</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Fast Lane</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Exempt Official Entity</fullName>
            </value>
            <value>
                <fullName>ANA + Entities</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>RAC / Shuttle NL</fullName>
            </value>
            <value>
                <fullName>Staff Company</fullName>
            </value>
            <value>
                <fullName>Staff Individual</fullName>
            </value>
            <value>
                <fullName>Fast Track Plus</fullName>
            </value>
            <value>
                <fullName>Lounge Adult</fullName>
            </value>
            <value>
                <fullName>Lounge Child</fullName>
            </value>
            <value>
                <fullName>Lounge Adult with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Child with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Non Schengen</fullName>
            </value>
            <value>
                <fullName>Terminal</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non -Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Adult Non -Schengen</label>
            </value>
            <value>
                <fullName>Lounge Child Non - Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Child Non - Schengen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_TimeZoneByAirport__c.field-meta.xml
<CustomField>
    <fullName>COMM_TimeZoneByAirport__c</fullName>
    <description>Formula field used to discover product Timezone based on the Airport.</description>
    <formula>IF( OR( ISPICKVAL(COMM_Airport__c, &apos;LIS&apos;), ISPICKVAL(COMM_Airport__c, &apos;OPO&apos;), ISPICKVAL(COMM_Airport__c, &apos;FAO&apos;)),
 &apos;Europe/Lisbon&apos;,
 IF( ISPICKVAL(COMM_Airport__c, &apos;FNC&apos;),
  &apos;Atlantic/Madeira&apos;,
   IF( ISPICKVAL(COMM_Airport__c, &apos;PDL&apos;),
    &apos;Atlantic/Azores&apos;,
    &apos;&apos;
  )
 )
)</formula>
    <label>Time Zone by Airport</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_SL_FreeVoucherReservation.cls
/**
 * @author Daniel Lascas
 * @description Service class to handle Free Voucher Reservations
 * for Fast-track and lounges.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    22/10/2024       ECOMM-2248: Original version
 **/
public with sharing class COMM_SL_FreeVoucherReservation {
    private static final String QR_CODE_VALUE_ERR_MESSAGE = 'QR Code value was not generated. Check the product SubCategory, Airport and Reservation Date.';
    private static final String QR_CODE_IMG_ERR_MESSAGE = 'QR Code image was not create.';

    /**
     * @description: method to create reservation vouchers on Free Voucher records,
     * @param voucherIds List of Free Voucher Record Ids.
     * @return List of Free Voucher Records with updated QR Code.
     */
    @InvocableMethod(
        category='Free Voucher'
        label='Create Free Reservation Vouchers'
        description='Create Reservation (lounge and fast-track) to be used in the QR Codes'
    )
    public static List<COMM_FreeVoucher__c> createFreeReservationVouchers(List<Id> voucherIds) {
        //Initialize REP
        COMM_IREP_FreeVoucher freeVoucherRep = new COMM_REP_FreeVoucher();

        List<COMM_FreeVoucher__c> toUpdateList = setReservationVoucherCodes(freeVoucherRep.getVouchersByIds(new Set<Id>(voucherIds)));
        if (!toUpdateList.isEmpty()) {
            freeVoucherRep.updateSObjects(toUpdateList);
        }
        return toUpdateList;
    }

    /**
     * @description: Method to set voucher codes on free voucher records.
     *
     * @param voucherList List of Free Voucher records to update.
     * @return List of updated voucher records.
     */
    private static List<COMM_FreeVoucher__c> setReservationVoucherCodes(List<COMM_FreeVoucher__c> voucherList) {
        List<COMM_FreeVoucher__c> updatedList = new List<COMM_FreeVoucher__c>();
        for (COMM_FreeVoucher__c fvRec : voucherList) {
            setQRCode(fvRec);
            updatedList.add(fvRec);
        }
        return updatedList;
    }

    /**
     * @description Set the QR Code value and image on the COMM_FreeVoucher__c.
     *
     * @param fvRecord Free Voucher Record to be set with QR Code.
     */
    private static void setQRCode(COMM_FreeVoucher__c fvRecord) {
        String qrCode = COMM_GEN_Utility.generateQRCodeValue(
            fvRecord.COMM_Product__r.Family,
            fvRecord.COMM_Product__r.COMM_SubCategory__c,
            fvRecord.COMM_Product__r.COMM_Airport__c,
            fvRecord.COMM_StartDate__c,
            fvRecord.COMM_Product__r.COMM_TimeZoneByAirport__c
        );
        if (String.isBlank(qrCode)) {
            throw new COMM_SL_CreateVoucherException(QR_CODE_VALUE_ERR_MESSAGE);
        }

        fvRecord.COMM_QRCode__c = qrCode;
        fvRecord.COMM_QRCodeImage__c = COMM_GEN_Utility.generateQRCodeImage(fvRecord.COMM_QRCode__c);

        if (String.isBlank(fvRecord.COMM_QRCodeImage__c)) {
            throw new COMM_SL_CreateVoucherException(QR_CODE_IMG_ERR_MESSAGE);
        }
    }
}