force-app/main/default/objects/COMM_FreeVoucher__c/COMM_FreeVoucher__c.object-meta.xml
<CustomObject>
    <description>Object that represents a record of a free voucher to be given to customers</description>
    <label>Free Voucher</label>
    <nameField>
        <displayFormat>FV-{0000}</displayFormat>
        <label>Free Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product that the Voucher is associated with</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Only Fast Track and Lounge Products that are Child can be associated with a Free Voucher.</errorMessage>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Fast Track</value>
        </filterItems>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Lounge</value>
        </filterItems>
        <filterItems>
            <field>Product2.COMM_ParentProduct__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Free Vouchers</relationshipLabel>
    <relationshipName>FreeVouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_FreeVoucher__c/fields/COMM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_StartDate__c</fullName>
    <description>Date of when Voucher can be used</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_TimeZoneByAirport__c.field-meta.xml
<CustomField>
    <fullName>COMM_TimeZoneByAirport__c</fullName>
    <description>Formula field used to discover product Timezone based on the Airport.</description>
    <formula>IF( OR( ISPICKVAL(COMM_Airport__c, &apos;LIS&apos;), ISPICKVAL(COMM_Airport__c, &apos;OPO&apos;), ISPICKVAL(COMM_Airport__c, &apos;FAO&apos;)),
 &apos;Europe/Lisbon&apos;,
 IF( ISPICKVAL(COMM_Airport__c, &apos;FNC&apos;),
  &apos;Atlantic/Madeira&apos;,
   IF( ISPICKVAL(COMM_Airport__c, &apos;PDL&apos;),
    &apos;Atlantic/Azores&apos;,
    &apos;&apos;
  )
 )
)</formula>
    <label>Time Zone by Airport</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_VFC_FreeVoucherPDF.cls
/**
 * @author Daniel Lascas
 * @description Controller class for COMM_VFC_FreeVoucherPDF
 *
 *  * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    23/10/2024       ECOMM-2248: Original version
 */
public with sharing class COMM_VFC_FreeVoucherPDF {
    public Id freeVoucherId { get; set; }
    public COMM_FreeVoucher__c freeVoucher { get; set; }
    public Datetime reservationStartDate { get; set; }
    public Boolean hasFastTrack { get; set; }
    public Boolean hasLounge { get; set; }

    /**
     * @description Constructor of the class. Set the variables used on the page
     * based on the Free Voucher Record Id
     *
     * @param controller Visualforce Controller
     */
    public COMM_VFC_FreeVoucherPDF(ApexPages.StandardController controller) {
        this.freeVoucherId = controller.getId();
        COMM_IREP_FreeVoucher repository = new COMM_REP_FreeVoucher();
        List<COMM_FreeVoucher__c> freeVoucherList = repository.getVouchersByIds(new Set<Id>{ freeVoucherId });
        if (!freeVoucherList.isEmpty()) {
            COMM_FreeVoucher__c freeVoucherRecord = freeVoucherList[0];
            this.freeVoucher = freeVoucherRecord;
            this.reservationStartDate = Datetime.valueOfGMT(
                freeVoucherRecord.COMM_StartDate__c.format(
                    COMM_GEN_Utility.TIMEZONE_DATETIME_FORMAT,
                    freeVoucherRecord.COMM_Product__r?.COMM_TimeZoneByAirport__c
                )
            );
            this.hasFastTrack = COMM_DO_Product2.CATEGORY_FASTTRACK.equals(freeVoucherRecord.COMM_Product__r?.Family);
            this.hasLounge = COMM_DO_Product2.CATEGORY_LOUNGE.equals(freeVoucherRecord.COMM_Product__r?.Family);
        }
    }
}