force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/COMM_OMS_CalloutSettings__mdt.object-meta.xml
<CustomObject>
    <description>Callout Settinsg holds the configurations for callouts</description>
    <label>OMS Callout Setting</label>
    <pluralLabel>OMS Callout Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/Endpoint_Server__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Server__c</fullName>
    <description>This specifies the endpoint server for the integration - e.g. https://&lt;&lt;env&gt;&gt;.services.com/</description>
    <label>Endpoint Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/Endpoint_URI__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URI__c</fullName>
    <description>This species the URI for the integration service - e.g. territory_assignments/accounts/</description>
    <label>Endpoint URI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/HTTP_Headers__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Headers__c</fullName>
    <description>Contains the map of the HTPP Headers (HeaderKey=&gt;HeaderValue) separated by semicolons following: 
HeaderKey=&gt;HeaderValue;HeaderKey=&gt;HeaderValue</description>
    <inlineHelpText>Contains the map of the HTPP Headers (HeaderKey=&gt;HeaderValue) separated by semicolons following: 
HeaderKey=&gt;HeaderValue;HeaderKey=&gt;HeaderValue</inlineHelpText>
    <label>HTTP Headers</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <description>HTTP Method</description>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout (Milliseconds)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/COMM_SL_BarCodeGeneration.cls
/**
 * @author  Diogo Gonçalves
 * @description Service Layer class used to generate the Barcode/QR Code image.
 *              NOTE: Authentication is handled by the external credential COMM_BarcodeGeneration
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer                Date            Description
 * ------------------------------------------------------------------------------------
 * Diogo Gonçalves          11/04/2024      ECOMM-105: Original version
 */
public inherited sharing class COMM_SL_BarCodeGeneration {
    public static final String CONFIGLABEL = 'Barcode_Generation';
    private static COMM_IREP_CalloutSettingMdt calloutSettingsRep = new COMM_REP_CalloutSettingMdt();

    /**
     * @description Method to generate the Barcode/QR Code image in base64 format.
     *              Performs callout.
     * @param {String} codeText - text for the code to be generated
     * @param {String} format - Can be QR_CODE or EAN128
     * @returns {COMM_SL_BarcodeResponse}
     */
    public static COMM_SL_BarcodeResponse getBarCodeBase64(String codeText, String format) {
        COMM_OMS_CalloutSettings__mdt calloutConfiguration = calloutSettingsRep.getCalloutSetting(CONFIGLABEL);
        Map<String, String> headers = COMM_OMS_CalloutUtil.parseHeaders(calloutConfiguration.HTTP_Headers__c);
        String queryParameters = COMM_HttpCallout_Utility.getUrlQueryParameters(
            new Map<String, String>{ 'codeText' => codeText, 'format' => format }
        );
        String endpoint = calloutConfiguration.Endpoint_Server__c + calloutConfiguration.Endpoint_URI__c + queryParameters;

        HttpResponse response = COMM_OMS_CalloutUtil.doCallout(
            endpoint,
            calloutConfiguration.HTTP_Method__c,
            headers,
            null,
            calloutConfiguration.Timeout__c
        );
        if (response != null) {
            return (COMM_SL_BarcodeResponse) JSON.deserialize(response.getBody(), COMM_SL_BarcodeResponse.class);
        } else {
            return null;
        }
    }
}