force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/COMM_OMS_CalloutSettings__mdt.object-meta.xml
<CustomObject>
    <description>Callout Settinsg holds the configurations for callouts</description>
    <label>OMS Callout Setting</label>
    <pluralLabel>OMS Callout Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/Endpoint_Server__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Server__c</fullName>
    <description>This specifies the endpoint server for the integration - e.g. https://&lt;&lt;env&gt;&gt;.services.com/</description>
    <label>Endpoint Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/Endpoint_URI__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URI__c</fullName>
    <description>This species the URI for the integration service - e.g. territory_assignments/accounts/</description>
    <label>Endpoint URI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/HTTP_Headers__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Headers__c</fullName>
    <description>Contains the map of the HTPP Headers (HeaderKey=&gt;HeaderValue) separated by semicolons following: 
HeaderKey=&gt;HeaderValue;HeaderKey=&gt;HeaderValue</description>
    <inlineHelpText>Contains the map of the HTPP Headers (HeaderKey=&gt;HeaderValue) separated by semicolons following: 
HeaderKey=&gt;HeaderValue;HeaderKey=&gt;HeaderValue</inlineHelpText>
    <label>HTTP Headers</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <description>HTTP Method</description>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/QueryString__c.field-meta.xml
<CustomField>
    <fullName>QueryString__c</fullName>
    <label>QueryString</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout (Milliseconds)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/COMM_REP_CalloutSettingMdt.cls
/**
 * @author Rui Salgado
 * @description COMM_OMS_CalloutSettings__mdt util class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Rui Salgado      01/04/2024       Original version
 **/

public with sharing class COMM_REP_CalloutSettingMdt extends FW_SobjectRep implements COMM_IREP_CalloutSettingMdt {
    /**
     * Get COMM_OMS_CalloutSettings__mdt records by instanceName
     * @param instanceName
     * @return COMM_OMS_CalloutSettings__mdt
     */
    public COMM_OMS_CalloutSettings__mdt getCalloutSetting(String instanceName) {
        if (Test.isRunningTest()) {
            COMM_OMS_CalloutSettings__mdt configuration = new COMM_OMS_CalloutSettings__mdt();
            configuration.Endpoint_Server__c = 'Endpoint_Server';
            configuration.Endpoint_URI__c = 'Endpoint_URI';
            configuration.HTTP_Headers__c = 'HTTP_Headers=>123123';
            configuration.HTTP_Method__c = 'POST';
            configuration.QueryString__c = '';
            configuration.Timeout__c = 12000;
            return configuration;
        }

        COMM_OMS_CalloutSettings__mdt configuration = COMM_OMS_CalloutSettings__mdt.getInstance(instanceName);
        if (configuration == null) {
            throw new COMM_REP_CalloutSettingMdtException('Configuration not found for instance = ' + instanceName);
        }
        return configuration;
    }

    /**
     * @description Unified Settings exception
     */
    public class COMM_REP_CalloutSettingMdtException extends Exception {
    }
}