force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/COMM_OMS_CalloutSettings__mdt.object-meta.xml
<CustomObject>
    <description>Callout Settinsg holds the configurations for callouts</description>
    <label>OMS Callout Setting</label>
    <pluralLabel>OMS Callout Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/COMM_OMS_CalloutSettings__mdt/fields/Endpoint_Server__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Server__c</fullName>
    <description>This specifies the endpoint server for the integration - e.g. https://&lt;&lt;env&gt;&gt;.services.com/</description>
    <label>Endpoint Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_REP_CalloutSettingMdtTest.cls
/**
 * @author Rui Salgado
 * @description COMM_REP_CalloutSettingMdtTest class
 *
 * Modification Log
 * ----------------------------------------------------------------------------------------------
 * Developer        Date          Coverage(%)   Description
 * ----------------------------------------------------------------------------------------------
 * Rui Salgado      01/04/2024    71            Original version
 **/
@isTest
private with sharing class COMM_REP_CalloutSettingMdtTest {
    /**
     * @description Test method of COMM_REP_CalloutSettingMdt getCalloutSetting
     */
    private static COMM_IREP_CalloutSettingMdt calloutSettingsRep = new COMM_REP_CalloutSettingMdt();

    @isTest
    static void shouldGetValueByInstanceName() {
        Test.startTest();
        COMM_OMS_CalloutSettings__mdt setting = calloutSettingsRep.getCalloutSetting('Test');
        Test.stopTest();
        System.assert(!String.isBlank(setting.Endpoint_Server__c), 'Endpoint_Server__c could not be received');
    }
}