force-app/main/default/objects/COMM_QRCodePrefix__mdt/COMM_QRCodePrefix__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to store mapping of sub-category QR Code value prefixes</description>
    <label>QR Code Prefix</label>
    <pluralLabel>QR Code Prefixes</pluralLabel>
</CustomObject>

force-app/main/default/objects/COMM_QRCodePrefix__mdt/fields/COMM_Prefix__c.field-meta.xml
<CustomField>
    <fullName>COMM_Prefix__c</fullName>
    <description>Prefix to be used on the QR Code value for a given sub-category</description>
    <label>Prefix</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_REP_QRCodePrefixMdt.cls
/**
 * @author Diogo Gonçalves
 * @description COMM_QRCodePrefixMdt__mdt util class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Diogo Gonçalves      18/10/2024       Original version
 **/

 public class COMM_REP_QRCodePrefixMdt implements COMM_IREP_QRCodePrefixMdt {
    /**
     * Get COMM_QRCodePrefix__mdt records by instanceName
     * @param instanceName
     * @return COMM_QRCodePrefix__mdt
     */
    public COMM_QRCodePrefix__mdt getQRCodePrefix(String instanceName){
        if (Test.isRunningTest()) {
            COMM_QRCodePrefix__mdt qrCodePrefix = new COMM_QRCodePrefix__mdt();
            qrCodePrefix.COMM_Prefix__c = 'GWP';
            return qrCodePrefix;
        }

        return COMM_QRCodePrefix__mdt.getInstance(instanceName);
    }
}