force-app/main/default/objects/COMM_ProductLocationStock__c/COMM_ProductLocationStock__c.object-meta.xml
<CustomObject>
    <label>Product Location Stock</label>
    <nameField>
        <displayFormat>PLS-{0000000000}</displayFormat>
        <label>Product Location Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Location Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_ProductLocationStock__c/fields/COMM_Location__c.field-meta.xml
<CustomField>
    <fullName>COMM_Location__c</fullName>
    <description>OCI Location (Hour_00, Hour_01, ....)</description>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_ProductLocationStock__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Product Id</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Location Stocks</relationshipLabel>
    <relationshipName>Product_Location_Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_ProductLocationStock__c/fields/COMM_ProductLocation__c.field-meta.xml
<CustomField>
    <fullName>COMM_ProductLocation__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Identifier for the Product Location record. This is the ProductCode concatenated with the Location.

Examples: 

OPO_P1_premium_20240101_Hour_00,

OPO_P1_premium_20240101_Hour_01,

OPO_P1_premium_20240101_Subscriptions</description>
    <externalId>true</externalId>
    <label>Product Location</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/COMM_ProductLocationStock__c/fields/COMM_ReservedStock__c.field-meta.xml
<CustomField>
    <fullName>COMM_ReservedStock__c</fullName>
    <description>OCI Total Reserved stock on the location</description>
    <label>Reserved Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COMM_ProductLocationStock__c/fields/COMM_StockDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_StockDate__c</fullName>
    <description>OCI Stock Date</description>
    <label>Stock Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COMM_ProductLocationStock__c/fields/COMM_StockOnHand__c.field-meta.xml
<CustomField>
    <fullName>COMM_StockOnHand__c</fullName>
    <description>OCI Total Stock on the location</description>
    <label>Stock On Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Airport__c.field-meta.xml
<CustomField>
    <fullName>COMM_Airport__c</fullName>
    <description>Airport in which the product is available</description>
    <label>Airport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Airport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Alarmistic__c.field-meta.xml
<CustomField>
    <fullName>COMM_Alarmistic__c</fullName>
    <description>The alarmistic percentage defined in this field will be the same for the default capacity and the capacity defined for a specific period.</description>
    <label>Alarmistic %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ClosingOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_ClosingOperatingHours__c</fullName>
    <description>Specific time during which the product stops being operational to be sold to the customers</description>
    <label>Closing Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_CPMS__c.field-meta.xml
<CustomField>
    <fullName>COMM_CPMS__c</fullName>
    <description>Which CPMS provider is associated with park where the reservation was done</description>
    <label>Parking System Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_CPMS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_OpeningOperatingHours__c.field-meta.xml
<CustomField>
    <fullName>COMM_OpeningOperatingHours__c</fullName>
    <description>Specific time during which the product starts being operational to be sold to the customers</description>
    <label>Opening Operating Hours</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Park__c.field-meta.xml
<CustomField>
    <fullName>COMM_Park__c</fullName>
    <description>Park associated with the Product</description>
    <label>Park</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COMM_Park</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>COMM_SubCategory__c</fullName>
    <description>Used to define the sub-category of the product.</description>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Park</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Fast Lane</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Exempt Official Entity</fullName>
            </value>
            <value>
                <fullName>ANA + Entities</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>RAC / Shuttle NL</fullName>
            </value>
            <value>
                <fullName>Staff Company</fullName>
            </value>
            <value>
                <fullName>Staff Individual</fullName>
            </value>
            <value>
                <fullName>Fast Track Plus</fullName>
            </value>
            <value>
                <fullName>Lounge Adult</fullName>
            </value>
            <value>
                <fullName>Lounge Child</fullName>
            </value>
            <value>
                <fullName>Lounge Adult with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Child with shower</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non Schengen</fullName>
            </value>
            <value>
                <fullName>Lounge Child Non Schengen</fullName>
            </value>
            <value>
                <fullName>Terminal</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Lounge Adult Non -Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Adult Non -Schengen</label>
            </value>
            <value>
                <fullName>Lounge Child Non - Schengen</fullName>
                <isActive>false</isActive>
                <label>Lounge Child Non - Schengen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Tax__c.field-meta.xml
<CustomField>
    <fullName>COMM_Tax__c</fullName>
    <description>Defines the tax used for the product based on location</description>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>COMM_Airport__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continent</fullName>
            </value>
            <value>
                <fullName>Madeira</fullName>
            </value>
            <value>
                <fullName>Azores</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidFrom__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 00:00:00&quot;)</defaultValue>
    <description>Beginning date for which the product is deemed valid</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_ValidTo__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValidTo__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY()) + &quot; 23:59:59&quot;)</defaultValue>
    <description>End date for which the product is deemed valid</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_WhereProductAvailable__c.field-meta.xml
<CustomField>
    <fullName>COMM_WhereProductAvailable__c</fullName>
    <description>Multi Picklist that indicates in which platform the product will be available</description>
    <label>Where is the product available?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Subscriptions Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/COMM_Subscription.recordType-meta.xml
<RecordType>
    <fullName>COMM_Subscription</fullName>
    <active>true</active>
    <description>This record type will used to typify subscriptions</description>
    <label>Subscription</label>
</RecordType>

force-app/main/default/classes/COMM_REP_ProductLocationStockTest.cls
/**
 * @author           Daniel Reto
 * @description      COMM_REP_ProductLocationStock test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      13/05/2024      100            ECOMM-281,282,283: Original version
 **/
@isTest
private class COMM_REP_ProductLocationStockTest {
    private final static COMM_REP_ProductLocationStock PRODUCTLOCATIONSTOCK_REP = new COMM_REP_ProductLocationStock();

    @TestSetup
    static void makeData() {

        Time myTime = Time.newInstance(1, 2, 3, 0);
        // Insert Product
        List<Product2> productList = (List<Product2>) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'Product2',
            new Map<String, Object>{
                'Name' => 'Subscription Service',
                'ProductCode' => 'P0',
                'Description' => 'Subscription Service',
                'IsActive' => false,
                'Family' => 'Subscription',
                'COMM_Alarmistic__c' => 75,
                'COMM_WhereProductAvailable__c' => 'Subscriptions Portal',
                'COMM_ValidFrom__c' => System.now().addSeconds(30),
                'COMM_ValidTo__c' => System.now().addDays(2),
                'COMM_Airport__c' => 'LIS',
                'COMM_Tax__c' => 'Continent',
                'COMM_Park__c' => 'p0',
                'COMM_CPMS__c' => 'SKIDATA',
                'COMM_OpeningOperatingHours__c' => myTime,
                'COMM_ClosingOperatingHours__c' => myTime,
                'COMM_SubCategory__c' => 'Park',
                'RecordTypeId' => Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('COMM_Subscription').RecordTypeId
            }
        );
        
        // Insert Product Location Stock
        List<COMM_ProductLocationStock__c> productLocationStockList = (List<COMM_ProductLocationStock__c>) COMM_TestDataFactory.insertRecords(
            1,
            true,
            'COMM_ProductLocationStock__c',
            new Map<String, Object>{
                'COMM_Location__c' => COMM_OCI_Constants.PRODUCT_FAMILY_SUBSCRIPTION,
                'COMM_StockDate__c' => System.today(),
                'COMM_Product__c' => productList.get(0).Id,
                'COMM_ProductLocation__c' => productList.get(0).ProductCode + '_' + String.valueOf(System.now().formatGMT(COMM_OCI_Constants.DATE_FORMAT)) + '_' + COMM_OCI_Constants.PRODUCT_FAMILY_SUBSCRIPTION,
                'COMM_ReservedStock__c' => 90,
                'COMM_StockOnHand__c' => 100
            }
        );
    }

    @isTest
    static void getProductLocationStockToEraseTest() {
        
        List<COMM_ProductLocationStock__c> expectedProductLocationStockList = [
            SELECT Id, COMM_Product__c, COMM_Product__r.Name, COMM_Product__r.COMM_Alarmistic__c, toLabel(COMM_Product__r.Family)
            FROM COMM_ProductLocationStock__c
            LIMIT 1];

        Test.startTest();
        List<COMM_ProductLocationStock__c> actualList = PRODUCTLOCATIONSTOCK_REP.getProductLocationStockToErase();
        Test.stopTest();

        Assert.areEqual(expectedProductLocationStockList, actualList, 'retrieved ProductLocationStock does not match expected');
    }

    @isTest
    static void getProductLocationStockToEraseTwoParametersTest() {
        Product2 productRecord = [
            SELECT Id
            FROM Product2
            LIMIT 1].get(0);
        
        List<COMM_ProductLocationStock__c> expectedProductLocationStockList = [
            SELECT Id
            FROM COMM_ProductLocationStock__c
            LIMIT 1];

        Test.startTest();
        List<COMM_ProductLocationStock__c> actualList = PRODUCTLOCATIONSTOCK_REP.getProductLocationStockToErase(new List<String>{ productRecord.Id }, System.today().addDays(1));
        Test.stopTest();

        Assert.areEqual(expectedProductLocationStockList, actualList, 'retrieved ProductLocationStock does not match expected');
    }
    
}