force-app/main/default/objects/COMM_ProductLocationStock__c/COMM_ProductLocationStock__c.object-meta.xml
<CustomObject>
    <label>Product Location Stock</label>
    <nameField>
        <displayFormat>PLS-{0000000000}</displayFormat>
        <label>Product Location Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Location Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_ProductLocationStock__c/fields/COMM_AlarmisticPercExceeded__c.field-meta.xml
<CustomField>
    <fullName>COMM_AlarmisticPercExceeded__c</fullName>
    <description>Formula to identify if the Alarmistic % on related Product was exceeded.</description>
    <formula>AND(
 NOT(ISBLANK(COMM_OccupancyRate__c)),
 NOT(ISBLANK(COMM_Product__r.COMM_Alarmistic__c)),
 COMM_OccupancyRate__c &gt;= COMM_Product__r.COMM_Alarmistic__c
)</formula>
    <label>Alarmistic % Exceeded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_ProductLocationStock__c/fields/COMM_Product__c.field-meta.xml
<CustomField>
    <fullName>COMM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Product Id</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Location Stocks</relationshipLabel>
    <relationshipName>Product_Location_Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COMM_ProductLocationStock__c/fields/COMM_StockDate__c.field-meta.xml
<CustomField>
    <fullName>COMM_StockDate__c</fullName>
    <description>OCI Stock Date</description>
    <label>Stock Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/COMM_Alarmistic__c.field-meta.xml
<CustomField>
    <fullName>COMM_Alarmistic__c</fullName>
    <description>The alarmistic percentage defined in this field will be the same for the default capacity and the capacity defined for a specific period.</description>
    <label>Alarmistic %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/COMM_REP_ProductLocationStock.cls
/**
 * @author Daniel Reto
 * @description COMM_ProductLocationsStock__c repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto    08/05/2024       Original version
 **/
public inherited sharing class COMM_REP_ProductLocationStock extends FW_SobjectRep implements COMM_IREP_ProductLocationStock {
    
    /**
     * @description Get ProductLocationStock records to erase.
     *
     * @param productIds Set of Product Id's related with Product Locations Stock
     * @param initialDate Reference Date, to get older records
     * @return List of Product Locations Stock Records
     */
    public List<COMM_ProductLocationStock__c> getProductLocationStockToErase(List<String> productIds, Date initialDate) {
        return [
            SELECT Id
            FROM COMM_ProductLocationStock__c
            WHERE COMM_Product__c IN :productIds AND COMM_StockDate__c <: initialDate
            WITH USER_MODE
        ];
    }

    /**
     * @description Get ProductLocationStock where Occupancy Rate is higher than the related Product2 Alarmistic %.
     *
     * @param productLocationStockIds Set of Product Location Stock Id's
     * @return List of Product Locations Stock Records
     */
    public List<COMM_ProductLocationStock__c> getProductLocationStockToErase() {
        return [
            SELECT Id, COMM_Product__c, COMM_Product__r.Name, COMM_Product__r.COMM_Alarmistic__c, toLabel(COMM_Product__r.Family)
            FROM COMM_ProductLocationStock__c
            WHERE COMM_AlarmisticPercExceeded__c = TRUE
            WITH USER_MODE
        ];
    }
}