force-app/main/default/objects/Contact/fields/COMM_CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>COMM_CustomerNumber__c</fullName>
    <description>Number used to identify Customer in Commerce. Used for Update Calls using OCAPI.</description>
    <externalId>true</externalId>
    <label>Customer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/COMM_IntegrationRequestBody__c.field-meta.xml
<CustomField>
    <fullName>COMM_IntegrationRequestBody__c</fullName>
    <description>To set Customer Data integration body request detail in JSON format, for integration in Salesforce Commerce.</description>
    <label>Integration Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/COMM_REP_Contact.cls
/**
 * @author Daniel Lascas
 * @description Contact repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    21/02/2024       Original version
 * Daniel Lascas    09/07/2024       ECOMM-370: Original version
 **/
public inherited sharing class COMM_REP_Contact extends FW_SobjectRep implements COMM_IREP_Contact {
    /**
     * @description Retrieve a list of Contacts with fields required for
     * OCAPI requests by a set of Contact Ids
     *
     * @param contactIds Set of Contact Ids to query
     * @return List of Contacts Records found
     **/
    public List<Contact> getContactWithRequestFieldsByIds(Set<Id> contactIds) {
        return [
            SELECT Id, Email, COMM_IntegrationRequestBody__c, COMM_CustomerNumber__c
            FROM Contact
            WHERE Id IN :contactIds
            WITH SECURITY_ENFORCED
        ];
    }
}