force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FW_TH_JobExecutionTest.cls
@isTest
public class FW_TH_JobExecutionTest {
    @isTest
    static void jobExecutionTest(){
        User runningUser = FW_TestDataFactory.createUsers(1, true, 'System Administrator', null).get(0);
        system.runAs(runningUser){  
            Id batchDefinitionId = FW_TestDataFactory.createBatchDefinition(1, true).get(0).Id;
            List<Job_Execution__c> jobExecutionList = FW_TestDataFactory.createJobExecution(1, false, FW_DO_JobExecution.JOB_EXEC_RECORD_TYPE_INITIAL, batchDefinitionId);
            
            User adminUser = FW_TestDataFactory.createUsers(1, false, 'System Administrator', null)[0];
            test.startTest();
                System.runAs(adminUser){
                    insert jobExecutionList;
                    jobExecutionList.get(0).Run_with_Defaults__c = true;
                    update jobExecutionList;
                }
            test.stopTest();
            system.assertNotEquals(null, jobExecutionList.get(0).Id);
        }
    }
}