force-app/main/default/objects/COMM_LanguageMapping__mdt/COMM_LanguageMapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to map language values used in Commerce to Core</description>
    <label>Language Mapping</label>
    <pluralLabel>Language Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/COMM_LanguageMapping__mdt/fields/COMM_ValueInCommerce__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValueInCommerce__c</fullName>
    <description>Value of the language in Commerce</description>
    <label>Value in Commerce</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_LanguageMapping__mdt/fields/COMM_ValueInSalesforce__c.field-meta.xml
<CustomField>
    <fullName>COMM_ValueInSalesforce__c</fullName>
    <description>Value of the language in Salesforce</description>
    <label>Value in Salesforce</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_DO_LanguageMappingTest.cls
/**
 * @author Daniel Lascas
 * @description COMM_DO_LanguageMapping test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    25/03/2024      100            Original version
 **/
@isTest
private class COMM_DO_LanguageMappingTest {
    private static final COMM_DO_LanguageMapping MAPPING_DO = new COMM_DO_LanguageMapping();
    @isTest
    static void getExistingMappingTest() {
        //Retrieve first setting to use for testing
        COMM_LanguageMapping__mdt expectedSetting = COMM_LanguageMapping__mdt.getAll().values()[0];
        Test.startTest();
        String mappedValue = MAPPING_DO.getSalesforceLanguage(expectedSetting.COMM_ValueInCommerce__c);
        Test.stopTest();
        Assert.areEqual(expectedSetting.COMM_ValueInSalesforce__c, mappedValue, 'mapped value does not match expected');
    }

    @isTest
    static void getNonExistingMappingTest() {
        //Test for when Metadata Record doesn't exist
        Test.startTest();
        String mappedValue = MAPPING_DO.getSalesforceLanguage('noMap');
        Test.stopTest();
        Assert.areEqual('noMap', mappedValue, 'mapped value does not match expected');
    }
}