force-app/main/default/objects/COMM_ProductSetting__c/COMM_ProductSetting__c.object-meta.xml
<CustomObject>
    <label>Product Setting</label>
    <nameField>
        <label>Product Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COMM_ProductSetting__c/fields/COMM_CommerceEssential__c.field-meta.xml
<CustomField>
    <fullName>COMM_CommerceEssential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Commerce Essential?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_ProductSetting__c/fields/COMM_CommerceMappingAttribute__c.field-meta.xml
<CustomField>
    <fullName>COMM_CommerceMappingAttribute__c</fullName>
    <label>Commerce Mapping Attribute</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_ProductSetting__c/fields/COMM_CoreEssential__c.field-meta.xml
<CustomField>
    <fullName>COMM_CoreEssential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Core Essential?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COMM_ProductSetting__c/fields/COMM_EligibleProductType__c.field-meta.xml
<CustomField>
    <fullName>COMM_EligibleProductType__c</fullName>
    <label>Eligible Product Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COMM_ProductSetting__c/fields/COMM_FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FieldAPIName__c</fullName>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COMM_ProductSetting__c/fields/COMM_FieldName__c.field-meta.xml
<CustomField>
    <fullName>COMM_FieldName__c</fullName>
    <label>FieldName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COMM_REP_ProductSetting.cls
/**
 * @author Ruben Rodrigues
 * @description COMM_ProductSetting__c repository interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Ruben Rodrigues    21/05/2024       Original version
 **/
public class COMM_REP_ProductSetting extends FW_SobjectRep implements COMM_IREP_ProductSetting{

    /**
     * @description Get all records marked as Essential for Core on the COMM_ProductSetting__c.
     *
     * @return List with all records marked as Essential for Core on the COMM_ProductSetting__c
     */
    public List<COMM_ProductSetting__c> getCoreEssentialFields(){
        return [SELECT Name,COMM_FieldName__c,COMM_CoreEssential__c, COMM_CommerceMappingAttribute__c,
                COMM_EligibleProductType__c, COMM_FieldAPIName__c
                FROM COMM_ProductSetting__c
                WHERE COMM_CoreEssential__c = TRUE
                WITH USER_MODE];
    }
    
    /**
     * @description Get all records marked as Essential for Commerce on the COMM_ProductSetting__c.
     *
     * @return List with all records marked as Essential for Commerce on the COMM_ProductSetting__c
     */
    public List<COMM_ProductSetting__c> getCommerceEssentialFields(){
        return [SELECT Name,COMM_FieldName__c, COMM_CommerceEssential__c, COMM_CommerceMappingAttribute__c,
                COMM_EligibleProductType__c, COMM_FieldAPIName__c
                FROM COMM_ProductSetting__c
                WHERE COMM_CommerceEssential__c = TRUE
				WITH USER_MODE];
    }
    
    /**
     * @description Get the values of the custom field from COMM_ProductSetting__c.
     *
     * @return List with all records with the values of the custom field from COMM_ProductSetting__c
     */
    public List<COMM_ProductSetting__c> getFieldAPINames(){
        return [SELECT Id,
                COMM_FieldAPIName__c
                FROM COMM_ProductSetting__c
                WITH USER_MODE];
    }
}