force-app/main/default/objects/COMM_TaxValueConfiguration__mdt/COMM_TaxValueConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to store tax applied to sold products in invoices</description>
    <label>Tax Value Configuration</label>
    <pluralLabel>Tax Value Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/COMM_TaxValueConfiguration__mdt/fields/COMM_TaxValue__c.field-meta.xml
<CustomField>
    <fullName>COMM_TaxValue__c</fullName>
    <description>Value of tax in percentage</description>
    <label>Tax Value</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/COMM_REP_TaxValueConfigurationMdt.cls
/**
 * @author Daniel Reto
 * @description Tax Value Configuration repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      18/10/2024       Original version
 **/

 public with sharing class COMM_REP_TaxValueConfigurationMdt extends FW_SobjectRep implements COMM_IREP_TaxValueConfigurationMdt {
    /**
     * @description get value of Tax Value Configuration TaxValue__c
     * @param instanceName instance name
     * @return Value of Instance COMM_TaxValue__c
     */
    public Decimal getTaxValueConfig(String instanceName) {
        COMM_TaxValueConfiguration__mdt taxValueConfigInstance;
        if (Test.isRunningTest() && instanceName != null) {
            taxValueConfigInstance = new COMM_TaxValueConfiguration__mdt();
            taxValueConfigInstance.COMM_TaxValue__c = 23;
        } else {
            taxValueConfigInstance = COMM_TaxValueConfiguration__mdt.getInstance(instanceName);
            if (taxValueConfigInstance == null) {
                throw new COMM_REP_TaxValueConfigurationMdtException('Invalid instance name ' + instanceName);
            }
        }
        return taxValueConfigInstance.COMM_TaxValue__c;
    }

    /**
     * @description Tax Value Configuration exception
     */
    public class COMM_REP_TaxValueConfigurationMdtException extends Exception {
    }
}